Repository datarobot/datarobot-user-models, pull requests merged in 2020-10, with the labels that each got.

#156 fix failing r test
  tests/drum/test_fit.py
Labels: 00 - Ready for Review, Auto Merge on Green

#158 [RAPTOR-3574] update drum test docker with required R libs
  docker/drum_integration_tests_base/Dockerfile
Labels: 00 - Ready for Review, Auto Merge on Green

#154 Lior/raptor 3665
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/drum/drum_server_utils.py
  tests/drum/test_other_cases.py
  tools/r2d2/README.md
  tools/r2d2/custom.py
Labels: 00 - Ready for Review

#160 [RAPTOR-3554] show error if uwsgi is not available in production mode
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/requirements.txt
Labels: 00 - Ready for Review

#162 [RAPTOR-3741] add options for multiclass
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  tests/drum/test_args_parser.py
Labels: 00 - Ready for Review

#164 [RAPTOR-3576] bump tensoflow versions to 2.2.1 and unify them across the repo
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  dev_env/java_nginx_env/dr_requirements.txt
  dev_env/python3_nginx_env/dr_requirements.txt
  dev_env/python3_nginx_env/requirements.txt
  dev_env/rlang_nginx_env/dr_requirements.txt
  model_templates/inference/python3_keras/keras_reg.h5
  model_templates/inference/python3_keras_joblib/custom.py
  model_templates/inference/python3_keras_joblib/model_deserializer.py
  model_templates/inference/python3_keras_vizai_joblib/model_utils.py
  model_templates/training/python3_keras_joblib/example_code.py
  model_templates/training/python3_keras_vizai_joblib/README.md
  model_templates/training/python3_keras_vizai_joblib/model_utils.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  requirements.txt
  tests/fixtures/drop_in_model_artifacts/Keras.ipynb
  tests/fixtures/drop_in_model_artifacts/keras_bin.h5
  tests/fixtures/drop_in_model_artifacts/keras_reg.h5
Labels: 00 - Ready for Review, Auto Merge on Green

#172 [YOLO] remove bad codeowners
  CODEOWNERS
Labels: 00 - Ready for Review

#167 Switch R envs to flask because of OOM
  dev_env/rlang_nginx_env/start_server.sh
  public_dropin_environments/r_lang/start_server.sh
Labels: 00 - Ready for Review

#171 Fix docker image repo names in documentation
  docker/java_dropin_env_base/README.md
  docker/python3_dropin_env_base/README.md
  docker/r_dropin_env_base/README.md
Labels: 00 - Ask for Review on Green, Auto Merge on Green

#168 Add IntelliJ project file (*.iml) to gitignore
  .gitignore
Labels: Ready for Review

#173 Update deps: pandas==1.1.0, rpy2==3.3.6
  dev_env/python3_nginx_env/requirements.txt
  dev_env/rlang_nginx_env/dr_requirements.txt
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
  requirements.txt
Labels: 00 - Ready for Review

#174 Deps up: pandas==1.1.0, numpy==1.19.0
  public_dropin_environments/python3_pmml/requirements.txt
  tests/fixtures/cmrun_docker_env/requirements.txt
Labels: 00 - Ready for Review

#176 [RAPTOR-3576] handle the case where standalone keras is not installed
  custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
Labels: 00 - Ready for Review, Auto Merge on Green, Needs Review: Custom Models

#165 [RAPTOR-3574] model templates for unstructured
  model_templates/inference/python3_unstructured/README.md
  model_templates/inference/python3_unstructured/custom.py
  model_templates/inference/r_unstructured/README.md
  model_templates/inference/r_unstructured/custom.R
Labels: 00 - Ready for Review, Auto Merge on Green

#181 [RAPTOR-3768] fix process detection for memory monitoring
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/memory_monitor.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  tests/drum/test_performance_check.py
Labels: 00 - Ready for Review

#178 [RAPTOR-3789] add multiclass support to H2OPredictor.
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictor.scala
  dev_env/java_nginx_env/dr_requirements.txt
  dev_env/python3_nginx_env/dr_requirements.txt
  dev_env/rlang_nginx_env/dr_requirements.txt
  model_templates/inference/h2o_mojo/README.md
  model_templates/inference/h2o_mojo/multiclass/XGBoost_3_AutoML_20201016_143029.zip
  model_templates/inference/h2o_pojo/README.md
  model_templates/inference/h2o_pojo/multiclass/XGBoost_3_AutoML_20201016_143029.java
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/test_inference.py
  tests/fixtures/drop_in_model_artifacts/XGBoost_3_AutoML_20201016_143029.java
  tests/fixtures/drop_in_model_artifacts/XGBoost_grid__1_AutoML_20200717_163214_model_159.java
  tests/fixtures/drop_in_model_artifacts/drf_887c2e5b_0941_40b7_ae26_cae274c4b424.java
  tests/fixtures/drop_in_model_artifacts/mojo_multi.zip
  tests/functional/test_drop_in_environments.py
Labels: Auto Merge on Green, Ready for Review

#182 disable functional tests on dev envs
  dev_env/java_nginx_env/Dockerfile
  dev_env/java_nginx_env/README.md
  dev_env/java_nginx_env/dr_requirements.txt
  dev_env/java_nginx_env/env_info.json
  dev_env/java_nginx_env/requirements.txt
  dev_env/java_nginx_env/start_server.sh
  dev_env/python3_nginx_env/Dockerfile
  dev_env/python3_nginx_env/README.md
  dev_env/python3_nginx_env/__init__.py
  dev_env/python3_nginx_env/dr_requirements.txt
  dev_env/python3_nginx_env/env_info.json
  dev_env/python3_nginx_env/fit.sh
  dev_env/python3_nginx_env/requirements.txt
  dev_env/python3_nginx_env/start_server.sh
  dev_env/rlang_nginx_env/Dockerfile
  dev_env/rlang_nginx_env/README.md
  dev_env/rlang_nginx_env/dr_requirements.txt
  dev_env/rlang_nginx_env/env_info.json
  dev_env/rlang_nginx_env/fit.sh
  dev_env/rlang_nginx_env/start_server.sh
  jenkins/test3_drop_in_envs.sh
  tests/functional/test_dev_envs.py
Labels: 00 - Ready for Review, Auto Merge on Green

#183 [RAPTOR-3554] hide 'pip show uwsgi' output
  custom_model_runner/datarobot_drum/drum/args_parser.py
Labels: 00 - Ready for Review

#179 [RAPTOR-3574] don't assign default charset if mimetype is binary
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/unstructured_helpers.py
  model_templates/inference/python3_unstructured/README.md
  model_templates/inference/r_unstructured/README.md
  tests/drum/test_unstructured_mode.py
Labels: 00 - Ready for Review, Auto Merge on Green

#187 Release drum v1.4.0
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#180 [RAPTOR-3700] Sparse Drum
  .gitattributes
  README.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
  model_templates/training/python3_sparse/README.md
  model_templates/training/python3_sparse/custom.py
  model_templates/training/python3_sparse/model-metadata.yaml
  public_dropin_environments/python3_keras/fit.sh
  public_dropin_environments/python3_pytorch/fit.sh
  public_dropin_environments/python3_sklearn/fit.sh
  public_dropin_environments/python3_xgboost/fit.sh
  public_dropin_environments/r_lang/fit.sh
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/testdata/sparse.mtx
  tests/testdata/sparse_target.csv
Labels: Ready for Review

#186 [RAPTOR-3569] change start_server.sh/fit.sh to take target_type from …
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/java_h2o/start_server.sh
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/fit.sh
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/fit.sh
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/fit.sh
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/fit.sh
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/fit.sh
  public_dropin_environments/r_lang/start_server.sh
  tests/drum/constants.py
  tests/drum/test_fit.py
Labels: 00 - Ready for Review, Auto Merge on Green

#188 Fix readme, release v1.4.0
  README.md
Labels: 00 - Ready for Review

#189 [Raptor-3829] H2O Driverless AI Mojo Suport
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictorPipeline.scala
  model_templates/inference/h2o_mojo_pipeline/README.md
Labels: Ready for Review

#192 [RAPTOR-3841] Implement predictUnstructured endpoint for DRUM uwsgi
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/unstructured_helpers.py
  custom_model_runner/requirements.txt
  model_templates/inference/python3_unstructured/custom.py
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/Dockerfile
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/test_unstructured_mode.py
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
Labels: 00 - Ready for Review

#190 [RAPTOR-3835] Add more realistic multiclass examples
  model_templates/inference/python3_pytorch_multiclass/README.md
  model_templates/inference/python3_pytorch_multiclass/artifact.pth
  model_templates/inference/python3_pytorch_multiclass/class_labels.txt
  model_templates/inference/python3_pytorch_multiclass/custom.py
  model_templates/inference/python3_pytorch_multiclass/expected_columns.pkl
  model_templates/inference/python3_pytorch_multiclass/model_utils.py
  model_templates/inference/python3_pytorch_multiclass/preprocessing.py
  model_templates/inference/python3_pytorch_multiclass/preprocessor.pkl
  model_templates/inference/python3_pytorch_multiclass/requirements.txt
  model_templates/training/python3_pytorch_multiclass/README.md
  model_templates/training/python3_pytorch_multiclass/custom.py
  model_templates/training/python3_pytorch_multiclass/model_utils.py
  model_templates/training/python3_pytorch_multiclass/preprocessing.py
  model_templates/training/python3_pytorch_multiclass/requirements.txt
  tests/functional/conftest.py
  tests/functional/test_inference_model_templates.py
  tests/functional/test_training_model_templates.py
Labels: 00 - Ready for Review

#193 Change dep from numpy>=1.19.0 to numpy<1.19.0
  docker/java_dropin_env_base/Dockerfile
  docker/python3_dropin_env_base/Dockerfile
  docker/r_dropin_env_base/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  requirements.txt
  tests/fixtures/cmrun_docker_env/requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green

#195 [YOLO] remove unneeded artifact
  model_templates/inference/python3_pytorch_multiclass/artifact.pth
  model_templates/inference/python3_pytorch_multiclass/expected_columns.pkl
  model_templates/inference/python3_pytorch_multiclass/preprocessor.pkl
Labels: 00 - Ready for Review

#196 switch public envs from Flask to uwsgi
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/java_h2o/start_server.sh
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/start_server.sh
Labels: 00 - Ready for Review, Auto Merge on Green
