Repository datarobot/datarobot-user-models, pull requests merged in 2020-08, with the labels that each got.

#103 Documentation for Drum Push
  MODEL-METADATA.md
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/push.py
  model_templates/inference/python3_sklearn/model-metadata.yaml
  model_templates/training/python3_sklearn/model-metadata.yaml
  tests/drum/test_units.py
Labels: Ready for Review

#101 [RAPTOR-3204, RAPTOR-3205] Better errors when errors occur in hooks, model loading or on predict
  custom_model_runner/datarobot_drum/drum/model_adapter.py
Labels: Auto Merge on Green

#109 Update test docker: install nginx, fix requirements
  docker/drum_integration_tests_base/Dockerfile
  requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green

#106 [RAPTOR-3258] small fixes for --docker param
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: 00 - Ready for Review

#104 [RAPTOR-3248] addin H2O models support
  .gitignore
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/Makefile
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictor.scala
  model_templates/inference/h2o_mojo/README.md
  model_templates/inference/h2o_mojo/binary/XGBoost_grid__1_AutoML_20200717_163214_model_159.zip
  model_templates/inference/h2o_mojo/lendingclub/GBM_model_python_1589382591366_1.zip
  model_templates/inference/h2o_mojo/readmission/DeepLearning_model_python_1589382591366_91.zip
  model_templates/inference/h2o_mojo/regression/drf_887c2e5b_0941_40b7_ae26_cae274c4b424.zip
  model_templates/inference/h2o_pojo/README.md
  model_templates/inference/h2o_pojo/binary/XGBoost_grid__1_AutoML_20200717_163214_model_159.java
  model_templates/inference/h2o_pojo/lending_club/GBM_model_python_1589382591366_1.java
  model_templates/inference/h2o_pojo/regression/drf_887c2e5b_0941_40b7_ae26_cae274c4b424.java
  model_templates/inference/h2o_pojo/sar/XGBoost_model_python_1589382591366_94.java
  public_dropin_environments/java_h2o/Dockerfile
  public_dropin_environments/java_h2o/README.md
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/java_h2o/start_server.sh
  tests/drum/test_custom_model.py
  tests/fixtures/drop_in_model_artifacts/mojo_bin.zip
  tests/fixtures/drop_in_model_artifacts/mojo_reg.zip
  tests/fixtures/drop_in_model_artifacts/pojo_bin/XGBoost_grid__1_AutoML_20200717_163214_model_159.java
  tests/fixtures/drop_in_model_artifacts/pojo_reg/drf_887c2e5b_0941_40b7_ae26_cae274c4b424.java
  tests/functional/conftest.py
  tests/functional/test_inference_model_templates.py
Labels: 00 - Ready for Review, Auto Merge on Green

#102 Release DRUM 1.1.4 and env update place holder
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#111 [RAPTOR-3246] changes for feedback from Jake Snyder
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/requirements.txt
  model_templates/training/python3_sklearn/README.md
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
Labels: Ready for Review

#114 [RAPTOR-3292] update pytorch env version id
  public_dropin_environments/python3_pytorch/env_info.json
Labels: 00 - Ready for Review, Auto Merge on Green

#116 Skip feature impact test before FI API is available in the API client
  tests/functional/test_drop_in_environments.py
Labels: 00 - Ready for Review

#115 [RAPTOR-3319] allow to enforce run language
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  tests/drum/test_custom_model.py
Labels: 00 - Ready for Review

#118 [RAPTOR-3342] relocate import sklearn
  custom_model_runner/datarobot_drum/drum/model_adapter.py
Labels: 00 - Ready for Review

#120 [RAPTOR-3406] Make order of extensions and files deterministic in error messages
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
Labels: 00 - Ready for Review

#121 release drum v1.2.0 and update environments
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  dev_env/java_nginx_env/dr_requirements.txt
  dev_env/python3_nginx_env/dr_requirements.txt
  dev_env/rlang_nginx_env/dr_requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Auto Merge on Green

#123 Switch drop-in envs to work with uwsgi server with one worker
  dev_env/java_nginx_env/Dockerfile
  dev_env/python3_nginx_env/Dockerfile
  dev_env/rlang_nginx_env/Dockerfile
  docker/java_dropin_env_base/Dockerfile
  docker/java_dropin_env_base/README.md
  docker/python3_dropin_env_base/Dockerfile
  docker/python3_dropin_env_base/README.md
  docker/r_dropin_env_base/Dockerfile
  docker/r_dropin_env_base/README.md
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/java_h2o/start_server.sh
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/start_server.sh
Labels: 00 - Ready for Review

#124 Update repo readme with git-lfs instructions
  README.md
Labels: 00 - Ready for Review
