Repository datarobot/datarobot-user-models, pull requests merged in 2020-09, with the labels that each got.

#125 [RAPTOR-3435] replace heavier VGG16 with lightweight MobileNet net
  custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
  model_templates/inference/python3_keras_vizai_joblib/artifact.joblib
  model_templates/inference/python3_keras_vizai_joblib/model_utils.py
  model_templates/training/python3_keras_vizai_joblib/model_utils.py
  model_templates/training/python3_keras_vizai_joblib/vgg16_weights_tf_dim_ordering_tf_kernels_notop.h5
Labels: Ready for Review

#128 [RAPTOR-3337]fix situation where the output dir is inside the code dir
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/drum/test_units.py
Labels: Ready for Review

#131 [RAPTOR-2697] add hook to read dataset file and move reading into Py/R/Java context
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictor.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  dev_env/java_nginx_env/dr_requirements.txt
  dev_env/java_nginx_env/env_info.json
  dev_env/python3_nginx_env/dr_requirements.txt
  dev_env/python3_nginx_env/env_info.json
  dev_env/rlang_nginx_env/dr_requirements.txt
  dev_env/rlang_nginx_env/env_info.json
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/fixtures/all_hooks_custom.R
  tests/fixtures/all_hooks_custom.py
Labels: 00 - Ready for Review

#135 [RAPTOR-2697] fix handling missing values in R
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  dev_env/java_nginx_env/dr_requirements.txt
  dev_env/java_nginx_env/env_info.json
  dev_env/python3_nginx_env/dr_requirements.txt
  dev_env/python3_nginx_env/env_info.json
  dev_env/rlang_nginx_env/dr_requirements.txt
  dev_env/rlang_nginx_env/env_info.json
  model_templates/inference/r_lang/custom.R
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/fixtures/custom.R
  tests/fixtures/load_model_custom.R
Labels: 00 - Ready for Review, Auto Merge on Green

#137 [RAPTOR-3430] mlops: adding mlops monitoring support
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_mlops_monitoring.py
Labels: Auto Merge on Green

#136 [RAPTOR-3506] refactoring drum integration tests
  tests/drum/__init__.py
  tests/drum/conftest.py
  tests/drum/constants.py
  tests/drum/drum_server_utils.py
  tests/drum/locally-run-drum-tests.sh
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_custom_model.py
  tests/drum/test_drum_runtime.py
  tests/drum/test_drum_server_failures.py
  tests/drum/test_fit_inference.py
  tests/drum/test_mlops_monitoring.py
  tests/drum/test_other_cases.py
  tests/drum/test_performance_check.py
  tests/drum/test_validation_check.py
  tests/drum/utils.py
Labels: 00 - Ready for Review, Auto Merge on Green

#138 [RAPTOR-3496] fix drum push
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/push.py
  model_templates/training/python3_sklearn/model-metadata.yaml
  tests/conftest.py
  tests/functional/test_drum_push.py
Labels: Auto Merge on Green, Ready for Review

#130 [RAPTOR-3497] unstructured mode - drop 1
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_unstructured_mode.py
  tests/fixtures/unstructured_custom.R
  tests/fixtures/unstructured_custom.py
  tests/testdata/unstructured_data.txt
Labels: 00 - Ready for Review, Auto Merge on Green

#147 [RAPTOR-3643] import keras from TF in drum keras predictor
  custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
Labels: 00 - Ready for Review
