Repository datarobot/datarobot-user-models, pull requests merged in 2020-07, with the labels that each got.

#61 [RAPTOR-2994] uncomment tests
  jenkins/test3_drop_in_envs.sh
Labels: Auto Merge on Green, Ready for Review

#59 [RAPTOR-3025] Alpha Testing Feedback
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
  tests/drum/test_custom_model.py
Labels: Auto Merge on Green

#49 [RAPTOR-2904] Add flag and start dummy server to propagate imports/pipeline failures
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/drum/server.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  tests/drum/test_custom_model.py
Labels: Auto Merge on Green

#66 Fix type change in CustomTrainingBlueprint
  tests/functional/tmp_training_fixtures.py
Labels: Auto Merge on Green

#65 [RAPTOR-3088] Use custom status code to propagate drum pipeline initialization failure
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/drum/server.py
  tests/drum/test_custom_model.py
Labels: Auto Merge on Green

#69 Functional test now uses client for custom training models
  README.md
  requirements_dev.txt
  tests/functional/test_training_model_templates.py
  tests/functional/tmp_training_fixtures.py
Labels: Auto Merge on Green

#73 [RAPTOR-3088] Hide error server output (similarly to pred server output)
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  tests/drum/test_custom_model.py
Labels: Auto Merge on Green

#70 [MODEL-4201] New Simple Custom Training Models Hook And Test
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/__init__.py
  custom_model_runner/datarobot_drum/drum/custom_fit_wrapper.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  model_templates/training/python3_sklearn/create_pipeline.py
  model_templates/training/simple/my_first_pipeline.py
  tests/drum/test_custom_model.py
Labels: Ready for Review

#71 [DOC-2145] update docs
  .github/pull_request_template.md
  README.md
  custom_model_runner/README.md
  model_templates/inference/java_codegen/README.md
  model_templates/inference/python3_keras/README.md
  model_templates/inference/python3_keras_joblib/README.md
  model_templates/inference/python3_pmml/README.md
  model_templates/inference/python3_pytorch/README.md
  model_templates/inference/python3_sklearn/README.md
  model_templates/inference/python3_xgboost/README.md
  model_templates/inference/r_lang/README.md
Labels: 00 - Ready for Review, Auto Merge on Green

#74 [DOC-2145] update docs
  .github/pull_request_template.md
  README.md
  custom_model_runner/README.md
Labels: 00 - Ready for Review, Auto Merge on Green

#76 [DOC-2145] update docs
  README.md
  custom_model_runner/README.md
  model_templates/inference/python3_pmml/README.md
Labels: 00 - Ready for Review

#77 [RAPTOR-2091] Raise exceptions instead of exiting program so that DrumRuntime can do post-processing
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_predictor/r_predictor.py
Labels: Auto Merge on Green

#79 [RAPTOR-3153] install requirements file from the jarvis triggered script
  jenkins/test3_drop_in_envs.sh
  requirements_dev.txt
  requirements_test.txt
Labels: 00 - Ready for Review, Auto Merge on Green

#78 [DOC-2145] update docs
  README.md
  custom_model_runner/README.md
Labels: 00 - Ready for Review, Auto Merge on Green

#75 Publish drum v1.1.3, switch staging envs to use drum v1.1.3
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  docker/drum_integration_tests_base/.gitignore
  jenkins/test3_mlpiper_custom_models.sh
  model_templates/inference/python3_xgboost/xgb_reg.pkl
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/start_server.sh
  requirements.txt
  tests/drum/test_custom_model.py
  tests/fixtures/drop_in_model_artifacts/xgb_bin.pkl
  tests/fixtures/drop_in_model_artifacts/xgb_reg.pkl
Labels: 00 - Ready for Review

#86 Update drum_integration_tests_base docker
  docker/drum_integration_tests_base/Dockerfile
  docker/drum_integration_tests_base/build_test_docker.sh
Labels: 00 - Ready for Review, Auto Merge on Green

#88 [RAPTOR-3220] unify all the pipelines into one pipeline template
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/resource/pipelines/java_predictor.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/java_predictor_for_server.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/python_predictor_for_server.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/r_predictor.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/r_predictor_for_server.json.j2
Labels: 00 - Ready for Review, Auto Merge on Green

#90 [RAPTOR-3220] refactoring: separate predictors by language from mlpiper components
  custom_model_runner/CHANGELOG.md
  custom_model_runner/Makefile
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/__init__.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/Makefile
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/__init__.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/BasePredictor.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/PredictorEntryPoint.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/__init__.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_common_code/__init__.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_common_code/common.R
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/__init__.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/resource/components/Python/csv_to_df/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/csv_to_df/csv_to_df.py
  custom_model_runner/datarobot_drum/resource/components/Python/df_to_csv/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/df_to_csv/df_to_csv.py
  custom_model_runner/datarobot_drum/resource/components/Python/df_to_shared_mem/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/df_to_shared_mem/df_to_shmem.py
  custom_model_runner/datarobot_drum/resource/components/Python/external_runner/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/external_runner/external_runner.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/__init__.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/java_predictor/Makefile
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/python_predictor/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_common_code/__init__.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_predictor/__init__.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_predictor/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/shared_mem_to_df/__init__.py
  custom_model_runner/datarobot_drum/resource/components/Python/shared_mem_to_df/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/shared_mem_to_df/shmem_to_df.py
  custom_model_runner/datarobot_drum/resource/pipelines/external_prediction_server_runner.json
  custom_model_runner/datarobot_drum/resource/pipelines/external_runner.json
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
Labels: 00 - Ready for Review, Auto Merge on Green

#92 [RAPTOR-3220] refactoring: clean up after prev patch
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
Labels: 00 - Ready for Review

#96 R training functional tests
  tests/functional/test_training_model_templates.py
Labels: Ready for Review

#95 [RAPTOR-3220] don't log exception if args were not parsed
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  tests/drum/test_custom_model.py
Labels: 00 - Ready for Review, Auto Merge on Green

#87 Drum push + metadata file
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/push.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  model_templates/inference/python3_sklearn/model-metadata.yaml
  model_templates/training/python3_sklearn/model-metadata.yaml
  requirements.txt
  requirements_test.txt
  tests/drum/locally-run-drum-tests.sh
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_custom_model.py
  tests/drum/test_units.py
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
  tests/fixtures/user_permissions.json
  tests/functional/conftest.py
Labels: Ready for Review

#100 [RAPTOR-3249] don't use experimental methods that assume dependency management
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_units.py
  tests/functional/test_drop_in_environments.py
  tests/functional/test_inference_model_templates.py
  tests/functional/test_training_model_templates.py
Labels: Priority: Blocker, Ready for Review

#94 [RAPTOR-3238] Allow docker flag to take a directory
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/requirements.txt
  requirements.txt
  tests/drum/test_custom_model.py
Labels: Ready for Review

#105 [RAPTOR-3220] import only required language predictor
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
Labels: 00 - Ready for Review
