Repository datarobot/datarobot-user-models, pull requests merged in 2020-12, with the labels that each got.

#236 [RAPTOR-3979][RAPTOR-4016][RAPTOR-4017] Transform endpoint using arrow/mtx
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  model_templates/training/python3_sklearn_transform/README.md
  model_templates/training/python3_sklearn_transform/create_transform_pipeline.py
  model_templates/training/python3_sklearn_transform/custom.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_inference.py
  tests/fixtures/drop_in_model_artifacts/sklearn_transform.pkl
  tests/fixtures/drop_in_model_artifacts/sklearn_transform_dense.pkl
  tests/fixtures/transform_custom.py
Labels: Ready for Review

#237 [RAPTOR-3968] Allow DRUM multiclass with only 2 labels
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/torch_predictor.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/xgboost_predictor.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/drum_server_utils.py
  tests/drum/test_args_parser.py
  tests/drum/test_fit.py
  tests/drum/test_fit_variety.py
  tests/drum/test_inference.py
  tests/drum/test_mlops_monitoring.py
  tests/drum/test_performance_check.py
  tests/drum/test_validation_check.py
  tests/drum/utils.py
Labels: 00 - Ready for Review, Needs Review: Custom Models

#238 [RAPTOR-3784] compare host and container drum versions - drop 2
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: 00 - Ready for Review

#231 [RAPTOR-4030] add support for receiving regular binary data for /predict endpoint
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictor.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictorPipeline.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/server.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/drum/test_drum_server_failures.py
  tests/drum/test_inference.py
  tests/drum/test_unstructured_mode.py
  tests/fixtures/drop_in_model_artifacts/sklearn_reg_sparse.pkl
Labels: 00 - Ready for Review, Auto Merge on Green

#246 [RAPTOR-4106] add monitoring to R and Java predictors
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#245 [RAPTOR-3660] pred consistency check
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/utils.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_drum_server_failures.py
  tests/drum/test_fit.py
  tests/drum/test_fit_variety.py
  tests/drum/test_inference.py
  tests/drum/test_mlops_monitoring.py
  tests/drum/test_other_cases.py
  tests/drum/test_performance_check.py
  tests/drum/test_unstructured_mode.py
  tests/drum/test_validation_check.py
  tests/fixtures/custom_pred_consistency/__init__.py
  tests/fixtures/custom_pred_consistency/custom.py
  tests/functional/test_drum_push.py
Labels: Ready for Review

#249 [RAPTOR-4183] refactoring: read input data as binary and pass into predictor
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictor.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/templates/custom_python_template.py.j2
  custom_model_runner/datarobot_drum/resource/templates/custom_r_template.R.j2
  tests/drum/test_units.py
  tests/fixtures/all_predict_structured_hooks_custom.R
  tests/fixtures/all_predict_structured_hooks_custom.py
  tests/fixtures/custom_pred_consistency/custom.py
Labels: 00 - Ready for Review

#252 [RAPTOR-3982] fix perf-test for multiclass
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/utils.py
  tests/drum/test_performance_check.py
Labels: 00 - Ready for Review

#254 [RAPTOR-4164] fix binary num class order
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/utils.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/test_utils.py
Labels: Needs Review: Custom Models, Ready for Review

#255 [RAPTOR-4199] force class labels to be strings
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/artifact_predictor.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  requirements.txt
  tests/drum/test_args_parser.py
Labels: 00 - Ready for Review

#253 [RAPTOR-3552] Align parameter names in model templates with docs
  custom_model_runner/datarobot_drum/resource/templates/custom_python_template.py.j2
  custom_model_runner/datarobot_drum/resource/templates/custom_r_template.R.j2
Labels: 00 - Ready for Review

#256 [RAPTOR-3916] make drum require Python >=3.4,<=3.8
  custom_model_runner/setup.py
Labels: 00 - Ready for Review

#260 [RAPTOR-4239] fix class labels in readmes
  model_templates/inference/h2o_mojo/README.md
  model_templates/inference/h2o_mojo_pipeline/README.md
  model_templates/inference/h2o_pojo/README.md
Labels: 00 - Ready for Review

#263 [RAPTOR-4161] fix drum push for multiclass
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#258 [RAPTOR-4203] Make Arrow logic optional, release v1.4.9
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_inference.py
  tests/fixtures/drop_in_model_artifacts/r_reg_sparse.rds
Labels: 00 - Ready for Review
