Repository datarobot/datarobot-user-models, pull requests merged in 2020-11, with the labels that each got.

#197 Add functional test for unstructured model
  tests/functional/conftest.py
  tests/functional/test_inference_model_templates.py
Labels: 00 - Ready for Review

#202 [RAPTOR-3889] Set flask server root logger level to the level provided by the user
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
Labels: 00 - Ask for Review on Green, 00 - Ready for Review

#201 [RAPTOR-3887] Fix Target Labels DAI Mojo Pipeline
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/custom/H2OPredictorPipeline.scala
Labels: 00 - Ready for Review

#203 [RAPTOR-3890] merge java codegen and h2o envs
  model_templates/inference/h2o_mojo/README.md
  model_templates/inference/h2o_mojo_pipeline/README.md
  model_templates/inference/h2o_pojo/README.md
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_h2o/Dockerfile
  public_dropin_environments/java_h2o/README.md
  public_dropin_environments/java_h2o/dr_requirements.txt
  public_dropin_environments/java_h2o/env_info.json
  public_dropin_environments/java_h2o/start_server.sh
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
  tests/functional/conftest.py
  tests/functional/test_drop_in_environments.py
  tests/functional/test_inference_model_templates.py
Labels: 00 - Ready for Review

#191 [RAPTOR-3768] improving drum perf-test mode
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/exceptions.py
  custom_model_runner/datarobot_drum/drum/memory_monitor.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/push.py
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/test_performance_check.py
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
Labels: 00 - Ready for Review

#200 [RAPTOR-3842] fix for pickling with joblib creates issue with TF2 upgrading
  README.md
  custom_model_runner/datarobot_drum/drum/artifact_predictors/keras_predictor.py
  custom_model_runner/datarobot_drum/drum/description.py
  model_templates/inference/python3_keras_vizai_joblib/artifact.joblib
  model_templates/inference/python3_keras_vizai_joblib/model_utils.py
  model_templates/training/python3_keras_vizai_joblib/model_utils.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#207 [RAPTOR-3813] test for unsupervised drum push
  custom_model_runner/datarobot_drum/drum/push.py
  jenkins/test3_drop_in_envs.sh
  tests/functional/test_drum_push.py
Labels: Ready for Review

#199 [RAPTOR-3866] Catch exception from user's code, log it and return proper response
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Custom Models, Ready for Review

#205 [RAPTOR-3839] Add support for a single uwsgi process in production mode
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
Labels: 00 - Ask for Review on Green, 00 - Ready for Review

#206 [RAPTOR-3899] add anomaly inference template
  README.md
  model_templates/inference/python3_sklearn_anomaly/README.md
  model_templates/inference/python3_sklearn_anomaly/anomaly_helpers.py
  model_templates/inference/python3_sklearn_anomaly/build_pipeline.py
  model_templates/inference/python3_sklearn_anomaly/sklearn_anomaly.pkl
Labels: Ready for Review

#212 [RAPTOR-3925] fix class label issues for numerical labels
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/artifact_predictors/sklearn_predictor.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_other_cases.py
  tests/testdata/skyserver_sql2_27_2018_6_51_39_pm_num_class.csv
Labels: 00 - Ready for Review, Needs Review: Custom Models

#211 [RAPTOR-3620] Add capabilities endpoint + arrow support
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/requirements.txt
  tests/drum/test_inference.py
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
Labels: Ready for Review

#213 remove flatten from pytorch template
  model_templates/training/python3_pytorch/model_utils.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/functional/test_training_model_templates.py
Labels: Ready for Review

#214 R boolean target
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/testdata/10k_diabetes_sample.csv
Labels: Ready for Review

#215 [RAPTOR-3584] drum: adding max used memory when running in container
  custom_model_runner/datarobot_drum/drum/memory_monitor.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
Labels: Ready for Review

#216 [RAPTOR-3936] add locust testing framework
  tests/locust/README.md
  tests/locust/empty_unstructured_model/custom.py
  tests/locust/scripts/start-locust-docker.sh
  tests/locust/suits/predict.py
  tests/locust/suits/predict_unstructured.py
Labels: 00 - Ready for Review, Auto Merge on Green

#218 [RAPTOR-3980] --class-labels-file should work in docker mode
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  model_templates/training/python3_sklearn_multiclass/custom.py
  tests/drum/test_inference.py
  tests/drum/utils.py
Labels: Auto Merge on Green

#217 release v1.4.2
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  jenkins/test3_drop_in_envs.sh
  model_templates/inference/r_unstructured/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/test_inference.py
  tests/functional/test_inference_model_templates.py
Labels: 00 - Ready for Review, Auto Merge on Green

#221 Uncomment test_drum_push
  jenkins/test3_drop_in_envs.sh
  tests/fixtures/user_permissions.json
Labels: 00 - Ready for Review, Auto Merge on Green

#223 [RAPTOR-3777] 10K diabetes file with windows line terminators breaks.
  QUICKSTART-FOR-TRAINING.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/conftest.py
  tests/drum/test_drum_server_failures.py
  tests/drum/test_fit_variety.py
  tests/testdata/10k_diabeetus_windows.csv
  tests/testdata/telecomms_churn.csv
  tests/testdata/variety_samples/variety_data_key.json
  tests/testdata/variety_samples/variety_data_key.yaml
Labels: Ready for Review

#229 release v1.4.3
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  jenkins/test3_drop_in_envs.sh
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/functional/test_inference_model_templates.py
Labels: 00 - Ready for Review

#224 [RAPTOR-3977] Let drum run transformations without downstream model
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  model_templates/training/python3_sklearn_transform/README.md
  model_templates/training/python3_sklearn_transform/create_transform_pipeline.py
  model_templates/training/python3_sklearn_transform/custom.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
Labels: Ready for Review
