Repository datarobot/datarobot-user-models, pull requests merged in 2021-11, with the labels that each got.

#470 Propagate sparse colnames for R transforms [RAPTOR-6209]
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_inference.py
  tests/fixtures/drop_in_model_artifacts/r_sparse_transform.rds
  tests/fixtures/r_transform_custom_sparse_output.R
  tests/fixtures/transform_custom_no_y.py
Labels: 00 - Ready for Review

#474 [RAPTOR-7046] Update JDK 11 version in requirements_dev.txt in DRUM repo
  requirements_dev.txt
Labels: 00 - Ready for Review

#476 [RAPTOR-6794] add some more messages for users
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/drum/test_fit.py
Labels: Ready for Review

#473 Fix class labels [RAPTOR-6493]
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
Labels: 00 - Ready for Review

#480 [RAPTOR-6106] Fast follow
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  tests/drum/test_data_marshalling.py
Labels: 00 - Ready for Review, Auto Merge on Green

#481 [RAPTOR-5500] New release 1.6.2
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Custom Models, 00 - Ready for Review

#484 [RAPTOR-5500] Update new release version number
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
Labels: 00 - Ready for Review

#487 [RAPTOR-7113] Update version of pip used in functional tests
  jenkins/test3_drop_in_envs.sh
  jenkins/test3_inference_model_templates.sh
  jenkins/test3_training_model_templates.sh
  tests/functional/test_custom_task_templates.py
  tests/functional/test_drum_push.py
Labels: 00 - Ready for Review, Priority: Blocker

#491 RAPTOR-7061 Do not block python thread while trying to read stdout from DRUM server
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/perf_testing.py
Labels: 00 - Ready for Review

#488 Consider CAT & TXT features as equivalent for data validation
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/test_typeschema_validation.py
Labels: 00 - Ready for Review

#492 [RAPTOR-7174] sparse output should be allowed with IDENTITY
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/test_typeschema_validation.py
Labels: Ready for Review, Close Jira on Merge

#493 [RAPTOR-7149] Improve the logic to handle class_labels
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  tests/conftest.py
  tests/drum/test_language_predictor.py
Labels: 00 - Ready for Review

#494 [RAPTOR-7124] Add new release 1.6.3
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#495 Call transform hook before fit [RAPTOR-6103]
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  custom_model_runner/datarobot_drum/resource/pipelines/python_fit.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/r_fit.json.j2
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/fixtures/custom_pred_consistency/custom.py
  tests/fixtures/python_xform_estimator/custom.py
  tests/fixtures/r_xform_estimator/custom.R
Labels: 00 - Ready for Review

#496 [RAPTOR-5478]update task routes
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_units.py
Labels: Ready for Review

#482 Fix numeric class labels for R tasks [RAPTOR-6493]
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_other_cases.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#486 Fix check for binary target labels [RAPTOR-6424]
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_units.py
  tests/fixtures/r_binary_classifier/custom.R
  tests/testdata/int_target.csv
Labels: 00 - Ready for Review

#498 [RAPTOR-7204] Run java predictor related tests sequentially
  pyproject.toml
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_inference.py
Labels: Ready for Review

#501 [YOLO] update readmes
  task_templates/1_transforms/2_r_transform_simple/README.md
  task_templates/1_transforms/3_python3_sklearn_transform/README.md
  task_templates/1_transforms/4_r_transform_recipe/README.md
  task_templates/1_transforms/6_python3_image_transform/README.md
  task_templates/3_pipelines/11_python3_pytorch_regression/README.md
  task_templates/3_pipelines/12_python3_pytorch/README.md
  task_templates/3_pipelines/13_python3_pytorch_multiclass/README.md
  task_templates/3_pipelines/14_python3_keras_joblib/README.md
  task_templates/3_pipelines/15_python3_keras_vizai_joblib/README.md
  task_templates/3_pipelines/2_python3_sklearn_regression/README.md
  task_templates/3_pipelines/3_r_lang/README.md
  task_templates/3_pipelines/4_python3_xgboost/README.md
  task_templates/3_pipelines/5_python3_sklearn_binary/README.md
  task_templates/3_pipelines/6_python3_sklearn_multiclass/README.md
  task_templates/3_pipelines/7_python3_anomaly_detection/README.md
  task_templates/3_pipelines/8_python3_calibrated_anomaly_detection/README.md
Labels: Ready for Review, Auto Merge on Green, Close Jira on Merge
