Repository datarobot/datarobot-user-models, pull requests merged in 2021-04, with the labels that each got.

#309 [RAPTOR-5806] Update user blueprint add to menu route
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_units.py
  tests/functional/test_training_model_templates.py
Labels: 00 - Ready for Review

#308 [RAPTOR-5017,5019] fix documentation on the API endpoints, release v1.5.3
  README.md
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/drum_server_api.yaml
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#311 [RAPTOR-5017,5019] fix links in docs
  README.md
  custom_model_runner/README.md
Labels: 00 - Ready for Review

#312 [RAPTOR-4570] Handle boolean in examples
  model_templates/training/python3_anomaly_detection/build_pipeline.py
  model_templates/training/python3_calibrated_anomaly_detection/build_pipeline.py
  model_templates/training/python3_pytorch_multiclass/preprocessing.py
  model_templates/training/python3_sklearn_binary/create_pipeline.py
  model_templates/training/python3_sklearn_multiclass/create_pipeline.py
  model_templates/training/python3_sklearn_regression/create_pipeline.py
Labels: Auto Merge on Green, Ready for Review

#313 [RAPTOR-4944] Training model and transform parameter support
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/push.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
  custom_model_runner/datarobot_drum/resource/pipelines/python_fit.json.j2
  model_templates/training/python3_sklearn_binary_hyperparameters/create_pipeline.py
  model_templates/training/python3_sklearn_binary_hyperparameters/custom.py
  model_templates/training/python3_sklearn_binary_hyperparameters/model-metadata.yaml
  model_templates/training/python3_sklearn_transform_hyperparameters/README.md
  model_templates/training/python3_sklearn_transform_hyperparameters/create_transform_pipeline.py
  model_templates/training/python3_sklearn_transform_hyperparameters/custom.py
  model_templates/training/python3_sklearn_transform_hyperparameters/model-metadata.yaml
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/testdata/sklearn_binary_parameters.json
  tests/testdata/sklearn_transform_parameters.json
Labels: 00 - Ready for Review

#314 [RAPTOR-4944] Update Drum for python parameter input support, add R support
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  custom_model_runner/datarobot_drum/resource/pipelines/r_fit.json.j2
  model_templates/training/r_lang_hyperparameters/README.md
  model_templates/training/r_lang_hyperparameters/create_pipeline.R
  model_templates/training/r_lang_hyperparameters/custom.R
  model_templates/training/r_lang_hyperparameters/model-metadata.yaml
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/fit.sh
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/fit.sh
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/fit.sh
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/fit.sh
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/fit.sh
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/testdata/r_parameters.json
Labels: 00 - Ready for Review

#315 [YOLO] pin DR client version to 2.24.0
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  requirements_test.txt
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
Labels: 00 - Ready for Review

#316 [RAPTOR-5197] update DRUM test container, add support for Julia
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  docker/drum_integration_tests_base/Dockerfile
  docker/drum_integration_tests_base/build_test_docker.sh
  docker/drum_integration_tests_base/sysim.jl
  requirements.txt
  tests/fixtures/custom_pred_consistency/custom.py
Labels: 00 - Ready for Review

#319 [RAPTOR-5197] update DRUM test container, add support for Julia - drop 2
  docker/drum_integration_tests_base/Dockerfile
  tests/drum/test_performance_check.py
Labels: 00 - Ready for Review

#321 [RAPTOR-5021] Show predict logs during drum fit when verbose is set to true
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
Labels: 00 - Ready for Review

#324 [YOLO] fix unstructured mode docs
  README.md
Labels: 00 - Ready for Review, Auto Merge on Green, Needs Review: Custom Models

#323 [YOLO] Bump version to 1.5.5
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#322 [RAPTOR-5193] Validation system for type schema
  MODEL-METADATA.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  custom_model_runner/requirements.txt
  tests/drum/test_units.py
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
Labels: Auto Merge on Green, Ready for Review
