Repository datarobot/datarobot-user-models, pull requests merged in 2021-12, with the labels that each got.

#502 [RAPTOR-7217] handle pyarrow version check in transforming
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  custom_model_runner/requirements.txt
  tests/drum/test_inference.py
Labels: 00 - Ready for Review

#503 [RAPTOR-7224] refactor subprocess.Popen() to call command without shell
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/resource/utils.py
  tests/drum/test_args_parser.py
  tests/drum/test_performance_check.py
Labels: 00 - Ready for Review

#497 [RAPTOR-7213] Read form data for unstructured models.
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/drum/test_unstructured_mode.py
Labels: 00 - Ready for Review

#504 [RAPTOR-7318] Release v1.6.4
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Close Jira on Merge

#507 [RAPTOR-7348] wrap main func with if __name__ == __main__
  custom_model_runner/bin/drum
Labels: 00 - Ready for Review

#512 Release 1.6.5
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#514 Release v1.6.2-post1
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  jenkins/test3_drop_in_envs.sh
  jenkins/test3_inference_model_templates.sh
  jenkins/test3_training_model_templates.sh
Labels: 00 - Ready for Review

#516 Update envs with DRUM v1.6.2.post1
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#520 Release v1.6.2.post2
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  tests/functional/test_custom_task_templates.py
  tests/functional/test_drum_push.py
Labels: 00 - Ready for Review

#521 Update envs with DRUM v1.6.2.post2
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Custom Models, 00 - Ready for Review

#524 [RAPTOR-7447] create drum build container with root user
  docker/drum_builder/build_docker.sh
Labels: 00 - Ready for Review, Close Jira on Merge

#526 [MODEL-7540] Update cmrunner dr client
  custom_model_runner/requirements.txt
Labels: Auto Merge on Green

#525 Release v1.6.6
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#506 [RAPTOR-7292] Add validation on custom task hyperparameters
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/model_metadata.py
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_other_cases.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#522 [RAPTOR-7419] Split drum java predictor into 3 jars
  custom_model_runner/Makefile
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/base_predictor/Makefile
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/base_predictor/README.md
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/base_predictor/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/base_predictor/src/main/java/com/datarobot/drum/BasePredictor.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/Makefile
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/src/main/java/com/datarobot/drum/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/src/main/scala/com/datarobot/drum/H2OPredictor.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/src/main/scala/com/datarobot/drum/H2OPredictorPipeline.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/py4j_entrypoint/Makefile
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/py4j_entrypoint/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/py4j_entrypoint/src/main/java/com/datarobot/drum/PredictorEntryPoint.java
  model_templates/java_unstructured/pom.xml
  tests/drum/custom_java_predictor/pom.xml
  tools/image-build-utils.sh
Labels: 00 - Ready for Review

#528 [RAPTOR-7458] don't install drum-base-predictor locally for test/build purposes
  custom_model_runner/Makefile
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/base_predictor/pom.xml
  tests/drum/custom_java_predictor/pom.xml
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#530 [MODEL-7527] refactor y fixture names
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_inference.py
  tests/fixtures/r_transform_custom.R
  tests/fixtures/r_transform_custom_with_y.R
  tests/fixtures/transform_custom.py
  tests/fixtures/transform_custom_with_y.py
  tests/fixtures/transform_fit_custom.py
  tests/fixtures/transform_fit_custom_with_y.py
Labels: Ready for Review
