Repository datarobot/datarobot-user-models, pull requests merged in 2021-05, with the labels that each got.

#325 [RAPTOR-5194 RAPTOR-5195]fit time validation
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/exceptions.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  custom_model_runner/datarobot_drum/resource/utils.py
  model_templates/training/python3_sklearn_binary_schema_validation/README.md
  model_templates/training/python3_sklearn_binary_schema_validation/create_pipeline.py
  model_templates/training/python3_sklearn_binary_schema_validation/custom.py
  model_templates/training/python3_sklearn_binary_schema_validation/model-metadata.yaml
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
Labels: 00 - Ready for Review, Auto Merge on Green

#327 [RAPTOR-5302] contains missing validation
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review, Auto Merge on Green

#328 [YOLO] code clean up and optimization
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  model_templates/training/python3_pytorch_multiclass/custom.py
  model_templates/training/python3_xgboost/custom.py
  tests/drum/test_drum_server_failures.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#329 [RAPTOR-5317] update h2o dependencies in pom
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
Labels: Ready for Review

#318 [RAPTOR-5203] Add support for Julia Inference Models
  README.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/Manifest.toml
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/Project.toml
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/__init__.py
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/julia_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/mlj_libs.jl
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/score.jl
  custom_model_runner/datarobot_drum/drum/templates_generator.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/templates/custom_julia_template.jl.j2
  custom_model_runner/datarobot_drum/resource/utils.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  model_templates/inference/julia/README.md
  model_templates/inference/julia/jl_boston/boston_rf.jlso
  model_templates/inference/julia/jl_boston/custom.jl
  model_templates/inference/julia/jl_custom/README.md
  model_templates/inference/julia/jl_custom/custom.jl
  model_templates/inference/julia/jl_custom/mymodel.bson
  model_templates/inference/julia/jl_galaxy/custom.jl
  model_templates/inference/julia/jl_galaxy/galaxy.jlso
  model_templates/inference/julia/jl_iris_binary/custom.jl
  model_templates/inference/julia/jl_iris_binary/iris-binary.jlso
  model_templates/inference/julia/jl_unstructured/README.md
  model_templates/inference/julia/jl_unstructured/custom.jl
  public_dropin_environments/julia_mlj/Dockerfile
  public_dropin_environments/julia_mlj/Manifest.toml
  public_dropin_environments/julia_mlj/Project.toml
  public_dropin_environments/julia_mlj/README.md
  public_dropin_environments/julia_mlj/__init__.py
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/julia_mlj/fit.sh
  public_dropin_environments/julia_mlj/requirements.txt
  public_dropin_environments/julia_mlj/start_server.sh
  public_dropin_environments/julia_mlj/sysim.jl
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_inference.py
  tests/fixtures/custom.jl
  tests/fixtures/drop_in_model_artifacts/boston_rf.jlso
  tests/fixtures/drop_in_model_artifacts/galaxy.jlso
  tests/fixtures/drop_in_model_artifacts/iris_binary.jlso
Labels: 00 - Ready for Review

#330 [RAPTOR-2656] Clean up and refactor validation testing
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/custom_java_predictor/pom.xml
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_validation_check.py
  tests/fixtures/fail_classification_validation_custom.R
Labels: 00 - Ready for Review, Needs Review: Custom Models

#326 [RAPTOR-5277,5301] validate classification predictions add up to one for all the predictors
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  tests/drum/test_inference.py
  tests/drum/test_units.py
  tests/drum/test_validation_check.py
Labels: 00 - Ready for Review

#335 [YOLO] fix raise_multiple_custom_files function - add arg for jl paths
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: 00 - Ready for Review

#333 [YOLO] refactorings
  README.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#336 [RAPTOR-5377] fix custom R detection
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: 00 - Ready for Review

#331 [RAPTOR-5286] Add detailed docs for validations schema
  VALIDATION-SCHEMA.md
Labels: 00 - Ready for Review, Auto Merge on Green

#337 [RAPTOR-5369] improve error output
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/PredictorEntryPoint.java
  public_dropin_environments/java_codegen/env_info.json
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#338 [RAPTOR-5369] Install DRUM 1.5.6.post1 into java env
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
Labels: 00 - Ready for Review

#339 [RAPTOR-5407] fix documentation to reflect all supported types.
  MODEL-METADATA.md
  custom_model_runner/datarobot_drum/drum/common.py
Labels: Ready for Review

#340 [YOLO] output total run time number per test case
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/profiler/stats_collector.py
Labels: 00 - Ready for Review

#348 [YOLO] pin pandas version
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/julia_mlj/dr_requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green

#350 [EP-714] disable inference vizai test to support k3d
  tests/functional/test_inference_model_templates.py
Labels: 00 - Ready for Review, Auto Merge on Green

#341 [Yolo] bug fix in score.jl
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/score.jl
Labels: 00 - Ask for Review on Green, 00 - Ready for Review
