Repository datarobot/datarobot-user-models, pull requests merged in 2021-03, with the labels that each got.

#295 [RAPTOR-4830] refactor data transfer from py to java via py4j
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/BasePredictor.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictor.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictorPipeline.scala
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#297 pin black
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/push.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  custom_model_runner/datarobot_drum/resource/utils.py
  model_templates/training/python3_anomaly_detection/custom.py
  model_templates/training/python3_calibrated_anomaly_detection/custom.py
  model_templates/training/python3_sklearn_transform/custom.py
  requirements_dev.txt
  requirements_lint.txt
  tests/conftest.py
  tests/drum/test_deployment_config.py
  tests/drum/test_drum_docker.py
  tests/drum/test_drum_server_failures.py
  tests/drum/test_fit.py
  tests/drum/test_fit_variety.py
  tests/drum/test_inference.py
  tests/drum/test_mlops_monitoring.py
  tests/drum/test_other_cases.py
  tests/drum/test_performance_check.py
  tests/drum/test_units.py
  tests/drum/test_unstructured_mode.py
  tests/drum/test_validation_check.py
  tests/fixtures/transform_fit_custom.py
  tests/fixtures/transform_fit_custom_no_hook.py
  tests/fixtures/transform_fit_custom_no_y.py
  tests/fixtures/transform_fit_custom_non_numeric.py
  tests/fixtures/transform_fit_custom_sparse_in_out.py
  tests/fixtures/transform_fit_custom_sparse_input.py
  tests/functional/test_drop_in_environments.py
  tests/functional/test_drum_push.py
  tests/functional/test_training_model_templates.py
  tools/parallel_requests.py
Labels: Auto Merge on Green

#296 [RAPTOR-4880] Sparse columns support
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/push.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
  custom_model_runner/datarobot_drum/resource/pipelines/python_fit.json.j2
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  public_dropin_environments/python3_keras/fit.sh
  public_dropin_environments/python3_pytorch/fit.sh
  public_dropin_environments/python3_sklearn/fit.sh
  public_dropin_environments/python3_xgboost/fit.sh
  public_dropin_environments/r_lang/fit.sh
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_inference.py
  tests/fixtures/validate_sparse_columns/README.md
  tests/fixtures/validate_sparse_columns/custom.py
  tests/fixtures/validate_sparse_columns/model-metadata.yaml
  tests/testdata/sparse.columns
Labels: 00 - Ready for Review

#298 [RAPTOR-4967] Add parameters to DRUM metadata schema
  custom_model_runner/datarobot_drum/drum/common.py
Labels: Auto Merge on Green

#302 Release 1.5.2
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#303 [RAPTOR-4897] make targetName field in model config optional
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#301 [RAPTOR-4975] add validation parameter to mode-metadata.yaml
  custom_model_runner/datarobot_drum/drum/common.py
Labels: Ready for Review

#306 Downgrade pandas version to workaround pandas to_json() memory leak - drop 2
  requirements.txt
  tests/fixtures/cmrun_docker_env/requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green

#307 [RAPTOR-4478] cleanup BasePredictor: add abstract configure() method
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/BasePredictor.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/drum/ScoringCode.java
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictor.scala
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/scala/com/datarobot/drum/H2OPredictorPipeline.scala
  tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java
Labels: 00 - Ready for Review

#304 [RAPTOR-4897] early detection of missing labels for binary/multiclass
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_inference.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review
