Repository datarobot/datarobot-user-models, pull requests merged in 2021-09, with the labels that each got.

#416 [RAPTOR-5841][RAPTOR-5842][RAPTOR-6190][RAPTOR-6230] R: Fix sparse data support, fix sampling issue
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  custom_model_runner/datarobot_drum/resource/pipelines/r_fit.json.j2
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  task_templates/estimators/r_sparse_regression/custom.R
  task_templates/estimators/r_sparse_regression/model-metadata.yaml
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_inference.py
  tests/fixtures/drop_in_model_artifacts/r_reg_sparse.rds
  tests/fixtures/r_validate_sparse_estimator.R
Labels: Ready for Review

#398 [RAPTOR-5931] R transform template
  README.md
  task_templates/transforms/python3_sklearn_transform/custom.py
  task_templates/transforms/r_transform_recipe/README.md
  task_templates/transforms/r_transform_recipe/custom.R
  task_templates/transforms/r_transform_recipe/model-metadata.yaml
  task_templates/transforms/r_transform_simple/README.md
  task_templates/transforms/r_transform_simple/custom.R
  task_templates/transforms/r_transform_simple/model-metadata.yaml
  tests/functional/test_custom_task_templates.py
Labels: 00 - Ready for Review

#421 [RAPTOR-6306] R Sparse Transforms: fix off-by-one error
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  tests/fixtures/r_transform_fit_custom_non_numeric.R
Labels: 00 - Ready for Review

#426 [YOLO] output string instead of bytes in img template
  task_templates/transforms/python3_image_transform/README.md
  task_templates/transforms/python3_image_transform/img_utils.py
Labels: Ready for Review, Auto Merge on Green

#424 [RAPTOR-5872]update messages for users
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
Labels: Ready for Review

#427 Release DRUM v1.5.13
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#429 [RAPTOR-6399] fix the order of class labels reported to MLOps monitoring
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
Labels: 00 - Ready for Review, Auto Merge on Green

#412 [RAPTOR-6119] disallow Y transform
  custom_model_runner/datarobot_drum/drum/exceptions.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_inference.py
  tests/fixtures/r_transform_fit_custom_sparse_input_y_output.R
  tests/fixtures/transform_fit_custom_sparse_input_y_output.py
  tests/functional/test_drum_push.py
Labels: Ready for Review

#432 [YOLO] publish new drum version
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#428 [RAPTOR-6377] refactor stats reporting
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/resource_monitor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/drum_server_api.yaml
  tests/drum/test_stats.py
Labels: 00 - Ready for Review, Auto Merge on Green

#435 Duncan/raptor 5561/refine readme drum stage1
  README.md
Labels: 00 - Ready for Review

#434 Release v1.5.15
  custom_model_runner/CHANGELOG.md
  jenkins/update_drum_in_dockerfile.sh
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/run-drum-tests-in-container.sh
  tools/image-build-utils.sh
Labels: 00 - Ready for Review

#436 [RAPTOR-6477] make uwsgi an extra dependency for DRUM
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/setup.py
  docker/drum_integration_tests_base/Dockerfile
  model_templates/java_codegen/README.md
  model_templates/python3_keras/README.md
  model_templates/python3_keras_joblib/README.md
  model_templates/python3_pmml/README.md
  model_templates/python3_pytorch/README.md
  model_templates/python3_pytorch_multiclass/README.md
  model_templates/python3_sklearn/README.md
  model_templates/python3_sklearn_anomaly/README.md
  model_templates/python3_unstructured/README.md
  model_templates/python3_xgboost/README.md
  model_templates/r_lang/README.md
  model_templates/r_unstructured/README.md
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
  tests/fixtures/cmrun_docker_env/requirements.txt
Labels: 00 - Ready for Review

#437 [RAPTOR-6465] Update default schema to forbid missing and sparse
  custom_model_runner/datarobot_drum/resource/default_typeschema/model-metadata.yaml
  tests/drum/test_fit.py
  tests/drum/unit/test_typeschema_validation.py
Labels: Ready for Review

#438 [RAPTOR-6439] handle defining bool args param through env var
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/requirements.txt
  tests/drum/test_args_parser.py
Labels: 00 - Ready for Review

#440 [YOLO] release 1.5.16
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Auto Merge on Green
