Repository datarobot/datarobot-user-models, pull requests merged in 2021-07, with the labels that each got.

#372 [RAPTOR-5491] fix datatypes in
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/test_typeschema_validation.py
Labels: Auto Merge on Green, Close Jira on Merge, Ready for Review

#374 [RAPTOR-5760] do not use deprecated custom model images in tests
  custom_model_tutorial.ipynb
  tests/functional/test_drop_in_environments.py
Labels: 00 - Ready for Review

#375 [RAPTOR-5493] Validate output data for transforms in predict server
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/julia_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_units.py
  tests/fixtures/validate_transform_fail_output_schema_validation/README.md
  tests/fixtures/validate_transform_fail_output_schema_validation/custom.py
  tests/fixtures/validate_transform_fail_output_schema_validation/model-metadata.yaml
Labels: 00 - Ready for Review

#378 [RAPTOR-5369] improve py4j gateway connection errors handling, release v1.5.8
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#377 [RAPTOR-5792] Check R colname validation as both literals and doubles
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_other_cases.py
  tests/fixtures/int_colnames_binary.R
  tests/fixtures/int_colnames_multiclass.R
Labels: 00 - Ready for Review

#381 Release v1.5.9
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#379 [RAPTOR-5424] Cleaning some stuff up, improving readme
  task_templates/README.md
  task_templates/estimators/python_classification_simple/custom.py
  task_templates/pipelines/python3_keras_joblib/README.md
  task_templates/pipelines/python3_pytorch/README.md
  task_templates/pipelines/python3_sklearn_binary/README.md
  task_templates/pipelines/python3_sklearn_binary_schema_validation/README.md
  task_templates/pipelines/python3_sklearn_multiclass/README.md
  task_templates/pipelines/python3_sklearn_regression/README.md
  task_templates/pipelines/python3_sklearn_regression/create_pipeline.py
Labels: Ready for Review

#373 [RAPTOR-5540] support all datatypes
  MODEL-METADATA.md
  VALIDATION-SCHEMA.md
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/test_typeschema_validation.py
Labels: Auto Merge on Green

#383 [BUILD-2410] Fix pandas version constraints
  custom_model_runner/requirements.txt
Labels: Ready for Review

#382 [RAPTOR-5486] Support for R transforms
  custom_model_runner/datarobot_drum/drum/language_predictors/r_common_code/common.R
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/resource/components/Python/python_fit/python_fit.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  public_dropin_environments/python3_sklearn/sklearn.tar.gz
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/drum/test_inference.py
  tests/fixtures/drop_in_model_artifacts/r_transform.rds
  tests/fixtures/r_transform_custom.R
  tests/fixtures/r_transform_custom_no_y.R
  tests/fixtures/r_transform_fit_custom_no_hook.R
  tests/fixtures/r_transform_fit_custom_non_numeric.R
  tests/fixtures/r_transform_fit_custom_sparse_in_out.R
  tests/fixtures/r_transform_fit_custom_sparse_input.R
Labels: Ready for Review

#384 [RAPTOR-5867] Update StrictYaml
  custom_model_runner/requirements.txt
  jenkins/update_drum_in_dockerfile.sh
  requirements.txt
  tests/fixtures/cmrun_docker_env/drum_requirements.txt
Labels: 00 - Ready for Review

#385 [RAPTOR-5868][RAPTOR-5911] Transforms: Use default type schema when not provided && Fix strict validation flag
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  custom_model_runner/datarobot_drum/resource/default_typeschema/__init__.py
  custom_model_runner/datarobot_drum/resource/default_typeschema/model-metadata.yaml
  custom_model_runner/setup.py
  tests/drum/test_args_parser.py
  tests/drum/test_fit.py
  tests/drum/unit/test_typeschema_validation.py
Labels: 00 - Ready for Review

#386 [RAPTOR-5924] Add script to test images in DR, refactor of jenkins shellscripts
  README.md
  docker/drum_builder/build_docker.sh
  jenkins/test3_drop_in_envs.sh
  jenkins/test3_inference_model_templates.sh
  jenkins/test3_training_model_templates.sh
  tools/create-drum-dev-image.sh
  tools/image-build-utils.sh
Labels: Ready for Review

#387 [RAPTOR-5867] Release drum 1.5.10
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#388 [RAPTOR-5789] Add server memory usage
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: 00 - Ready for Review
