Repository datarobot/datarobot-user-models, pull requests merged in 2021-08, with the labels that each got.

#394 [YOLO] Move hyperparameter templates to test fixtures directory
  tests/conftest.py
  tests/fixtures/python3_sklearn_binary_hyperparameters/create_pipeline.py
  tests/fixtures/python3_sklearn_binary_hyperparameters/custom.py
  tests/fixtures/python3_sklearn_binary_hyperparameters/model-metadata.yaml
  tests/fixtures/python3_sklearn_transform_hyperparameters/README.md
  tests/fixtures/python3_sklearn_transform_hyperparameters/create_transform_pipeline.py
  tests/fixtures/python3_sklearn_transform_hyperparameters/custom.py
  tests/fixtures/python3_sklearn_transform_hyperparameters/model-metadata.yaml
  tests/fixtures/r_lang_hyperparameters/README.md
  tests/fixtures/r_lang_hyperparameters/create_pipeline.R
  tests/fixtures/r_lang_hyperparameters/custom.R
  tests/fixtures/r_lang_hyperparameters/model-metadata.yaml
Labels: Ready for Review

#397 [RAPTOR-5866] update docs for schema validation
  MODEL-METADATA.md
  VALIDATION-SCHEMA.md
Labels: Ready for Review

#403 [YOLO] remove unnecessary ls in dockerfile
  tests/fixtures/cmrun_docker_env/Dockerfile
Labels: Auto Merge on Green

#395 [RAPTOR-6035]Perform schema checks for transform output
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  tests/drum/test_fit.py
  tests/drum/unit/test_typeschema_validation.py
  tests/fixtures/r_transform_fit_custom_non_numeric.R
Labels: Ready for Review, Auto Merge on Green

#391 [RAPTOR-5739] Applying Jesse's technique to python
  .ignore
  custom_model_runner/datarobot_drum/drum/artifact_predictors/sklearn_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/utils.py
  pyproject.toml
  tests/drum/test_data_marshalling.py
  tests/drum/test_other_cases.py
  tests/drum/test_units.py
Labels: Ready for Review, Auto Merge on Green

#407 [YOLO] update wording from models to tasks
  VALIDATION-SCHEMA.md
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
Labels: Ready for Review

#406 [RAPTOR-6035] Release DRUM v1.5.11
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  task_templates/pipelines/python3_keras_joblib/model-metadata.yaml
Labels: Ready for Review, Auto Merge on Green

#401 [RAPTOR-6038] Removing custom tasks docs in DRUM repo
  QUICKSTART-FOR-TASKS.md
  README.md
Labels: 00 - Ready for Review

#409 [RAPTOR-6115] add BRANCHING.yaml to run the installer build job for release
  BRANCHING.yaml
Labels: 00 - Ready for Review

#413 [YOLO] Remove accidentally commited tar.gz
  public_dropin_environments/python3_sklearn/sklearn.tar.gz
Labels: 00 - Ready for Review

#380 [RAPTOR-5781] update generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
Labels: Ready for Review

#414 RAPTOR-6038 removing dead hyperlink from top level readme
  README.md
Labels: 00 - Ready for Review, Auto Merge when Ready
