Repository datarobot/datarobot-user-models, pull requests merged in 2021-06, with the labels that each got.

#357 [RAPTOR-5568] Show R Traceback for fit/predict errors
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/r_fit.py
  tests/drum/test_utils.py
Labels: 00 - Ready for Review

#347 [RAPTOR-5435] add dependbot configuration
  dependbot.yml
Labels: Ready for Review

#359 [YOLO] define JAVA_PATH env var in the java base image
  docker/java_dropin_env_base/Dockerfile
Labels: 00 - Ready for Review

#364 [YOLO] moved tests
  tests/drum/unit/__init__.py
  tests/drum/unit/test_typeschema_validation.py
  tests/drum/utils.py
Labels: Ready for Review

#360 [RAPTOR-5590] Load custom.r if custom.R fails
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_other_cases.py
  tests/fixtures/all_predict_structured_hooks_custom_lowercase_r.r
  tests/fixtures/all_predict_unstructured_hooks_custom_lowercase_r.r
Labels: 00 - Ready for Review

#365 [YOLO] Try xdist out for test performance
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  requirements_test.txt
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_drum_server_failures.py
  tests/drum/test_units.py
  tests/drum/unit/test_typeschema_validation.py
Labels: 00 - Ready for Review

#367 [RAPTOR-5588] Fix R fit bug when handling single-col data
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/testdata/regression_single_col.csv
Labels: Auto Merge on Green, Close Jira on Merge

#369 [RAPTOR-5648] Add quotes around all docker mount paths
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: Auto Merge on Green

#370 [YOLO] Bump to version 1.5.7
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#371 [YOLO] Update description for new version
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Auto Merge on Green

#362 [RAPTOR-5492]deal with ugly list representation in f-string
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/test_typeschema_validation.py
Labels: Ready for Review
