Repository datarobot/datarobot-user-models, pull requests merged in 2021-02, with the labels that each got.

#283 [RAPTOR-4563] Bump up default DRUM perf test timeout to 600s
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review

#284 [RAPTOR-4593] refactor YAML schema for model-metadata.yaml
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/push.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#285 [RAPTOR-4601] update environment for pytorch
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Custom Models, Ready for Review

#286 [RAPTOR-4634] implement DR predictions response, release 1.4.14
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/constants.py
  tests/drum/test_deployment_config.py
  tests/testdata/deployment_config/anomaly.json
  tests/testdata/deployment_config/binary.json
  tests/testdata/deployment_config/multiclass.json
  tests/testdata/deployment_config/regression.json
Labels: 00 - Ready for Review, Priority: Blocker

#287 [RAPTOR-4132] pass start_server.sh arguments to DRUM
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/start_server.sh
Labels: 00 - Ready for Review

#288 [RAPTOR-4520,4712] fix dataset temp filepath naming, release v1.4.15
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_args_parser.py
  tests/drum/test_validation_check.py
  tests/fixtures/no_artifact_regression_custom.py
Labels: 00 - Ready for Review

#290 [RAPTOR-4726] implement /info endpoint
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  tests/drum/test_inference.py
Labels: 00 - Ready for Review

#292 [RAPTOR-3911] show progress spinner when building a docker image, release v1.4.16
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/test_drum_docker.py
  tests/fixtures/cmrun_docker_env/Dockerfile
Labels: 00 - Ready for Review
