Repository datarobot/datarobot-user-models, pull requests merged in 2021-01, with the labels that each got.

#266 [RAPTOR-4105] add reading params from env vars
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/artifact_predictor.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/utils.py
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/start_server.sh
  tests/drum/test_fit.py
  tests/drum/test_inference.py
Labels: 00 - Ready for Review

#267 [RAPTOR-4366] remove --unsupervised arg support
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/push.py
  model_templates/training/python3_anomaly_detection/README.md
  model_templates/training/python3_calibrated_anomaly_detection/README.md
  model_templates/training/python3_sklearn_transform/README.md
  public_dropin_environments/python3_keras/fit.sh
  public_dropin_environments/python3_pytorch/fit.sh
  public_dropin_environments/python3_sklearn/fit.sh
  public_dropin_environments/python3_xgboost/fit.sh
  public_dropin_environments/r_lang/fit.sh
  tests/drum/test_fit.py
  tests/drum/test_fit_variety.py
  tests/drum/test_units.py
Labels: 00 - Ready for Review

#269 [RAPTOR-4388] don't run side effects for transform
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/fixtures/transform_fit_custom_non_numeric.py
Labels: Ready for Review

#268 [RAPTOR-4069][RAPTOR-4388] tests for sparse input and output for custom transformers
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/fixtures/transform_fit_custom_sparse_in_out.py
Labels: Ready for Review

#270 [RAPTOR-4423] Return colnames for sparse transform server; return both X and y format in payload
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
  tests/drum/test_inference.py
Labels: Ready for Review

#271 update to 1.4.11
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#272 [RAPTOR-4156] Sampling with replacement was confusing modelers
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/r_fit/fit.R
  tests/drum/test_fit.py
Labels: Needs Review: Custom Models, Ready for Review

#273 release 1.4.12
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#275 [YOLO] make BasePredictor class public
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/src/main/java/com/datarobot/custom/BasePredictor.java
Labels: 00 - Ready for Review

#274 [RAPTOR-4243] Update error messages
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: Needs Review: Custom Models, Ready for Review

#277 [RAPTOR-4487] Warn but don't error in DRUM for prediction consistency check
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/exceptions.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  tests/drum/test_fit.py
Labels: Needs Review: Custom Models, Ready for Review

#279 [RAPTOR-4438] drum server fails if labels have spaces
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/resource/utils.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/testdata/iris_with_spaces.csv
Labels: Ready for Review

#282 [RAPTOR-4521] drum not being installed during tests
  custom_model_runner/requirements.txt
  jenkins/test3_drop_in_envs.sh
  jenkins/test3_inference_model_templates.sh
  jenkins/test3_training_model_templates.sh
Labels: 00 - Ready for Review

#281 [RAPTOR-4506] skip predict if SKIP_PREDICT env var is present
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Ready for Review

#278 [RAPTOR-4443] handle case where X matrix has colname that's the same as target column
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/utils.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/testdata/target_name_duplicated_X.csv
  tests/testdata/target_name_duplicated_y.csv
Labels: Ready for Review
