Repository datarobot/datarobot-user-models, pull requests merged in 2022-04, with the labels that each got.

#614 [RAPTOR-3909] drop 2: unpin werkzeug, release DRUM 1.9.2
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/server.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/requirements.txt
  tests/drum/test_drum_server_failures.py
Labels: 00 - Ready for Review

#615 [RAPTOR-7939] release envs with DRUM 1.9.2
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#607 [MODEL-8952] Adds a file to report fit statistics
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  tests/drum/test_fit.py
  tests/drum/unit/test_args_parser.py
Labels: Ready for Review, Auto Merge on Green, Close Jira on Merge

#616 [MODEL-9047] bump version
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#618 [MODEL-9050] Remove drum autofit
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/__init__.py
  custom_model_runner/datarobot_drum/drum/custom_fit_wrapper.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  requirements_test.txt
  task_templates/3_pipelines/1_simple/custom.py
  task_templates/README.md
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
Labels: Auto Merge on Green, Close Jira on Merge

#621 [MODEL-7545] update model metadata with additional info
  task_templates/2_estimators/3_r_sparse_regression/model-metadata.yaml
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge
