Repository datarobot/datarobot-user-models, pull requests merged in 2022-11, with the labels that each got.

#706 [AGENT-3690] Refactor DrumServerRun and improve shutdown
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  jenkins/test_drop_in_envs.groovy
  jenkins/test_inference_model_templates.groovy
  jenkins/test_integration_general.groovy
  jenkins/test_integration_general.sh
  jenkins/test_integration_per_framework.groovy
  jenkins/test_training_model_templates.groovy
  model_templates/flask_extension_httpauth/README.md
  pyproject.toml
  tests/drum/run_integration_tests_in_framework_container.sh
  tests/drum/test_drum_server_failures.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#707 [DOC-4789] Documentation README.md review.
  model_templates/flask_extension_httpauth/README.md
  model_templates/flask_extension_httpauth/custom_flask.py
  model_templates/flask_extension_httpauth/requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#708 [RAPTOR-8728] bump mlpiper, log4j, release 1.9.13
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/pom.xml
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/py4j_entrypoint/pom.xml
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/custom_java_predictor/pom.xml
  tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java
Labels: Ready for Review, Close Jira on Merge

#711 [RAPTOR-8100] Upon an error do not ask for verbose flag in case it is provided
  custom_model_runner/datarobot_drum/drum/runtime.py
Labels: Ready for Review

#713 [MODEL-10345] remove unused imports
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/server.py
  custom_model_runner/datarobot_drum/drum/templates_generator.py
Labels: Ready for Review

#712 [MODEL-10337] missed pr suggestions
  task_templates/1_transforms/1_python_missing_values/custom.py
  task_templates/1_transforms/3_python3_sklearn_transform/custom.py
  task_templates/2_estimators/9_python_calibrator/custom.py
Labels: 00 - Ready for Review

#719 [AGENT-3741] Download Agent JAR from public repository
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/pom.xml
  jenkins/test_integration_general.sh
Labels: 00 - Ready for Review
