Repository datarobot/datarobot-user-models, pull requests merged in 2022-07, with the labels that each got.

#656 [MODEL-9532] faster vit
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  task_templates/2_estimators/11_python_huggingface_vit/custom.py
  task_templates/2_estimators/11_python_huggingface_vit/requirements.txt
Labels: 00 - Ready for Review, Close Jira on Merge

#652 [RAPTOR-8182] add more tests into pipeline controller boilerplate
  jenkins/build_drum.groovy
  jenkins/run_integration_tests_without_container.groovy
  jenkins/test3_drop_in_envs.sh
  jenkins/test3_inference_model_templates.sh
  jenkins/test3_mlpiper_custom_models_without_container.sh
  jenkins/test3_training_model_templates.sh
  jenkins/test_drop_in_envs.groovy
  jenkins/test_inference_model_templates.groovy
  jenkins/test_training_model_templates.groovy
  pipelineController.yaml
  tests/drum/custom_java_predictor/src/main/java/com/datarobot/test/TestCustomPredictor.java
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_inference.py
  tests/drum/test_inference_custom_java_predictor.py
Labels: Needs Review: Core Modeling, Ready for Review

#659 Fixes Broken Doc Links
  README.md
Labels: 00 - Ready for Review

#658 [RAPTOR-8213] update public Python envs to use python 3.9
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base/README.md
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/requirements.txt
  docker/dropin_env_base_jdk/Dockerfile
  docker/dropin_env_base_jdk/README.md
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk/requirements.txt
  model_templates/python3_pytorch_multiclass/README.md
  model_templates/python3_pytorch_multiclass/artifact.pth
  model_templates/python3_pytorch_multiclass/custom.py
  model_templates/python3_pytorch_multiclass/model_utils.py
  model_templates/python3_pytorch_multiclass/preprocessing.py
  model_templates/python3_pytorch_multiclass/preprocessor.pkl
  model_templates/python3_pytorch_multiclass/requirements.txt
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  task_templates/3_pipelines/13_python3_pytorch_multiclass/preprocessing.py
Labels: Ready for Review

#660 [RAPTOR-8239] remove sagemaker sklearn extension from sklearn environment
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
Labels: Needs Review: Custom Models, Ready for Review

#662 [RAPTOR-8213] update pypmml environment to Python 3.9
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  requirements.txt
Labels: Needs Review: Custom Models, Ready for Review

#665 [RAPTOR-8244] provide Python version in the env's names
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Custom Models, Ready for Review

#668 [MODEL-9609]Point users to the official DR documentation for type schema
  MODEL-METADATA.md
  VALIDATION-SCHEMA.md
Labels: 00 - Ready for Review, Close Jira on Merge

#670 [RAPTOR-8302,8246] split integration tests, update R env to 4.2.1
  docker/dropin_env_base_r/Dockerfile
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
  jenkins/run_integration_tests_per_framework.groovy
  jenkins/run_integration_tests_per_framework.sh
  jenkins/test_drop_in_envs.groovy
  jenkins/test_inference_model_templates.groovy
  jenkins/test_training_model_templates.groovy
  pipelineController.yaml
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/README.md
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  task_templates/1_transforms/4_r_transform_recipe/custom.R
  task_templates/1_transforms/4_r_transform_recipe/model-metadata.yaml
  task_templates/2_estimators/8_r_anomaly_detection/README.md
  task_templates/3_pipelines/3_r_lang/README.md
  task_templates/3_pipelines/3_r_lang/create_pipeline.R
  task_templates/3_pipelines/3_r_lang/model-metadata.yaml
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/integration-helpers.sh
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/run_integration_tests_in_framework_container.sh
  tests/drum/test_fit.py
  tests/drum/test_fit_per_framework.py
  tests/drum/test_inference.py
  tests/drum/test_inference_per_framework.py
  tests/fixtures/drop_in_model_artifacts/Rmodel.R
  tests/fixtures/fit_custom.R
  tests/fixtures/r_binary_classifier/custom.R
  tests/fixtures/r_transform_custom.R
  tests/fixtures/r_transform_custom_with_y.R
  tests/fixtures/r_transform_fit_custom_no_hook.R
Labels: 00 - Ready for Review

#672 [RAPTOR-8323] fix R predictor typechecking, bump rpy2, release 1.9.6
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/adapters/r/r_model_adapter.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/setup.py
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/run_integration_tests_in_framework_container.sh
  tests/drum/test_drum_docker.py
  tests/drum/test_inference_per_framework.py
  tests/drum/test_other_cases.py
  tests/drum/test_other_cases_per_framework.py
  tests/drum/test_unstructured_mode_per_framework.py
  tests/drum/unit/test_utils.py
  tests/fixtures/all_predict_structured_hooks_custom.R
  tests/fixtures/all_predict_structured_hooks_custom_lowercase_r.r
  tests/fixtures/all_predict_unstructured_hooks_custom.R
  tests/fixtures/all_predict_unstructured_hooks_custom_lowercase_r.r
Labels: Ready for Review

#675 [RAPTOR-8348] bump pandas version for R env
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review, Auto Merge on Green

#673 [MODEL-9648] ViT epochs as hyperparameter
  task_templates/2_estimators/11_python_huggingface_vit/custom.py
  task_templates/2_estimators/11_python_huggingface_vit/model-metadata.yaml
  task_templates/2_estimators/11_python_huggingface_vit/requirements.txt
  task_templates/2_estimators/1_python_regression/custom.py
Labels: 00 - Ready for Review, Close Jira on Merge

#674 [RAPTOR-8060] bump java jackson packages to 2.13.3 (#627)
  model_templates/java_unstructured/pom.xml
  tests/drum/custom_java_predictor/pom.xml
Labels: Ready for Review
