Repository datarobot/datarobot-user-models, pull requests merged in 2022-03, with the labels that each got.

#593 [MODEL-8452] Organize unit tests
  tests/drum/test_fit_variety.py
  tests/drum/test_language_predictor.py
  tests/drum/test_units.py
  tests/drum/test_utils.py
  tests/drum/unit/conftest.py
  tests/drum/unit/model_metadata/__init__.py
  tests/drum/unit/model_metadata/test_model_metadata.py
  tests/drum/unit/model_metadata/test_model_metadata_hyperparameters.py
  tests/drum/unit/test_args_parser.py
  tests/drum/unit/test_artifact_predictors.py
  tests/drum/unit/test_classification_label_utils.py
  tests/drum/unit/test_data_marshalling.py
  tests/drum/unit/test_drum_push.py
  tests/drum/unit/test_language_predictors.py
  tests/drum/unit/test_structured_input_read_utils.py
  tests/drum/unit/test_utils.py
Labels: Ready for Review

#595 [MODEL-8479] [Refactor] Move drum utils into separate files
  custom_model_runner/datarobot_drum/drum/artifact_predictors/artifact_predictor.py
  custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/python/python_fit_adapter.py
  custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/r/r_fit_adapter.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/utils/__init__.py
  custom_model_runner/datarobot_drum/drum/utils/drum_utils.py
  custom_model_runner/datarobot_drum/drum/utils/stacktraces.py
  custom_model_runner/datarobot_drum/drum/utils/structured_input_read_utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/drum/test_deployment_config.py
  tests/drum/test_fit.py
  tests/drum/test_inference.py
  tests/drum/test_stats.py
  tests/drum/unit/test_args_parser.py
  tests/drum/unit/test_structured_input_read_utils.py
  tests/drum/unit/test_utils.py
Labels: Ready for Review

#598 [RAPTOR-7857] release DRUM 1.9.0 supporting Py 3.9
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
Labels: Needs Review: Custom Models, 00 - Ready for Review

#600 [RAPTOR-7858] create and use base dropin env image with mlops
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base/README.md
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/pom.xml
  docker/dropin_env_base/pull_artifacts.sh
  docker/dropin_env_base/requirements.txt
  docker/dropin_env_base_jdk/Dockerfile
  docker/dropin_env_base_jdk/README.md
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk/pom.xml
  docker/dropin_env_base_jdk/pull_artifacts.sh
  docker/dropin_env_base_jdk/requirements.txt
  docker/dropin_env_base_julia/Dockerfile
  docker/dropin_env_base_julia/Manifest.toml
  docker/dropin_env_base_julia/Project.toml
  docker/dropin_env_base_julia/README.md
  docker/dropin_env_base_julia/build_image.sh
  docker/dropin_env_base_julia/requirements.txt
  docker/dropin_env_base_julia/sysim.jl
  docker/dropin_env_base_r/Dockerfile
  docker/dropin_env_base_r/README.md
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
  docker/jdk_dropin_env_base/README.md
  docker/jre_dropin_env_base/README.md
  docker/julia_dropin_env_base/requirements.txt
  docker/python3_dropin_env_base/Dockerfile
  docker/python3_dropin_env_base/README.md
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_xgboost/Dockerfile
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#599 [MODEL-8487] Begin decoupling CLI arguments and fit logic
  custom_model_runner/datarobot_drum/drum/adapters/__init__.py
  custom_model_runner/datarobot_drum/drum/adapters/classification_labels_util.py
  custom_model_runner/datarobot_drum/drum/adapters/drum_cli_adapter.py
  custom_model_runner/datarobot_drum/drum/adapters/r/__init__.py
  custom_model_runner/datarobot_drum/drum/adapters/r/fit.R
  custom_model_runner/datarobot_drum/drum/adapters/r/r_model_adapter.py
  custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/base_fit_adapter.py
  custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/python/__init__.py
  custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/python/python_fit_adapter.py
  custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/r/__init__.py
  custom_model_runner/datarobot_drum/drum/custom_tasks/fit_adapters/r/r_fit_adapter.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  custom_model_runner/datarobot_drum/drum/utils/dataframe.py
  custom_model_runner/datarobot_drum/drum/utils/structured_input_read_utils.py
  tests/drum/unit/conftest.py
  tests/drum/unit/test_artifact_predictors.py
  tests/drum/unit/test_classification_label_utils.py
  tests/drum/unit/test_drum_cli_adapter.py
  tests/drum/unit/test_drum_push.py
  tests/fixtures/r_sparse_validation/custom.R
Labels: Needs Review: Custom Models, 00 - Ready for Review

#603 [RAPTOR-7869] update envs with DRUM 1.9.0, prepare for install
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#602 [MODEL-8509] Remove duplicate logic for R-based custom task fits
  custom_model_runner/datarobot_drum/drum/adapters/drum_cli_adapter.py
  custom_model_runner/datarobot_drum/drum/adapters/r/fit.R
  custom_model_runner/datarobot_drum/drum/adapters/r/r_model_adapter.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/utils/dataframe.py
  task_templates/3_pipelines/3_r_lang/create_pipeline.R
  tests/drum/unit/test_drum_cli_adapter.py
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#604 [MODEL-8517] Use DrumCLIAdapter for drum score
  custom_model_runner/datarobot_drum/drum/adapters/drum_cli_adapter.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_runner/datarobot_drum/drum/utils/structured_input_read_utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/drum/unit/test_drum_cli_adapter.py
Labels: 00 - Ready for Review

#611 [RAPTOR-3909] drop 1: pin werkzeug==2.0.3, release DRUM 1.9.1
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  requirements_lint.txt
Labels: 00 - Ready for Review
