Repository datarobot/datarobot-user-models, pull requests merged in 2022-02, with the labels that each got.

#563 [MODEL-7883] updates based on cfds feedback
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  custom_model_tutorial.ipynb
  custom_task_tutorial.ipynb
  tests/fixtures/custom_task_interface_anomaly/custom.py
  tests/fixtures/custom_task_interface_anomaly/model-metadata.yaml
  tests/fixtures/custom_task_interface_binary/custom.py
  tests/fixtures/custom_task_interface_binary/model-metadata.yaml
  tests/fixtures/custom_task_interface_keras_regression/custom.py
  tests/fixtures/custom_task_interface_keras_regression/example_code.py
  tests/fixtures/custom_task_interface_keras_regression/model-metadata.yaml
  tests/fixtures/custom_task_interface_keras_visual/README.md
  tests/fixtures/custom_task_interface_keras_visual/custom.py
  tests/fixtures/custom_task_interface_keras_visual/model-metadata.yaml
  tests/fixtures/custom_task_interface_keras_visual/model_utils.py
  tests/fixtures/custom_task_interface_multiclass/custom.py
  tests/fixtures/custom_task_interface_pytorch_binary/custom.py
  tests/fixtures/custom_task_interface_pytorch_multiclass/artifact.pkl
  tests/fixtures/custom_task_interface_pytorch_multiclass/custom.py
  tests/fixtures/custom_task_interface_pytorch_multiclass/model-metadata.yaml
  tests/fixtures/custom_task_interface_pytorch_multiclass/torch_class.pth
  tests/fixtures/custom_task_interface_regression/custom.py
  tests/fixtures/custom_task_interface_regression/model-metadata.yaml
  tests/fixtures/custom_task_interface_regression_with_custom_class/custom.py
  tests/fixtures/custom_task_interface_regression_with_custom_class/model-metadata.yaml
  tests/fixtures/custom_task_interface_transform_bool_to_int/custom.py
  tests/fixtures/custom_task_interface_transform_bool_to_int/model-metadata.yaml
  tests/fixtures/custom_task_interface_transform_image/custom.py
  tests/fixtures/custom_task_interface_transform_image/model-metadata.yaml
  tests/fixtures/custom_task_interface_transform_missing_values/custom.py
  tests/fixtures/custom_task_interface_transform_missing_values/model-metadata.yaml
  tests/fixtures/custom_task_interface_transform_pipeline/create_transform_pipeline.py
  tests/fixtures/custom_task_interface_transform_pipeline/custom.py
  tests/fixtures/custom_task_interface_transform_pipeline/model-metadata.yaml
  tests/fixtures/custom_task_interface_xgboost_regression/custom.py
  tests/fixtures/custom_task_interface_xgboost_regression/model-metadata.yaml
Labels: Needs Review: Custom Models, 00 - Ready for Review

#565 [RAPTOR-7654] move R environment to use Python 3.7
  public_dropin_environments/r_lang/Dockerfile
Labels: 00 - Ready for Review, Close Jira on Merge

#568 [RAPTOR-7659] make java_dropin_env_base use openjdk base image
  DRCODEOWNERS
  docker/java_dropin_env_base/Dockerfile
  docker/jdk_dropin_env_base/Dockerfile
  docker/jdk_dropin_env_base/README.md
  docker/jre_dropin_env_base/Dockerfile
  docker/jre_dropin_env_base/README.md
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
Labels: 00 - Ready for Review

#570 [RAPTOR-7659] update pmml env image
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
Labels: 00 - Ready for Review

#573 Release v1.7.0
  custom_model_runner/CHANGELOG.md
  custom_model_runner/requirements.txt
  docker/jdk_dropin_env_base/README.md
  docker/jre_dropin_env_base/README.md
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#567 [MODEL-7887] fix whitespace handling for class labels
  custom_model_runner/datarobot_drum/resource/utils.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/functional/test_custom_task_templates.py
  tests/testdata/iris_with_spaces_full.csv
Labels: Ready for Review, Auto Merge on Green

#566 [MODEL-7976] Create save/load_task helper functions
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  tests/fixtures/custom_task_interface_keras_regression/custom.py
  tests/fixtures/custom_task_interface_keras_visual/custom.py
  tests/fixtures/custom_task_interface_pytorch_binary/custom.py
  tests/fixtures/custom_task_interface_pytorch_multiclass/custom.py
Labels: 00 - Ready for Review

#572 [MODEL-7755] handle min/max versions when running pip install for a docker image
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/drum/test_drum_docker.py
Labels: Ready for Review

#574 [MODEL-7541][MODEL-8029] Improve R hyperparameter template, add docs for other hyperparam templates
  custom_model_runner/datarobot_drum/drum/args_parser.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/fixtures/python3_sklearn_binary_hyperparameters/model-metadata.yaml
  tests/fixtures/python3_sklearn_transform_hyperparameters/model-metadata.yaml
  tests/fixtures/r_lang_hyperparameters/README.md
  tests/fixtures/r_lang_hyperparameters/create_pipeline.R
  tests/fixtures/r_lang_hyperparameters/custom.R
  tests/fixtures/r_lang_hyperparameters/model-metadata.yaml
  tests/testdata/iris_with_binary.csv
  tests/testdata/r_parameters.json
Labels: Auto Merge on Green

#577 [MODEL-8112] updates to validation schema documentation
  MODEL-METADATA.md
  VALIDATION-SCHEMA.md
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#564 [RAPTOR-7539]Add built-in support for ONNX
  .gitignore
  DEFINE-INFERENCE-MODEL.md
  custom_model_runner/datarobot_drum/drum/artifact_predictors/onnx_predictor.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  model_templates/README.md
  model_templates/python3_onnx_anomaly/README.md
  model_templates/python3_onnx_anomaly/anomaly_juniors.onnx
  model_templates/python3_onnx_anomaly/custom.py
  model_templates/python3_onnx_binary/README.md
  model_templates/python3_onnx_binary/binary_iris.onnx
  model_templates/python3_onnx_binary/custom.py
  model_templates/python3_onnx_multiclass/README.md
  model_templates/python3_onnx_multiclass/class_labels.txt
  model_templates/python3_onnx_multiclass/custom.py
  model_templates/python3_onnx_multiclass/multiclass_SDSS.onnx
  model_templates/python3_onnx_multiclass/preprocessing.py
  model_templates/python3_onnx_multiclass/preprocessor.pkl
  model_templates/python3_onnx_multiclass/requirements.txt
  model_templates/python3_onnx_regression/README.md
  model_templates/python3_onnx_regression/custom.py
  model_templates/python3_onnx_regression/regression_juniors.onnx
  public_dropin_environments/README.md
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/README.md
  public_dropin_environments/python3_onnx/__init__.py
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/fit.sh
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_onnx/start_server.sh
  requirements.txt
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_inference.py
  tests/drum/test_units.py
  tests/fixtures/artifacts.py
  tests/fixtures/drop_in_model_artifacts/onnx_bin.onnx
  tests/fixtures/drop_in_model_artifacts/onnx_multi.onnx
  tests/fixtures/drop_in_model_artifacts/onnx_reg.onnx
  tests/functional/conftest.py
  tests/functional/test_drop_in_environments.py
  tests/functional/test_inference_model_templates.py
Labels: 00 - Ready for Review

#583 [RAPTOR-7711] don't include default drum java predictors into java classpath when working with custom predictor
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
Labels: 00 - Ready for Review

#581 [MODEL-7979] Treat single col blank values as NAN in CSVs
  custom_model_runner/datarobot_drum/drum/utils.py
  tests/drum/unit/test_shared_fit_preprocessing.py
Labels: 00 - Ready for Review

#585 [RAPTOR-7723] Pin markupsafe
  custom_model_runner/requirements.txt
Labels: 00 - Ready for Review

#584 Get ready for v1.8.0 release
  DRCODEOWNERS
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#587 [MODEL-8376] add 1.8.0 to version, update changelog
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Auto Merge on Green, Close Jira on Merge
