Repository datarobot/datarobot-user-models, pull requests merged in 2022-05, with the labels that each got.

#624 [MODEL-9265] update fit.sh and the environments
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/fit.sh
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/fit.sh
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/fit.sh
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/fit.sh
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/fit.sh
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/fit.sh
Labels: Ready for Review

#625 Update setup.py license metadata
  custom_model_runner/setup.py
Labels: 00 - Ready for Review, Auto Merge on Green

#627 [RAPTOR-8060] bump java jackson packages to 2.13.3
  model_templates/java_unstructured/pom.xml
  tests/drum/custom_java_predictor/pom.xml
Labels: Needs Review: Custom Models, 00 - Ready for Review
