Repository datarobot/datarobot-user-models, pull requests merged in 2022-08, with the labels that each got.

#678 [MODEL-7482] support integer values as categorical values
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  task_templates/2_estimators/4_python_binary_classification/custom.py
  task_templates/2_estimators/6_python_multiclass_classification/custom.py
  task_templates/2_estimators/7_python_anomaly/custom.py
  task_templates/2_estimators/9_python_regression_with_custom_class/custom.py
  tests/drum/unit/model_metadata/test_model_metadata.py
  tests/functional/test_custom_task_templates.py
Labels: Ready for Review, Close Jira on Merge

#679 [MODEL-9684] log method added to custom task interface
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
Labels: Ready for Review, Close Jira on Merge

#680 [MODEL-9698] bump version to 1.9.8
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#684 [MODEL-9736] static logging method
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  docker/dropin_env_base/Dockerfile
  docker/drum_integration_tests_base/Dockerfile
  jenkins/test3_mlpiper_custom_models_without_container.sh
  requirements_test.txt
  tests/drum/run-drum-tests-in-container.sh
Labels: 00 - Ready for Review, Close Jira on Merge

#683 [MODEL-9671] Fix missing image values in the typeschema
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/model_metadata/test_model_metadata.py
Labels: Ready for Review, Close Jira on Merge

#671 [RAPTOR-8303] move more test cases to be run per environment - drop 1/many
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base/README.md
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/requirements.txt
  docker/dropin_env_base_jdk/Dockerfile
  docker/dropin_env_base_jdk/README.md
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk/requirements.txt
  docker/dropin_env_base_r/Dockerfile
  docker/dropin_env_base_r/README.md
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/r_lang/Dockerfile
  tests/drum/test_inference.py
  tests/drum/test_inference_per_framework.py
  tools/image-build-utils.sh
Labels: Ready for Review

#687 [RAPTOR-8364] Check env var before printing env dump
  example_dropin_environments/julia_mlj/start_server.sh
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_onnx/start_server.sh
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/start_server.sh
Labels: Ready for Review

#691 [RAPTOR-8480] bump datarobot-prediction java lib to 2.2.1
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/pom.xml
Labels: Ready for Review
