Repository datarobot/datarobot-user-models, pull requests merged in 2022-10, with the labels that each got.

#696 [RAPTOR-8618] pin dr==2.28.1
  custom_model_runner/CHANGELOG.md
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  requirements_test.txt
Labels: Ready for Review, Do Not Merge

#685 [RAPTOR-7748] pass dir/spooler_type params to the embedded mlops monitor, release v1.9.10
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  jenkins/test3_mlpiper_custom_models_without_container.sh
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/test_inference_custom_java_predictor.py
  tests/drum/test_mlops_monitoring.py
  tests/drum/unit/test_args_parser.py
Labels: Ready for Review

#697 [RAPTOR-8636] update base envs, public envs
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base/README.md
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/requirements.txt
  docker/dropin_env_base_jdk/Dockerfile
  docker/dropin_env_base_jdk/README.md
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk/requirements.txt
  docker/dropin_env_base_julia/Dockerfile
  docker/dropin_env_base_r/README.md
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
  jenkins/run_integration_tests_in_a_single_container.groovy
  jenkins/run_integration_tests_without_container.groovy
  jenkins/test_integration.sh
  jenkins/test_integration_without_container.sh
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/drum/test_mlops_monitoring.py
Labels: Ready for Review

#689 [RAPTOR-8303] tests refactoring
  custom_model_runner/datarobot_drum/drum/args_parser.py
  docker/drum_integration_tests_base/.gitignore
  docker/drum_integration_tests_base/Dockerfile
  docker/drum_integration_tests_base/README.md
  docker/drum_integration_tests_base/build_test_docker.sh
  docker/drum_integration_tests_base/sysim.jl
  jenkins/run_black_check.sh
  jenkins/run_integration_tests_per_framework.groovy
  jenkins/test_drop_in_envs.groovy
  jenkins/test_drop_in_envs.sh
  jenkins/test_inference_model_templates.groovy
  jenkins/test_inference_model_templates.sh
  jenkins/test_integration.sh
  jenkins/test_integration_general.groovy
  jenkins/test_integration_general.sh
  jenkins/test_integration_per_framework.groovy
  jenkins/test_integration_per_framework.sh
  jenkins/test_integration_without_container.sh
  jenkins/test_training_model_templates.groovy
  jenkins/test_training_model_templates.sh
  pipelineController.yaml
  requirements.txt
  requirements_test.txt
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/run-drum-tests-in-container.sh
  tests/drum/run_integration_tests_in_framework_container.sh
  tests/drum/test_fit.py
  tests/drum/test_fit_per_framework.py
  tests/drum/test_inference.py
  tests/drum/test_other_cases.py
  tests/drum/test_other_cases_per_framework.py
  tests/drum/test_stats.py
  tests/drum/unit/model_metadata/test_model_metadata.py
  tests/drum/unit/test_language_predictors.py
  tests/drum/unit/test_utils.py
  tests/fixtures/cmrun_docker_env/Dockerfile
  tests/fixtures/cmrun_docker_env/__init__.py
  tests/fixtures/cmrun_docker_env/requirements.txt
  tests/fixtures/cmrun_docker_env/start_server.sh
  tests/functional/test_drum_push.py
Labels: Ready for Review

#703 [RAPTOR-8303] fix tests, comments cleanup
  jenkins/test_integration_general.sh
  requirements_test.txt
Labels: Needs Review: Custom Models, Ready for Review

#702 [RAPTOR-8526] Initialize the DataRobot Python client at the drum layer
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_dr_api_access.py
  tests/drum/unit/test_args_parser.py
  tests/fixtures/unstructured_custom_dr_api_access.py
Labels: Ready for Review

#704 [RAPTOR-8683] release DRUM v1.9.11, update envs
  custom_model_runner/CHANGELOG.md
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Close Jira on Merge
