Repository datarobot/datarobot-user-models, pull requests merged in 2022-06, with the labels that each got.

#633 [RAPTOR-8109] Fix tests + Keras environment following upgrades in packages
  public_dropin_environments/python3_keras/requirements.txt
  tests/functional/test_inference_model_templates.py
Labels: Ready for Review, Auto Merge when Ready

#636 [RAPTOR-8060] bump java jackson packages to 2.13.3 - drop 2
  tests/drum/custom_java_predictor/pom.xml
  tests/drum/run-drum-tests-in-container.sh
Labels: 00 - Ready for Review

#634 [MODEL-9100] Huggingface estimator template
  custom_task_tutorial.ipynb
  task_templates/2_estimators/11_python_huggingface_vit/README.md
  task_templates/2_estimators/11_python_huggingface_vit/custom.py
  task_templates/2_estimators/11_python_huggingface_vit/img_utils.py
  task_templates/2_estimators/11_python_huggingface_vit/model-metadata.yaml
  task_templates/2_estimators/11_python_huggingface_vit/requirements.txt
Labels: Ready for Review, Auto Merge on Green, Close Jira on Merge

#639 [RAPTOR-8155] release DRUM 1.9.4
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Custom Models, 00 - Ready for Review

#641 [MODEL-9340]
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/model_metadata/test_model_metadata.py
Labels: Ready for Review

#650 [RAPTOR-8182] introduce pipeline controller boilerplate
  Jenkinsfile
  jenkins/black_check.groovy
  jenkins/build_drum.groovy
  jenkins/run_integration_tests_in_a_single_container.groovy
  pipelineController.yaml
  tests/drum/run-drum-tests-in-container.sh
Labels: 00 - Ready for Review

#657 [RAPTOR-8210] skip julia env functional test and move env
  DEFINE-INFERENCE-MODEL.md
  example_dropin_environments/julia_mlj/Dockerfile
  example_dropin_environments/julia_mlj/README.md
  example_dropin_environments/julia_mlj/__init__.py
  example_dropin_environments/julia_mlj/dr_requirements.txt
  example_dropin_environments/julia_mlj/env_info.json
  example_dropin_environments/julia_mlj/start_server.sh
  model_templates/julia/README.md
  pipelineController.yaml
  public_dropin_environments/README.md
  tests/drum/run-drum-tests-in-container.sh
  tests/functional/test_inference_model_templates.py
Labels: Ready for Review

#651 [MODEL-7471] manage non raw target information correctly.
  task_templates/3_pipelines/14_python3_keras_joblib/custom.py
  task_templates/3_pipelines/15_python3_keras_vizai_joblib/model_utils.py
Labels: Auto Merge on Green
