Repository datarobot/datarobot-user-models, pull requests merged in 2022-01, with the labels that each got.

#534 [MODEL-7700] code dir cannot be the same as output dir for fit
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/drum/test_fit.py
Labels: Ready for Review, Auto Merge on Green

#537 [MODEL-7730] update codeowners
  DRCODEOWNERS
Labels: Auto Merge on Green

#533 [MODEL-7633][MODEL-7634] Drum functionality for new custom task template interface
  custom_model_runner/datarobot_drum/custom_task_interfaces/__init__.py
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/custom_task_interfaces/estimator_interfaces.py
  custom_model_runner/datarobot_drum/custom_task_interfaces/transform_interface.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/model_adapter.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_fit.py
  tests/fixtures/custom_task_interface_regression/custom.py
  tests/fixtures/custom_task_interface_transform/custom.py
Labels: Auto Merge on Green

#544 Minor relational link fixes in a couple READMEs
  model_templates/README.md
  model_templates/julia/README.md
  model_templates/python3_pmml/README.md
  model_templates/python3_sklearn_anomaly/README.md
  model_templates/python3_xgboost/README.md
Labels: documentation, Needs Review: Custom Models, 00 - Ready for Review

#552 [RAPTOR-7554] Gracefully shutdown MLOps upon POD's completion/termination
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/drum/server.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/utils.py
  custom_model_runner/requirements.txt
  requirements_test.txt
  tests/drum/test_mlops_monitoring.py
  tests/drum/utils.py
  tests/fixtures/unstructured_custom_mlops.py
Labels: Ready for Review

#561 DRUM bump to 1.6.2.post6
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/pom.xml
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/julia_mlj/dr_requirements.txt
  public_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review
