Repository datarobot/datarobot-user-models, pull requests merged in 2023-07, with the labels that each got.

#789 [RAPTOR-9530] update environments
  custom_model_runner/CHANGELOG.md
  docker/dropin_env_base/README.md
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/requirements.txt
  docker/dropin_env_base_jdk/README.md
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk/requirements.txt
  docker/dropin_env_base_r/README.md
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
  jenkins/test_integration_general.sh
  model_templates/python3_onnx_multiclass/requirements.txt
  model_templates/python3_pytorch_multiclass/requirements.txt
  model_templates/python3_sklearn_runtime_params/requirements.txt
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review, Close Jira on Merge

#793 [RAPTOR-9604] update pytorch: env reqs, desc for GenAI apps
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  tests/functional/conftest.py
  tests/functional/test_inference_model_templates.py
Labels: Ready for Review

#794 [NB-3884] Fix openjdk version
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/env_info.json
Labels: Ready for Review

#796 [EPS-1199] update notebooks envs
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/r_notebook/Dockerfile
  public_dropin_notebook_environments/r_notebook/env_info.json
Labels: 00 - Ready for Review, Close Jira on Merge

#795 [MODEL-11933] fixed misleading tests
  tests/drum/unit/test_runtime_parameters.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#797 [NB-3832] add notebooks python GPU env
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/README.md
  public_dropin_notebook_environments/python39_notebook_gpu/agent/README.md
  public_dropin_notebook_environments/python39_notebook_gpu/agent/agent.py
  public_dropin_notebook_environments/python39_notebook_gpu/agent/cgroup_watchers.py
  public_dropin_notebook_environments/python39_notebook_gpu/agent/requirements-agent.txt
  public_dropin_notebook_environments/python39_notebook_gpu/common-user-limits.sh
  public_dropin_notebook_environments/python39_notebook_gpu/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/extensions/README.md
  public_dropin_notebook_environments/python39_notebook_gpu/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook_gpu/ipython_config.py
  public_dropin_notebook_environments/python39_notebook_gpu/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python39_notebook_gpu/kernel.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/setup-prompt.sh
  public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
Labels: Ready for Review

#799 [RAPTOR-9604] update pytorch env to allow in-notebook deployment flows - drop 2
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
Labels: Ready for Review
