Repository datarobot/datarobot-user-models, pull requests merged in 2023-02, with the labels that each got.

#690 [RAPTOR-8801] change test jobs run order (phases)
  jenkins/test_integration_general.groovy
  jenkins/test_integration_per_framework.groovy
  pipelineController.yaml
Labels: Ready for Review, Close Jira on Merge

#732 [AGENT-4009] Fix some bugs found during testing RuntimeParams
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  tests/drum/unit/test_runtime_parameters.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#731 [RAPTOR-8948] Exception in a custom model is not properly displayed in the UI
  custom_model_runner/datarobot_drum/drum/runtime.py
  tests/drum/test_drum_docker.py
  tests/drum/test_drum_server_failures.py
  tests/drum/test_fit_per_framework.py
Labels: Ready for Review

#735 [RAPTOR-9004] Upgrade dr-usertool to 1.0.0
  requirements_test.txt
  tests/functional/conftest.py
Labels: 00 - Ready for Review

#736 [AGENT-4034] Improve how we inject runtime params during local testing
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
  tests/drum/test_runtime_parameters.py
  tests/drum/unit/test_runtime_parameters.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#738 [RAPTOR-9061] bump datarobot==3.0.2, release 1.10.0
  custom_model_runner/CHANGELOG.md
  custom_model_runner/requirements.txt
  example_dropin_environments/julia_mlj/dr_requirements.txt
  example_dropin_environments/julia_mlj/env_info.json
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  requirements_test.txt
  tests/functional/test_drop_in_environments.py
  tests/functional/test_inference_model_templates.py
Labels: Ready for Review

#739 [RAPTOR-9073] set drum version to 1.10.0
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Close Jira on Merge

#740 [MODEL-10997]remove debugging print
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#742 [MODEL-11001]update from deprecated method
  custom_task_tutorial.ipynb
  tests/drum/unit/model_metadata/test_model_metadata.py
  tests/drum/utils.py
  tests/functional/test_custom_task_templates.py
Labels: Ready for Review, Close Jira on Merge
