Repository datarobot/datarobot-user-models, pull requests merged in 2023-05, with the labels that each got.

#763 [RAPTOR-9177] Upgrade dr-usertool to 2.x
  jenkins/test_drop_in_envs.groovy
  jenkins/test_inference_model_templates.groovy
  jenkins/test_training_model_templates.groovy
  requirements_test.txt
  tests/fixtures/user_permissions.json
  tests/functional/conftest.py
Labels: 00 - Ready for Review

#764 [RAPTOR-9358] Add example and documentation for MLOps reporting from unstructured models
  DEFINE-INFERENCE-MODEL.md
  model_templates/python3_unstructured_with_mlops_reporting/README.md
  model_templates/python3_unstructured_with_mlops_reporting/custom.py
  model_templates/python3_unstructured_with_mlops_reporting/datasets/holdout-surgical-dataset.csv
  model_templates/python3_unstructured_with_mlops_reporting/datasets/predict-request-surgical-dataset.csv
  model_templates/python3_unstructured_with_mlops_reporting/datasets/training-surgical-dataset.csv
  model_templates/python3_unstructured_with_mlops_reporting/model.pkl
  model_templates/python3_unstructured_with_mlops_reporting/train-and-generate-artifacts/mlops-example-surgical-dataset.csv
  model_templates/python3_unstructured_with_mlops_reporting/train-and-generate-artifacts/train_and_generate_artifacts.py
Labels: Ready for Review

#765 [MODEL-11047] Handle missing values in single column
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/score.R
  custom_model_runner/datarobot_drum/resource/transform_helpers.py
Labels: 00 - Ready for Review, Auto Merge on Green

#768 [RAPTOR-9391] Fit in user email length limit in tests
  tests/functional/conftest.py
Labels: 00 - Ready for Review, Priority: Blocker

#766 [MODEL-11519]bump version of drum
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Close Jira on Merge

#771 [MODEL-11546] bump version of drum for R
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review
