Repository datarobot/datarobot-user-models, pull requests merged in 2023-08, with the labels that each got.

#800 [RAPTOR-9609] return 513 from error server (flask) / production server (nginx+uwsgi)
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/drum/server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/drum_server_api.yaml
  custom_model_runner/setup.py
  tests/drum/test_drum_server_failures.py
Labels: Ready for Review, Close Jira on Merge

#802 [RAPTOR-9667] add Python3-GenAI public env, remove GenAi deps from pytorch env
  public_dropin_environments/python3_genai/Dockerfile
  public_dropin_environments/python3_genai/README.md
  public_dropin_environments/python3_genai/__init__.py
  public_dropin_environments/python3_genai/dr_requirements.txt
  public_dropin_environments/python3_genai/env_info.json
  public_dropin_environments/python3_genai/fit.sh
  public_dropin_environments/python3_genai/requirements.txt
  public_dropin_environments/python3_genai/start_server.sh
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
Labels: 00 - Ready for Review, Close Jira on Merge

#801 [RAPTOR-9663] make DRUM to support Py 3.11, release 1.10.8
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_genai/dr_requirements.txt
  public_dropin_environments/python3_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review, Close Jira on Merge

#756 [RAPTOR-9684] bump pandas<=2.0.3
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/python3_genai/requirements.txt
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
  requirements.txt
Labels: Ready for Review, Close Jira on Merge

#804 [MODEL-12041] Template to show loading a pretrained estimator
  task_templates/2_estimators/12_python_pretrained/README.md
  task_templates/2_estimators/12_python_pretrained/custom.py
  task_templates/2_estimators/12_python_pretrained/estimator.joblib
  task_templates/2_estimators/12_python_pretrained/model-metadata.yaml
  task_templates/2_estimators/12_python_pretrained/requirements.txt
Labels: Ready for Review, Close Jira on Merge

#803 [RAPTOR-9675] base GenAI env on Python 3.11
  docker/dropin_env_base_jdk_ubi/Dockerfile
  docker/dropin_env_base_jdk_ubi/README.md
  docker/dropin_env_base_jdk_ubi/build_image.sh
  docker/dropin_env_base_jdk_ubi/pom.xml
  docker/dropin_env_base_jdk_ubi/pull_artifacts.sh
  docker/dropin_env_base_jdk_ubi/requirements.txt
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/README.md
  public_dropin_environments/python311_genai/__init__.py
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/fit.sh
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python311_genai/start_server.sh
  public_dropin_environments/python39_genai/Dockerfile
  public_dropin_environments/python39_genai/README.md
  public_dropin_environments/python39_genai/__init__.py
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python39_genai/fit.sh
  public_dropin_environments/python39_genai/requirements.txt
  public_dropin_environments/python39_genai/start_server.sh
  tests/drum/run_integration_tests_in_framework_container.sh
Labels: Ready for Review

#807 [RAPTOR-9708] pin datarobot<4, release v1.10.10
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review, Close Jira on Merge

#810 [NB-3234] fix notebook images
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
Labels: 00 - Ready for Review

#811 [RAPTOR-9738] Added docs into model templates about implicit hook implementation
  model_templates/flask_extension_httpauth/custom.py
  model_templates/julia/jl_galaxy/custom.jl
  model_templates/julia/jl_grade/custom.jl
  model_templates/julia/jl_iris_binary/custom.jl
  model_templates/python3_keras/custom.py
  model_templates/python3_keras_joblib/custom.py
  model_templates/python3_keras_vizai_joblib/custom.py
  model_templates/python3_onnx_anomaly/custom.py
  model_templates/python3_onnx_binary/custom.py
  model_templates/python3_onnx_multiclass/custom.py
  model_templates/python3_onnx_regression/custom.py
  model_templates/python3_pmml/custom.py
  model_templates/python3_pytorch/custom.py
  model_templates/python3_sklearn/custom.py
  model_templates/python3_sklearn_anomaly/custom.py
  model_templates/python3_sklearn_runtime_params/custom.py
  model_templates/python3_xgboost/custom.py
  model_templates/r_lang/custom.R
Labels: 00 - Ready for Review
