Repository datarobot/datarobot-user-models, pull requests merged in 2023-12, with the labels that each got.

#883 [AGENT-5017] Add new "/ping" health check method compatible with SageMaker
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/drum/server.py
  tests/functional/test_dr_api_access.py
  tests/functional/test_drum_server_failures.py
Labels: Ready for Review

#884 [MMM-15697] bump dmm library to 0.3.1
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green

#881 [RAPTOR-10166] release DRUM v1.10.15
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review, Close Jira on Merge

#882 [RAPTOR-10167] update envs' base images and drum
  custom_model_runner/CHANGELOG.md
  docker/dropin_env_base/README.md
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/requirements.txt
  docker/dropin_env_base_jdk/README.md
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk/requirements.txt
  docker/dropin_env_base_jdk_ubi/Dockerfile
  docker/dropin_env_base_jdk_ubi/README.md
  docker/dropin_env_base_jdk_ubi/build_image.sh
  docker/dropin_env_base_jdk_ubi/requirements.txt
  docker/dropin_env_base_r/Dockerfile
  docker/dropin_env_base_r/README.md
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/Dockerfile
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review, Close Jira on Merge

#887 [AGENT-5188] Adding support for boolean runtime param
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
  tests/functional/test_runtime_parameters.py
  tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py
Labels: 00 - Ready for Review

#888 [AGENT-5188] release DRUM v1.10.16
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#890 [NB-3656] Port notebook changes
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
Labels: Ready for Review

#894 [NB-3656] Fix dataframe ext for codespaces
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
Labels: Ready for Review

#885 [RAPTOR-10171] add a separate job for integration tests
  docker/drum_builder/Dockerfile
  docker/drum_builder/build_docker.sh
  jenkins/test_functional_general.sh
  jenkins/test_integration.groovy
  pipelineController.yaml
Labels: Ready for Review, Close Jira on Merge

#900 [NB-4998] Added custom environments for Python 3.11 and GPU with terraform
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python311_notebook/README.md
  public_dropin_notebook_environments/python311_notebook/agent/README.md
  public_dropin_notebook_environments/python311_notebook/agent/agent.py
  public_dropin_notebook_environments/python311_notebook/agent/cgroup_watchers.py
  public_dropin_notebook_environments/python311_notebook/agent/requirements-agent.txt
  public_dropin_notebook_environments/python311_notebook/common-user-limits.sh
  public_dropin_notebook_environments/python311_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/extensions/README.md
  public_dropin_notebook_environments/python311_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python311_notebook/ipython_config.py
  public_dropin_notebook_environments/python311_notebook/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python311_notebook/kernel.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python311_notebook/setup-prompt.sh
  public_dropin_notebook_environments/python311_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python311_notebook/sshd_config
  public_dropin_notebook_environments/python311_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_tf/agent/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_tf/agent/agent.py
  public_dropin_notebook_environments/python39_notebook_gpu_tf/agent/cgroup_watchers.py
  public_dropin_notebook_environments/python39_notebook_gpu_tf/agent/requirements-agent.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/common-user-limits.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/extensions/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_tf/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook_gpu_tf/ipython_config.py
  public_dropin_notebook_environments/python39_notebook_gpu_tf/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python39_notebook_gpu_tf/kernel.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements-gpu.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/setup-prompt.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_tf/start_server.sh
Labels: Needs Review: Custom Models, Ready for Review

#893 [AGENT-5214] Add support for numeric runtime parameters
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
  model_templates/python3_sklearn_runtime_params/custom.py
  model_templates/python3_sklearn_runtime_params/model-metadata.yaml
  tests/functional/test_runtime_parameters.py
  tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py
Labels: 00 - Ready for Review

#902 [NB-4998] New images bug fixes
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
Labels: Ready for Review

#903 [RAPTOR-10198] set nbx team as DRCODEOWNERS for nbx envs
  DRCODEOWNERS
Labels: Ready for Review, Close Jira on Merge

#895 [MODEL-12834] CustomTasks Network Access: 5 - scrub outputs
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/custom_task_interfaces/user_secrets.py
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  tests/unit/datarobot_drum/custom_task_interfaces/test_custom_task_interface.py
  tests/unit/datarobot_drum/custom_task_interfaces/test_user_secrets.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: 00 - Ready for Review, Close Jira on Merge
