Repository datarobot/datarobot-user-models, pull requests merged in 2023-09, with the labels that each got.

#815 [MMM-14493] bump dmm library
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
Labels: Needs Review: Custom Models, 00 - Ready for Review

#816 [MMM-14465] bump dmm library to 0.2.5
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
Labels: Ready for Review

#817 [RAPTOR-9739] Add regression dummy custom model
  model_templates/python3_dummy_regression/README.md
  model_templates/python3_dummy_regression/custom.py
Labels: 00 - Ready for Review

#819 [RAPTOR-9815] update name of the Python 3.11 GenAi env
  public_dropin_environments/python311_genai/env_info.json
Labels: Ready for Review, Close Jira on Merge

#821 [MMM-14688] bump dmm library to 0.2.6
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
Labels: 00 - Ready for Review

#824 [BUZOK-454] Sync 3.11 GenAI env with DataRobot Buzok
  public_dropin_environments/python311_genai/README.md
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
Labels: 00 - Ready for Review
