Repository datarobot/datarobot-user-models, pull requests merged in 2023-11, with the labels that each got.

#850 [MODEL-12560] Update versions
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/fit.sh
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python39_genai/fit.sh
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/fit.sh
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/fit.sh
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/fit.sh
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/fit.sh
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/fit.sh
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#845 [RAPTOR-10015] rearrange requirements files
  README.md
  jenkins/test_drop_in_envs.sh
  jenkins/test_inference_model_templates.sh
  jenkins/test_training_model_templates.sh
  requirements.txt
  requirements_dev.txt
  requirements_test.txt
  requirements_test_functional.txt
  tests/drum/locally-run-drum-tests.sh
Labels: Ready for Review, Close Jira on Merge

#854 [NCA-1696] Added Streamlit environment
  public_custom_application_environments/python39_streamlit/Dockerfile
  public_custom_application_environments/python39_streamlit/README.md
  public_custom_application_environments/python39_streamlit/env_info.json
Labels: Close Jira on Merge, Auto Merge when Ready

#851 [NCA-1683] Adding DRApp CLI tool
  DRCODEOWNERS
  README.md
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  drapps/README.md
  drapps/demo-streamlit/demo-streamlet.py
  drapps/demo-streamlit/pages/deployments.py
  drapps/demo-streamlit/pages/projects.py
  drapps/demo-streamlit/start-app.sh
  drapps/drapps.py
  drapps/requirements.txt
  jenkins/test_integration_general.sh
  tests/drapps/__init__.py
  tests/drapps/test_drapps.py
Labels: Ready for Review

#853 [MMM-15336] DRUM should support deployment id as run time parameter
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
  tests/drum/test_runtime_parameters.py
Labels: Ready for Review

#860 [NCA-1710] Fixed typo in file name
  drapps/demo-streamlit/demo-streamlit.py
  drapps/demo-streamlit/start-app.sh
Labels: 00 - Ready for Review, Close Jira on Merge, Auto Merge when Ready

#858 [-] Add project URLs for source and changelog to show on pypi
  custom_model_runner/setup.py
Labels: 00 - Ready for Review

#862 [RAPTOR-10068] add drapps binary
  custom_model_runner/setup.py
  drapps/drapps
  tests/drapps/test_drapps.py
Labels: Needs Review: Custom Models, Ready for Review, Close Jira on Merge

#863 [RAPTOR-10071] Increase verbosity of the drop-in environments test
  jenkins/test_drop_in_envs.sh
Labels: Ready for Review, 00 - Ready for Review

#864 [RAPTOR-10086] remove feature impact unstable redundant test
  jenkins/test_inference_model_templates.sh
  jenkins/test_training_model_templates.sh
  tests/functional/test_drop_in_environments.py
Labels: Ready for Review

#865 [RAPTOR-10096] remove unstable redundant functional tests
  tests/functional/test_drop_in_environments.py
Labels: Needs Review: Custom Models, Ready for Review

#867 [RAPTOR-10100] bump pyarrow<=14.0.1
  custom_model_runner/CHANGELOG.md
  example_dropin_environments/julia_mlj/dr_requirements.txt
  task_templates/1_transforms/5_python3_image_transform/requirements.txt
Labels: Needs Review: Custom Models, Ready for Review, Close Jira on Merge

#866 NB-4727: Allowlisted the working directory in the git configs
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/start_server.sh
Labels: 00 - Ready for Review

#868 [MODEL-12684] CustomTasks Network Access: docs and examples
  MODEL-METADATA.md
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/custom_task_interfaces/user_secrets.py
  task_templates/2_estimators/13_python_credentials_and_internet_access/README.md
  task_templates/2_estimators/13_python_credentials_and_internet_access/custom.py
  task_templates/2_estimators/13_python_credentials_and_internet_access/model-metadata.yaml
  task_templates/2_estimators/13_python_credentials_and_internet_access/secrets/MY_CREDENTIAL
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#870 [RAPTOR-10110] release DRUM v1.10.13
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python39_genai/requirements.txt
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt
Labels: Needs Review: Custom Models, Ready for Review, Close Jira on Merge

#869 [RAPTOR-10097] add multiple artifacts negative tests
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_other_cases_per_framework.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: Ready for Review, Close Jira on Merge

#873 [RAPTOR-10137] remove drapps, bump pyarrow, release v1.10.14
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  custom_model_runner/setup.py
  jenkins/black_check.groovy
  jenkins/test_functional_general.sh
  jenkins/test_unit.groovy
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
  tests/drapps/__init__.py
  tests/drapps/test_drapps.py
  tests/functional/test_fit_per_framework.py
Labels: Close Jira on Merge

#872 [RAPTOR-10131] reorder test by putting heavier envs first
  tests/e2e/test_drop_in_environments.py
Labels: Ready for Review, Auto Merge on Green, Close Jira on Merge

#879 [RAPTOR-10158] fix DRUM version check when running drum in container
  custom_model_runner/datarobot_drum/drum/drum.py
Labels: Ready for Review, Close Jira on Merge

#877 [AGENT-5013] Extend DRUM to support SageMaker api method
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  tests/conftest.py
  tests/functional/test_deployment_config.py
  tests/functional/test_inference.py
  tests/functional/test_inference_per_framework.py
  tests/functional/test_stats.py
  tests/functional/test_unstructured_mode_per_framework.py
Labels: Ready for Review
