Repository datarobot/datarobot-user-models, pull requests merged in 2023-04, with the labels that each got.

#754 [RAPTOR-9286] bump pandas to <= 1.5.3
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
  requirements.txt
Labels: Ready for Review, Close Jira on Merge

#760 [MODEL-11370] fix templates
  custom_model_runner/datarobot_drum/custom_task_interfaces/estimator_interfaces.py
  custom_task_tutorial.ipynb
  task_templates/2_estimators/4_python_binary_classification/custom.py
Labels: 00 - Ready for Review, Close Jira on Merge

#755 [NB-3062] Update notebooks dropins
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/agent/requirements-agent.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/common-user-limits.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python38_snowflake_notebook/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/setup-prompt.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/agent/requirements-agent.txt
  public_dropin_notebook_environments/python39_notebook/common-user-limits.sh
  public_dropin_notebook_environments/python39_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/setup-prompt.sh
  public_dropin_notebook_environments/python39_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook/start_server.sh
  public_dropin_notebook_environments/r_notebook/Dockerfile
  public_dropin_notebook_environments/r_notebook/agent/requirements-agent.txt
  public_dropin_notebook_environments/r_notebook/common-user-limits.sh
  public_dropin_notebook_environments/r_notebook/dr_requirements.txt
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/r_notebook/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/r_notebook/renv.lock
  public_dropin_notebook_environments/r_notebook/setup-common.R
  public_dropin_notebook_environments/r_notebook/setup-prompt.sh
  public_dropin_notebook_environments/r_notebook/setup-ssh.sh
  public_dropin_notebook_environments/r_notebook/start_server.sh
Labels: Ready for Review

#761 [MODEL-11392]fix issue with integer column NaN
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  tests/drum/unit/model_metadata/test_model_metadata.py
Labels: Ready for Review, Close Jira on Merge

#762 [MODEL-11423] bump version to 1.10.2
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Close Jira on Merge
