Repository datarobot/datarobot-user-models, pull requests merged in 2023-06, with the labels that each got.

#776 [RAPTOR-9417] Upgrade dr-usertool to v3
  requirements_test.txt
  tests/functional/conftest.py
Labels: 00 - Ready for Review

#773 [RAPTOR-9422-9423] bump werkzeug flask markupsafe deps, release 1.10.4
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/predictors/pom.xml
  custom_model_runner/requirements.txt
  jenkins/black_check.groovy
  jenkins/test_drop_in_envs.sh
  jenkins/test_inference_model_templates.sh
  jenkins/test_integration_general.groovy
  jenkins/test_integration_general.sh
  jenkins/test_training_model_templates.sh
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  requirements_test.txt
Labels: Ready for Review

#777 [RAPTOR-9455] bump scikit-learn==1.0.2, release 1.10.5
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/profiler/stats_collector.py
  example_dropin_environments/julia_mlj/dr_requirements.txt
  jenkins/test_integration_general.sh
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
  requirements.txt
  requirements_test.txt
Labels: 00 - Ready for Review, Close Jira on Merge

#778 [-] Upgrade NBX kernels
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/agent/requirements-agent.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/agent/requirements-agent.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/r_notebook/dr_requirements.txt
  public_dropin_notebook_environments/r_notebook/env_info.json
Labels: Ready for Review

#779 [RAPTOR-9468] use the latest base image for R env, fix test
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
  tests/fixtures/r_transform_custom_sparse_output.R
Labels: Ready for Review, Close Jira on Merge

#781 [-] fix NBX kernel vulenrabilities for python 3.8
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
Labels: Ready for Review

#782 [MODEL-11706] simple hyperparam examples
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  task_templates/2_estimators/1_python_regression/custom.py
  task_templates/2_estimators/1_python_regression/model-metadata.yaml
  task_templates/2_estimators/4_python_binary_classification/custom.py
  task_templates/2_estimators/4_python_binary_classification/model-metadata.yaml
  task_templates/2_estimators/7_python_anomaly/custom.py
  task_templates/2_estimators/7_python_anomaly/model-metadata.yaml
  task_templates/README.md
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#786 [MMM-13517] DRUM Support for new text generation target type
  custom_model_runner/datarobot_drum/drum/adapters/cli/shared/drum_input_file_adapter.py
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/conftest.py
  tests/drum/constants.py
  tests/drum/test_deployment_config.py
  tests/drum/test_inference_per_framework.py
  tests/drum/unit/adapters/test_drum_class_label_adapter.py
  tests/drum/unit/adapters/test_drum_fit_adapter.py
  tests/drum/unit/test_data_marshalling.py
  tests/drum/unit/test_language_predictors.py
  tests/fixtures/text_generation_custom.py
  tests/testdata/deployment_config/text_generation.json
  tests/testdata/prompts.csv
Labels: 00 - Ready for Review, 00 - Ask for Review on Green

#787 [MMM-13720] Remove hard coded target name for text generation target type
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/adapters/cli/shared/drum_input_file_adapter.py
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/requirements.txt
  requirements_test.txt
  tests/drum/test_deployment_config.py
  tests/drum/unit/test_data_marshalling.py
  tests/testdata/deployment_config/text_generation.json
Labels: Ready for Review, 00 - Ask for Review on Green

#788 [RAPTOR-9519] release v1.10.7
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/r_lang/dr_requirements.txt
  tests/drum/unit/test_data_marshalling.py
Labels: Ready for Review
