Repository datarobot/datarobot-user-models, pull requests merged in 2023-10, with the labels that each got.

#826 [MMM-14853] bump dmm library to 0.2.7
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
Labels: Ready for Review

#825 [BUZOK-454] Fix numpy version in 3.11 GenAI env, add new packages & add tests
  jenkins/test_integration_per_framework.sh
  pipelineController.yaml
  public_dropin_environments/python311_genai/README.md
  public_dropin_environments/python311_genai/requirements.txt
  tests/conftest.py
  tests/drum/constants.py
  tests/functional/conftest.py
  tests/functional/test_drop_in_environments.py
Labels: Ready for Review

#827 [MODEL-11992] update start_server.sh to pass shellcheck
  example_dropin_environments/julia_mlj/start_server.sh
  public_dropin_environments/java_codegen/start_server.sh
  public_dropin_environments/python311_genai/start_server.sh
  public_dropin_environments/python39_genai/start_server.sh
  public_dropin_environments/python3_keras/start_server.sh
  public_dropin_environments/python3_onnx/start_server.sh
  public_dropin_environments/python3_pmml/start_server.sh
  public_dropin_environments/python3_pytorch/start_server.sh
  public_dropin_environments/python3_sklearn/start_server.sh
  public_dropin_environments/python3_xgboost/start_server.sh
  public_dropin_environments/r_lang/start_server.sh
Labels: Needs Review: Custom Models, Ready for Review

#823 [ENGPROD-6377] Supersede BRANCHING.yaml with RELEASE.yaml for federalized release
  BRANCHING.yaml
  RELEASE.yaml
Labels: Ready for Review, Close Jira on Merge, Auto Merge when Ready

#828 [NB-4479] Increase max kernels value
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python38_snowflake_notebook/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook_gpu/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/jupyter_kernel_gateway_config.py
Labels: Ready for Review

#829 NB-4449: Allowed to dynamically specify working directory
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/setup-ssh.sh
  public_dropin_notebook_environments/r_notebook/start_server.sh
Labels: 00 - Ready for Review

#832 [MODEL-12503] CustomTask Network Access: 4 - initial additions to DRUM
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/enum.py
  tests/drum/unit/custom_task_interfaces/__init__.py
  tests/drum/unit/custom_task_interfaces/test_custom_task_interface.py
  tests/drum/unit/model_metadata/test_model_metadata.py
  tests/drum/unit/test_args_parser.py
Labels: 00 - Ready for Review

#830 [RAPTOR-9963] update envs, release 9.2
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review

#836 [NB-4502] fix python38 and GPU notebooks
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/setup-ssh.sh
Labels: Ready for Review

#839 [MODEL-12503] update test suites
  jenkins/test_integration_general.sh
  jenkins/test_unit.groovy
  pipelineController.yaml
  requirements_test_unit.txt
  tests/drum/run_integration_tests_in_framework_container.sh
  tests/integration/__init__.py
  tests/integration/datarobot_drum/__init__.py
  tests/integration/datarobot_drum/drum/__init__.py
  tests/integration/datarobot_drum/drum/language_predictors/__init__.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
Labels: 00 - Ready for Review

#840 [RAPTOR-10002] update error messages
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/runtime.py
Labels: Ready for Review, Close Jira on Merge

#841 [RAPTOR-9976] clean exception handling logic
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/model_adapter.py
Labels: Ready for Review

#844 [RAPTOR-10016] DRUM: fix a potential flaky unit test concerning the stdout flusher
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/stdout_flusher.py
  requirements.txt
  requirements_test.txt
  tests/unit/datarobot_drum/resource/components/Python/prediction_server/test_stdout_flusher.py
Labels: Ready for Review

#843 ]MODEL-12503] insert secrets values into fit/score
  custom_model_runner/datarobot_drum/drum/adapters/cli/shared/drum_class_label_adapter.py
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/__init__.py
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/abstract_model_adapter.py
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/fit.R
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/r_model_adapter.py
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/artifact_predictor.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/pmml_predictor.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/sklearn_predictor.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/xgboost_predictor.py
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  custom_model_runner/datarobot_drum/drum/push.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  tests/conftest.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
  tests/unit/datarobot_drum/drum/adapters/cli/__init__.py
  tests/unit/datarobot_drum/drum/adapters/cli/conftest.py
  tests/unit/datarobot_drum/drum/adapters/cli/shared/__init__.py
  tests/unit/datarobot_drum/drum/adapters/cli/shared/test_drum_class_label_adapter.py
  tests/unit/datarobot_drum/drum/adapters/cli/shared/test_drum_file_input_adapter.py
  tests/unit/datarobot_drum/drum/adapters/cli/test_drum_fit_adapter.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/__init__.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
  tests/unit/datarobot_drum/drum/language_predictors/python_predictor/__init__.py
  tests/unit/datarobot_drum/drum/language_predictors/python_predictor/test_python_predictor.py
  tests/unit/datarobot_drum/drum/test_args_parser.py
  tests/unit/datarobot_drum/drum/test_data_marshalling.py
  tests/unit/datarobot_drum/drum/test_drum.py
  tests/unit/datarobot_drum/drum/test_perf_testing.py
  tests/unit/datarobot_drum/drum/test_push.py
  tests/unit/datarobot_drum/model_metadata/test_model_metadata.py
  tests/unit/datarobot_drum/resource/test_drum_server_utils.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#846 [NB-4660] Bump R, datarobot and langchain - pin cloudpickle
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/r_notebook/Dockerfile
  public_dropin_notebook_environments/r_notebook/env_info.json
Labels: Ready for Review

#847 [MODEL-12504] make credential objects
  custom_model_runner/datarobot_drum/custom_task_interfaces/__init__.py
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/custom_task_interfaces/user_secrets.py
  tests/unit/datarobot_drum/custom_task_interfaces/conftest.py
  tests/unit/datarobot_drum/custom_task_interfaces/test_custom_task_interface.py
  tests/unit/datarobot_drum/custom_task_interfaces/test_user_secrets.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge
