Repository datarobot/datarobot-user-models, pull requests merged in 2024-05, with the labels that each got.

#1000 [APPLS-2188] streamlit env, add dr components wheel
  public_dropin_environments/python39_streamlit/packages/dr_components-0.1.4-py3-none-any.whl
Labels: Needs Review: Custom Models, Ready for Review

#997 [AGENT-5631 AGENT-5634] update GPU predictors to send deployment events
  custom_model_runner/datarobot_drum/drum/gpu_predictors/__init__.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nemo_predictor.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/triton_predictor.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/utils.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  model_templates/gpu_nemo_textgen/custom_model/custom.py
  model_templates/gpu_nemo_textgen/custom_model/model-metadata.yaml
  model_templates/gpu_vllm_textgen/custom_model/model-metadata.yaml
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
  tests/fixtures/gpu_nemo_textgen/custom_model/custom.py
  tests/fixtures/gpu_nemo_textgen/custom_model/model-metadata.yaml
  tests/unit/datarobot_drum/drum/test_drum.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#1002 [cherry-pick][APPLS-2188] streamlit env, add dr components wheel
  public_dropin_environments/python39_streamlit/packages/dr_components-0.1.4-py3-none-any.whl
Labels: 00 - Ready for Review, Frozen Branch Merge Request

#1003 [AGENT-5469] Bump version to 1.11.0
  DRCODEOWNERS
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  model_templates/gpu_nemo_textgen/custom.py
  model_templates/gpu_nemo_textgen/model-metadata.yaml
  model_templates/gpu_vllm_textgen/custom.py
  model_templates/gpu_vllm_textgen/model-metadata.yaml
  public_dropin_gpu_environments/nemollm_inference_ms/dr_requirements.txt
  public_dropin_gpu_environments/nemollm_inference_ms/env_info.json
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
  public_dropin_gpu_environments/triton_server/env_info.json
  public_dropin_gpu_environments/vllm/dr_requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
  tests/functional/test_inference_per_framework.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#1004 [AGENT-5587] Update NeMo Inference Server env
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nemo_predictor.py
  jenkins/test_functional_per_framework.sh
  model_templates/gpu_nemo_tensorrt_llm_textgen/README.md
  model_templates/gpu_nemo_tensorrt_llm_textgen/custom.py
  model_templates/gpu_nemo_tensorrt_llm_textgen/model-metadata.yaml
  public_dropin_gpu_environments/nim_llm/Dockerfile
  public_dropin_gpu_environments/nim_llm/README.md
  public_dropin_gpu_environments/nim_llm/dr_requirements.in
  public_dropin_gpu_environments/nim_llm/dr_requirements.txt
  public_dropin_gpu_environments/nim_llm/env_info.json
  public_dropin_gpu_environments/nim_llm/start_server.sh
  tests/fixtures/gpu_nemo_textgen/custom.py
  tests/fixtures/gpu_nemo_textgen/model-metadata.yaml
  tests/functional/run_integration_tests_in_framework_container.sh
  tests/functional/test_inference_per_framework.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#1005 [NB-5922] Update java-11-openjdk deps in notebooks
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
Labels: 00 - Ready for Review, Close Jira on Merge

#1010 [RAPTOR-10746] fix java and genai tests
  jenkins/test_functional_per_framework.sh
  pipelineController.yaml
  tests/conftest.py
  tests/constants.py
  tests/functional/test_inference_per_framework.py
Labels: Ready for Review, Close Jira on Merge

#1028 [AGENT-5469] Fix bashisms in GPU envs
  public_dropin_gpu_environments/nim_llm/start_server.sh
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/start_server.sh
Labels: 00 - Ready for Review, Auto Merge when Ready

#1012 [DSX-3349] bump pysdk versions
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: Ready for Review, Frozen Branch Merge Request

#1011 [NB-5928] Update git in notebooks GPU kernels
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
Labels: 00 - Ready for Review, Close Jira on Merge

#1034 [AGENT-5735] update vLLM env
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
  model_templates/gpu_nemo_tensorrt_llm_textgen/model-metadata.yaml
  model_templates/gpu_vllm_textgen/model-metadata.yaml
  model_templates/python3_sklearn_runtime_params/model-metadata.yaml
  public_dropin_gpu_environments/nim_llm/dr_requirements.txt
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/dr_requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
Labels: Needs Review: Tracking-Agent, 00 - Ready for Review, Close Jira on Merge

#1033 [AGENT-5696] Add runtime-parameter-file to docker command
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/functional/test_runtime_parameters.py
  tests/unit/datarobot_drum/drum/test_args_parser.py
  tests/unit/datarobot_drum/drum/test_drum.py
Labels: 00 - Ready for Review

#1035 [NB-5708] Introduce base python311 notebook environment
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/README.md
  public_dropin_notebook_environments/python311_notebook_base/agent/README.md
  public_dropin_notebook_environments/python311_notebook_base/agent/agent.py
  public_dropin_notebook_environments/python311_notebook_base/agent/cgroup_watchers.py
  public_dropin_notebook_environments/python311_notebook_base/agent/requirements-agent.txt
  public_dropin_notebook_environments/python311_notebook_base/common-user-limits.sh
  public_dropin_notebook_environments/python311_notebook_base/dr_requirements.txt
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/extensions/README.md
  public_dropin_notebook_environments/python311_notebook_base/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python311_notebook_base/ipython_config.py
  public_dropin_notebook_environments/python311_notebook_base/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python311_notebook_base/kernel.json
  public_dropin_notebook_environments/python311_notebook_base/requirements.txt
  public_dropin_notebook_environments/python311_notebook_base/setup-prompt.sh
  public_dropin_notebook_environments/python311_notebook_base/setup-ssh.sh
  public_dropin_notebook_environments/python311_notebook_base/setup-venv.sh
  public_dropin_notebook_environments/python311_notebook_base/sshd_config
  public_dropin_notebook_environments/python311_notebook_base/start_server.sh
Labels: 00 - Ready for Review

#1027 [RAPTOR-10751] Tidy up GenAI environments
  DRCODEOWNERS
  example_dropin_environments/python39_genai/Dockerfile
  example_dropin_environments/python39_genai/README.md
  example_dropin_environments/python39_genai/__init__.py
  example_dropin_environments/python39_genai/dr_requirements.txt
  example_dropin_environments/python39_genai/env_info.json
  example_dropin_environments/python39_genai/fit.sh
  example_dropin_environments/python39_genai/requirements.txt
  example_dropin_environments/python39_genai/start_server.sh
Labels: 00 - Ready for Review

#1042 Bump requests 2.32.2 in GPU envs
  public_dropin_gpu_environments/nim_llm/dr_requirements.txt
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
  public_dropin_gpu_environments/vllm/dr_requirements.txt
Labels: 00 - Ready for Review, dependencies, Auto Merge when Ready, python

#1044 [RAPTOR-10834] release DRUM v1.11.2
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Ready for Review, Close Jira on Merge

#1045 [RAPTOR-10839] fix port values jsonification, release v1.11.3
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
Labels: Ready for Review, Close Jira on Merge

#1043 [NB-5708] Update python 3.11 images to the Python 3.11.7
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
Labels: 00 - Ready for Review, Auto Merge on Green

#1047 [BUZOKNEW-473] Adjust transformers for nemo guardrails compatibility
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
Labels: 00 - Ready for Review

#1048 [NB-6071] Upgrade Pillow to address CVE-2024-28219
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  public_dropin_environments/python3_keras/requirements.txt
  task_templates/1_transforms/5_python3_image_transform/requirements.txt
  tests/fixtures/custom_task_interface_transform_image/requirements.txt
Labels: 00 - Ready for Review

#1049 [BUZZOK-4043] Bump sentence transformers to 3.0.0
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
Labels: Ready for Review
