Repository datarobot/datarobot-user-models, pull requests merged in 2024-09, with the labels that each got.

#1113 [RAPTOR-11378] update Py support to Py>=3.8, bump version to 1.12.0
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/setup.py
Labels: Ready for Review, Close Jira on Merge

#1108 [APP-2364] [APPLS-2364] Add new custom app env 3.12 with streamlit 1.36.0
  DRCODEOWNERS
  public_dropin_environments/python312_streamlit/Dockerfile
  public_dropin_environments/python312_streamlit/README.md
  public_dropin_environments/python312_streamlit/__init__.py
  public_dropin_environments/python312_streamlit/env_info.json
  tools/image-build-utils.sh
Labels: 00 - Ready for Review

#1110 [CODEGEN-1946] Chat monitoring
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/resource/chat_helpers.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/unit/datarobot_drum/drum/chat_utils.py
  tests/unit/datarobot_drum/drum/conftest.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: Ready for Review

#1116 [RAPTOR-11401] unpin datarobot dep in test
  requirements_test.txt
Labels: Ready for Review, Close Jira on Merge

#1119 [CODEGEN-1924] Add chat to OpenAPI spec
  custom_model_runner/drum_server_api.yaml
Labels: Ready for Review

#1121 [CODEGEN-1949] Use custom model workers with and without runtime_params_file
  custom_model_runner/datarobot_drum/drum/main.py
  tests/unit/datarobot_drum/drum/test_main.py
Labels: 00 - Ready for Review

#1127 [AGENT-6285] Warning message if moderation is disabled
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Ready for Review, Auto Merge on Green

#1125 [CODEGEN-1946] Chat monitoring improvements
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  tests/unit/datarobot_drum/drum/chat_utils.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
Labels: Ready for Review
