Repository datarobot/datarobot-user-models, pull requests merged in 2024-06, with the labels that each got.

#1050 [AGENT-5795] Update vLLM env for large LLMs
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/start_server.sh
Labels: Ready for Review

#1052 [NB-5419] Fix Notebooks DataFrame
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/extensions/dataframe_formatter.py
Labels: Ready for Review

#1060 [RAPTOR-10986] Set proper dependency for numpy in the runner and java-codegen env
  custom_model_runner/CHANGELOG.md
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/requirements.txt
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1061 [RAPTOR-11004] release v1.11.5
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Needs Review: Core Modeling, 00 - Ready for Review, Close Jira on Merge

#1059 [CODEGEN-1913] Fix nginx permissions
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base_jdk/Dockerfile
  docker/dropin_env_base_jdk_ubi/Dockerfile
  docker/dropin_env_base_r/Dockerfile
Labels: Ready for Review, Close Jira on Merge

#1062 [RAPTOR-11006] update base images with the latest drum v1.11.5
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/requirements.txt
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk/requirements.txt
  docker/dropin_env_base_jdk_ubi/Dockerfile
  docker/dropin_env_base_jdk_ubi/build_image.sh
  docker/dropin_env_base_jdk_ubi/requirements.txt
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
Labels: Needs Review: Custom Models, 00 - Ready for Review, Close Jira on Merge

#1063 [RAPTOR-11008] update env's base images
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Core Modeling, Ready for Review, Close Jira on Merge

#1066 [NB-6229] Update git & python patch version in base notebooks image
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
Labels: Ready for Review

#1065 [NB-6164] Remove Notebook Drop-in R Environment
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/r_notebook/.Rprofile
  public_dropin_notebook_environments/r_notebook/Dockerfile
  public_dropin_notebook_environments/r_notebook/README.md
  public_dropin_notebook_environments/r_notebook/agent/README.md
  public_dropin_notebook_environments/r_notebook/agent/agent.py
  public_dropin_notebook_environments/r_notebook/agent/cgroup_watchers.py
  public_dropin_notebook_environments/r_notebook/agent/requirements-agent.txt
  public_dropin_notebook_environments/r_notebook/common-user-limits.sh
  public_dropin_notebook_environments/r_notebook/dr_requirements.txt
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/extensions/README.md
  public_dropin_notebook_environments/r_notebook/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/r_notebook/renv.lock
  public_dropin_notebook_environments/r_notebook/setup-base.R
  public_dropin_notebook_environments/r_notebook/setup-common.R
  public_dropin_notebook_environments/r_notebook/setup-prompt.sh
  public_dropin_notebook_environments/r_notebook/setup-ssh.sh
  public_dropin_notebook_environments/r_notebook/setup-venv.sh
  public_dropin_notebook_environments/r_notebook/sshd_config
  public_dropin_notebook_environments/r_notebook/start_server.sh
Labels: Ready for Review

#1069 [RAPTOR-11069] change test to make it run a couple of seconds longer
  tests/functional/test_performance_check.py
Labels: Ready for Review, Close Jira on Merge
