Repository datarobot/datarobot-user-models, pull requests merged in 2024-12, with the labels that each got.

#1189 [MMMDATA-875] Add GeoPoint target type
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
  tests/conftest.py
  tests/constants.py
  tests/fixtures/geo_point_custom.py
  tests/functional/test_deployment_config.py
  tests/functional/test_inference_per_framework.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
  tests/testdata/deployment_config/geo_point.json
  tests/testdata/geo_dataset.csv
  tests/unit/datarobot_drum/drum/adapters/cli/shared/test_drum_class_label_adapter.py
  tests/unit/datarobot_drum/drum/adapters/cli/test_drum_fit_adapter.py
  tests/unit/datarobot_drum/drum/test_data_marshalling.py
Labels: 00 - Ready for Review

#1191 [MMMDATA-875] Add geopoint to predictors
  custom_model_runner/datarobot_drum/drum/artifact_predictors/sklearn_predictor.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/xgboost_predictor.py
Labels: Ready for Review

#1192 [MMMDATA-875] Change geopoint output to wkt
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/fixtures/geo_point_custom.py
  tests/functional/test_deployment_config.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
  tests/unit/datarobot_drum/drum/test_data_marshalling.py
Labels: 00 - Ready for Review

#1193 [RAPTOR-11770] update envs: drum v1.15.0 and set use_cases
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
Labels: Ready for Review, Close Jira on Merge

#1198 [RAPTOR-11783] Deprecate the production mode and replace its functionality with Flask running in multi-process mode
  .harness/test_functional_by_framework.yaml
  .harness/test_functional_general.yaml
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/resource_monitor.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/__init__.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/component.json
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  custom_model_runner/drum_server_api.yaml
  custom_model_runner/setup.py
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base_jdk/Dockerfile
  docker/dropin_env_base_jdk_ubi/Dockerfile
  docker/dropin_env_base_r/Dockerfile
  docker/drum_builder/Dockerfile
  example_dropin_environments/julia_mlj/Dockerfile
  example_dropin_environments/python39_genai/Dockerfile
  jenkins/test_functional_general.sh
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_gpu_environments/python311_genai/Dockerfile
  public_dropin_gpu_environments/vllm/start_server.sh
  tests/functional/test_drum_server_failures.py
  tests/functional/test_inference.py
  tests/functional/test_inference_custom_java_predictor.py
  tests/functional/test_inference_per_framework.py
  tests/functional/test_unstructured_mode_per_framework.py
  tests/locust/README.md
  tests/unit/datarobot_drum/drum/test_args_parser.py
  tests/unit/datarobot_drum/drum/test_drum.py
  tools/image-build-utils.sh
  tools/parallel_requests.py
Labels: 00 - Ready for Review

#1196 [CFX-590] [CFX-539] Make Notebook custom environments to be compatible with custom models
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python311_notebook/start_server.sh
  public_dropin_notebook_environments/python311_notebook/start_server_drum.sh
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/requirements.txt
  public_dropin_notebook_environments/python311_notebook_base/start_server.sh
  public_dropin_notebook_environments/python311_notebook_base/start_server_drum.sh
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu/start_server_drum.sh
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/start_server_drum.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/start_server_drum.sh
Labels: Ready for Review
