Repository datarobot/datarobot-user-models, pull requests merged in 2024-07, with the labels that each got.

#1071 [RAPTOR-11016] add a pipeline to build base env images
  .harness/build_env_base_docker_images.yaml
  .harness/dropin_env_base.yaml
  .harness/dropin_env_base_jdk.yaml
  .harness/dropin_env_base_jdk_ubi.yaml
  .harness/dropin_env_base_r.yaml
  .harness/drum_builder.yaml
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base_jdk/Dockerfile
  docker/dropin_env_base_jdk/build_image.sh
  docker/dropin_env_base_jdk_ubi/Dockerfile
  docker/dropin_env_base_jdk_ubi/build_image.sh
  docker/dropin_env_base_r/build_image.sh
  docker/drum_builder/build_docker.sh
  docker/drum_builder/build_image.sh
Labels: Ready for Review

#1088 [RAPTOR-11194] Remove dependency from requirements_test.txt
  jenkins/test_drop_in_envs.sh
  jenkins/test_inference_model_templates.sh
  jenkins/test_training_model_templates.sh
  requirements_test.txt
  requirements_test_e2e_inference.txt
  requirements_test_e2e_training.txt
Labels: 00 - Ready for Review, Close Jira on Merge

#1089 [RAPTOR-11201] cleanup final exception logging
  custom_model_runner/datarobot_drum/drum/runtime.py
Labels: Ready for Review, Close Jira on Merge
