Repository datarobot/datarobot-user-models, pull requests merged in 2024-08, with the labels that each got.

#1054 Add short-circuit to NIM env
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nemo_predictor.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/triton_predictor.py
  public_dropin_gpu_environments/nim_llm/dr_requirements.txt
  public_dropin_gpu_environments/nim_llm/env_info.json
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
  public_dropin_gpu_environments/triton_server/env_info.json
  public_dropin_gpu_environments/vllm/dr_requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
Labels: Needs Review: Custom Models, 00 - Ready for Review, Auto Merge on Green

#1096 [RAPTOR-11248] add disk usage printing in the e2e test
  jenkins/test_drop_in_envs.sh
  tests/e2e/test_drop_in_environments.py
Labels: Ready for Review, Close Jira on Merge

#1099 Update Base Notebook 3.11 image
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
Labels: Ready for Review

#1090 [CODEGEN-1924] Add chat hook
  DEFINE-INFERENCE-MODEL.md
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/server.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  requirements_test_unit.txt
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: Ready for Review

#1103 [AGENT-6033] Bump vllm env to 0.5.4
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
Labels: 00 - Ready for Review, Auto Merge when Ready

#1106 [AGENT-6110] Moderation support for chat interface
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/enum.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: Ready for Review

#1101 [CODEGEN-1918] Support concurrent requests for Custom Models
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  tests/functional/test_inference_per_framework.py
  tests/unit/datarobot_drum/drum/test_args_parser.py
  tests/unit/datarobot_drum/drum/test_drum.py
  tests/unit/datarobot_drum/drum/test_main.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
  tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py
Labels: 00 - Ready for Review

#1107 [CODEGEN-1945] Fix chat wrong parameter order
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: 00 - Ready for Review

#1109 [AGENT-5722] Don't set cache dirs in DRUM
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
Labels: Needs Review: Core Modeling, Needs Review: Custom Models, 00 - Ready for Review, Auto Merge on Green
