Repository datarobot/datarobot-user-models, pull requests merged in 2024-02, with the labels that each got.

#922 [RAPTOR-10323] Fix extra model extraction for text generation models
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  tests/functional/test_inference_per_framework.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: 00 - Ready for Review

#921 [RAPTOR-10205] Add support for extra model output in PPS response
  custom_model_runner/datarobot_drum/resource/deployment_config_helpers.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/functional/test_deployment_config.py
Labels: 00 - Ready for Review

#924 [MMM-16119] bump dmm library to 0.3.6
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: 00 - Ready for Review, Close Jira on Merge

#925 [NB-5277] [NB-5278] [NB-5279] Recent NBX updates to kernels
  public_dropin_notebook_environments/python311_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python311_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/setup-ssh.sh
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/setup-ssh.sh
Labels: Ready for Review

#926 [RAPTOR-10333] Handle redundant quotation marks in target name when extracting extra model output
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: 00 - Ready for Review

#927 [NB-5277][NB-5278][NB-5279] Update dependencies in notebook drop-ins Dockerfiles
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/r_notebook/Dockerfile
  public_dropin_notebook_environments/r_notebook/env_info.json
  public_dropin_notebook_environments/r_notebook/renv.lock
Labels: Ready for Review

#929 [RAPTOR-10337] Extra model output, bug fixes, release 1.10.20
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#931 [APPLS-1977] Removed custom apps CLI code
  DRCODEOWNERS
  README.md
  drapps/README.md
  drapps/demo-streamlit/demo-streamlit.py
  drapps/demo-streamlit/pages/deployments.py
  drapps/demo-streamlit/pages/projects.py
  drapps/demo-streamlit/start-app.sh
  drapps/drapps
  drapps/drapps.py
  drapps/requirements.txt
Labels: 00 - Ready for Review, Close Jira on Merge, Auto Merge when Ready

#775 [RAPTOR-10422] add pylint, move code to try avoid circular deps
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/data_marshalling.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/model_metadata.py
  custom_model_runner/datarobot_drum/drum/push.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/components/Python/uwsgi_component/uwsgi_serving.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  requirements_lint.txt
  tests/unit/datarobot_drum/drum/test_push.py
  tests/unit/datarobot_drum/model_metadata/test_model_metadata.py
  tests/unit/datarobot_drum/model_metadata/test_model_metadata_hyperparameters.py
Labels: Ready for Review, Close Jira on Merge
