Repository datarobot/datarobot-user-models, pull requests merged in 2024-11, with the labels that each got.

#1172 [AGENT-6475] Bump new version of Drum
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1170 [AGENT-6475] Bump version of DRUM to latest in GPU envs
  public_dropin_gpu_environments/nim_llm/dr_requirements.txt
  public_dropin_gpu_environments/nim_llm/env_info.json
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
  public_dropin_gpu_environments/triton_server/env_info.json
  public_dropin_gpu_environments/vllm/dr_requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
Labels: 00 - Ready for Review

#1164 [RAPTOR-11619] update public environments with new base images
  docker/dropin_env_base_jdk_ubi/build_image.sh
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  tests/functional/test_fit_per_framework.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1173 [RAPTOR-11626] Unpin 'datarobot-storage' package
  custom_model_runner/requirements.txt
Labels: 00 - Ready for Review

#1161 [CFX-123] Update dataframe formatter
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/python311_notebook/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook_gpu/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook_gpu_tf/extensions/dataframe_formatter.py
Labels: Ready for Review

#1176 [CFX-506] Update PYTHON_EXACT_VERSION to 3.11.10
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
Labels: 00 - Ready for Review, Auto Merge when Ready

#1175 [RAPTOR-11620] try to unpin DRUM dependencies
  .harness/test_functional_by_framework.yaml
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/python311_genai/requirements.txt
  tests/functional/test_fit_per_framework.py
Labels: Needs Review: Core Modeling, Ready for Review, Close Jira on Merge, Needs Review: GenAI Build (Buzok)

#1177 [RAPTOR-11637] make single requirements file for envs
  .harness/test_functional_by_framework.yaml
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/requirements.txt
  tools/image-build-utils.sh
Labels: 00 - Ready for Review, Close Jira on Merge, Needs Review: GenAI Build (Buzok)

#1171 [CODEGEN-1974] Don't fail request if mlops reporting fails
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
Labels: Ready for Review

#1178 [RAPTOR-11647] release v1.14.2
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
Labels: Ready for Review, Close Jira on Merge

#1180 [AGENT-6505] Make BaseOpenAiGpuPredictor not care about model name
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  public_dropin_gpu_environments/nim_llm/Dockerfile
  public_dropin_gpu_environments/nim_llm/env_info.json
  public_dropin_gpu_environments/nim_llm/requirements.in
  public_dropin_gpu_environments/nim_llm/requirements.txt
  public_dropin_gpu_environments/triton_server/Dockerfile
  public_dropin_gpu_environments/triton_server/requirements.in
  public_dropin_gpu_environments/triton_server/requirements.txt
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.in
  public_dropin_gpu_environments/vllm/requirements.txt
  tests/functional/test_inference_per_framework.py
Labels: 00 - Ready for Review, Priority: Blocker, Close Jira on Merge, Auto Merge when Ready

#1182 Fix minor Markdown nit
  public_dropin_gpu_environments/nim_llm/README.md
Labels: 00 - Ready for Review, Auto Merge when Ready

#1183 Update metadata for GPU envs
  public_dropin_gpu_environments/nim_llm/env_info.json
  public_dropin_gpu_environments/triton_server/env_info.json
  public_dropin_gpu_environments/vllm/env_info.json
Labels: Needs Review: Tracking-Agent, 00 - Ready for Review

#1185 Tweak defaults for vLLM example
  model_templates/gpu_nim_textgen/README.md
  model_templates/gpu_nim_textgen/model-metadata.yaml
  model_templates/gpu_vllm_textgen/README.md
  model_templates/gpu_vllm_textgen/model-metadata.yaml
Labels: 00 - Ready for Review

#1186 [RAPTOR-11705] Implement lazy-loading command line option and set environment variables accordingly
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/lazy_loading/__init__.py
  custom_model_runner/datarobot_drum/drum/lazy_loading/constants.py
  custom_model_runner/datarobot_drum/drum/lazy_loading/lazy_loading_handler.py
  custom_model_runner/datarobot_drum/drum/lazy_loading/schema.py
  custom_model_runner/datarobot_drum/drum/main.py
  tests/functional/test_fit_per_framework.py
  tests/functional/test_lazy_loading.py
  tests/unit/datarobot_drum/drum/lazy_loading/test_lazy_loading_handler.py
  tests/unit/datarobot_drum/drum/lazy_loading/test_schema.py
  tests/unit/datarobot_drum/drum/test_args_parser.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: 00 - Ready for Review

#1187 [RAPTOR-11721] Publish DRUM v1.15.0 with support for lazy-loading from command line
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  tests/unit/datarobot_drum/drum/test_push.py
Labels: Ready for Review
