Repository datarobot/datarobot-user-models, pull requests merged in 2024-03, with the labels that each got.

#937 [AGENT-5370] Add env var support for runtime-parameter-file
  custom_model_runner/datarobot_drum/drum/args_parser.py
  tests/functional/test_runtime_parameters.py
Labels: 00 - Ready for Review

#939 [RAPTOR-10452] bump py4j gateway polling time
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
Labels: Ready for Review, Close Jira on Merge

#943 [MMMDATA-226] bump dmm library to 0.3.7
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: 00 - Ready for Review, Close Jira on Merge

#944 AGENT-5349 add NVIDIA Triton Server dropin environment
  public_dropin_gpu_environments/triton_server/Dockerfile
  public_dropin_gpu_environments/triton_server/README.md
  public_dropin_gpu_environments/triton_server/__init__.py
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
  public_dropin_gpu_environments/triton_server/start_server.sh
Labels: 00 - Ready for Review

#938 [AGENT-5408] Integration with moderations library
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/enum.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: Ready for Review

#946 [RAPTOR-10347] Propagate error with strict yaml
  custom_model_runner/datarobot_drum/drum/exceptions.py
  custom_model_runner/datarobot_drum/drum/model_metadata.py
  tests/unit/datarobot_drum/model_metadata/test_model_metadata.py
Labels: Ready for Review

#947 [BUZOK-2248] Add rouge to GenAI drop in env
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python39_genai/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements-gpu.txt
Labels: 00 - Ready for Review

#945 AGENT-5438 Add DRUM Nvidia Triton predictor
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/triton_predictor/__init__.py
  custom_model_runner/datarobot_drum/drum/language_predictors/triton_predictor/triton_predictor.py
  custom_model_runner/datarobot_drum/drum/utils/drum_utils.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  public_dropin_gpu_environments/triton_server/proto/setup.py
  public_dropin_gpu_environments/triton_server/proto/src/__init__.py
  public_dropin_gpu_environments/triton_server/proto/src/triton_model_config/__init__.py
  public_dropin_gpu_environments/triton_server/proto/src/triton_model_config/model_config_pb2.py
  public_dropin_gpu_environments/triton_server/start_server.sh
  tests/unit/datarobot_drum/drum/test_args_parser.py
  tests/unit/datarobot_drum/drum/test_drum.py
  tests/unit/datarobot_drum/drum/utils/test_drum_utils.py
Labels: 00 - Ready for Review

#953 AGENT-5461 add Nemo Inference Server drop-in environment
  public_dropin_gpu_environments/nemollm_inference_ms/Dockerfile
  public_dropin_gpu_environments/nemollm_inference_ms/README.md
  public_dropin_gpu_environments/nemollm_inference_ms/__init__.py
  public_dropin_gpu_environments/nemollm_inference_ms/dr_requirements.in
  public_dropin_gpu_environments/nemollm_inference_ms/dr_requirements.txt
  public_dropin_gpu_environments/nemollm_inference_ms/start_server.sh
  public_dropin_gpu_environments/triton_server/start_server.sh
Labels: 00 - Ready for Review

#954 [AGENT-5477] DRUM Hook without an environment variable
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/enum.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: 00 - Ready for Review

#950 [APPLS-1980] Add DR Custom Components package to streamlit base env
  public_custom_application_environments/python39_streamlit/Dockerfile
  public_custom_application_environments/python39_streamlit/README.md
  public_custom_application_environments/python39_streamlit/env_info.json
  public_custom_application_environments/python39_streamlit/packages/dr_components-0.1.3-py3-none-any.whl
Labels: 00 - Ready for Review

#956 [APPLS-1980] Bump Custom App Env version id
  public_custom_application_environments/python39_streamlit/env_info.json
Labels: 00 - Ready for Review

#957 [MMM-16454] bump dmm library to 0.5.0
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: Ready for Review, Auto Merge on Green

#949 [AGENT-5372] Bump version to 1.10.21
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  docker/dropin_env_base_jdk_ubi/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_gpu_environments/triton_server/dr_requirements.txt
Labels: 00 - Ready for Review

#952 [AGENT-5464] Prepare code for new import path in 10.0 version of mlops library
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  tests/functional/test_mlops_monitoring.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#961 [BUZOK-2441] Add required dependencies for Japanese embedding model to GenAI drop-in envs
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python39_genai/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements-gpu.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements-gpu.txt
Labels: 00 - Ready for Review

#962 [AGENT-5523] Hide guard presence if moderations are not enabled
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
Labels: Ready for Review

#951 AGENT-5461 add DRUM proxy to NVIDIA Nemo Inference Microservices (NIM)
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/__init__.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nemo_predictor.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/triton_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  public_dropin_gpu_environments/nemollm_inference_ms/Dockerfile
  public_dropin_gpu_environments/nemollm_inference_ms/start_server.sh
  public_dropin_gpu_environments/triton_server/start_server.sh
  tests/unit/datarobot_drum/drum/test_drum.py
Labels: 00 - Ready for Review
