Repository datarobot/datarobot-user-models, pull requests merged in 2024-04, with the labels that each got.

#959 [NB-5478] Introduced Notebook GPU with Rapids Built-in Custom Environment
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/agent/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/agent/agent.py
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/agent/cgroup_watchers.py
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/agent/requirements-agent.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/common-user-limits.sh
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/extensions/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/extensions/dataframe_formatter.py
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/ipython_config.py
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/jupyter_kernel_gateway_config.py
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/kernel.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements-gpu.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/setup-prompt.sh
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/setup-venv.sh
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/start_server.sh
Labels: Ready for Review

#964 [BUZOK-2294] Remove buzok from owners
  DRCODEOWNERS
Labels: 00 - Ready for Review

#967 [MMM-16670] bump dmm to 0.5.4
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: Ready for Review, Close Jira on Merge

#969 AGENT-5556 update the ONNX example: parse binary response to numpy
  model_templates/triton_onnx_unstructured/client/datarobot-predict.py
  model_templates/triton_onnx_unstructured/client/requirements.txt
Labels: 00 - Ready for Review

#968 [RAPTOR-10612] add log stacktrace when there is exception
  custom_model_runner/datarobot_drum/drum/runtime.py
Labels: 00 - Ready for Review, Close Jira on Merge

#983 [RAPTOR-10663] update drum-builder image
  custom_model_runner/Makefile
  docker/drum_builder/Dockerfile
  docker/drum_builder/README.md
  docker/drum_builder/build_docker.sh
  tools/image-build-utils.sh
Labels: Ready for Review, Close Jira on Merge

#984 AGENT-5588 Add tests for NeMo and Triton predictors / environments
  custom_model_runner/datarobot_drum/resource/drum_server_utils.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  jenkins/test_functional_per_framework.sh
  model_templates/gpu_nemo_textgen/custom_model/custom.py
  model_templates/gpu_nemo_textgen/custom_model/model-metadata.yaml
  tests/conftest.py
  tests/constants.py
  tests/functional/run_integration_tests_in_framework_container.sh
  tests/functional/test_inference_per_framework.py
  tests/testdata/triton_densenet_onnx.bin
  tests/unit/datarobot_drum/drum/test_drum.py
Labels: Ready for Review, Auto Merge when Ready

#996 [AGENT-5443] Finalize vLLM drop-in env
  custom_model_runner/datarobot_drum/drum/gpu_predictors/__init__.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nemo_predictor.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/prediction_server/prediction_server.py
  jenkins/test_functional_per_framework.sh
  model_templates/gpu_vllm_textgen/custom_model/custom.py
  model_templates/gpu_vllm_textgen/custom_model/model-metadata.yaml
  public_dropin_gpu_environments/triton_server/env_info.json
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/README.md
  public_dropin_gpu_environments/vllm/dr_requirements.in
  public_dropin_gpu_environments/vllm/dr_requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/start_server.sh
  tests/functional/integration-helpers.sh
  tests/functional/run_integration_tests_in_framework_container.sh
  tests/functional/test_inference_per_framework.py
  tools/image-build-utils.sh
Labels: Needs Review: Custom Models, 00 - Ready for Review

#986 [RAPTOR-10155] migrate tests to harness
  custom_model_runner/datarobot_drum/drum/resource_monitor.py
  public_dropin_environments/python3_sklearn/requirements.txt
  tests/conftest.py
  tests/functional/test_drum_docker.py
  tests/functional/test_inference.py
  tests/functional/test_other_cases.py
  tests/functional/test_performance_check.py
  tests/functional/test_stats.py
Labels: Ready for Review

#998 [APPLS-2188] Add custom apps streamlit environment to public drop-in directory
  DRCODEOWNERS
  public_custom_application_environments/python39_streamlit/packages/dr_components-0.1.4-py3-none-any.whl
  public_dropin_environments/python39_streamlit/Dockerfile
  public_dropin_environments/python39_streamlit/README.md
  public_dropin_environments/python39_streamlit/env_info.json
  tools/image-build-utils.sh
Labels: 00 - Ready for Review

#995 [NB-5720][NB-5238] Add dependencies to kernels
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
  public_dropin_notebook_environments/r_notebook/Dockerfile
  public_dropin_notebook_environments/r_notebook/env_info.json
Labels: Ready for Review

#999 [APPLS-2188] Add custom apps streamlit environment to public drop-in directory
  DRCODEOWNERS
  model_templates/triton_onnx_unstructured/client/datarobot-predict.py
  public_custom_application_environments/python39_streamlit/packages/dr_components-0.1.4-py3-none-any.whl
  public_dropin_environments/python39_streamlit/Dockerfile
  public_dropin_environments/python39_streamlit/README.md
  public_dropin_environments/python39_streamlit/env_info.json
  tools/image-build-utils.sh
Labels: 00 - Ready for Review, Frozen Branch Merge Request
