Repository datarobot/datarobot-user-models, pull requests merged in 2024-01, with the labels that each got.

#906 [MODEL-12854] CustomTasks Network Access: 5 - bump drum version to 1.10.17
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#907 NB-4920: Porting persistent dependency installations into all custom images
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python311_notebook/setup-prompt.sh
  public_dropin_notebook_environments/python311_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python311_notebook/setup-venv.sh
  public_dropin_notebook_environments/python311_notebook/start_server.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/Dockerfile
  public_dropin_notebook_environments/python38_snowflake_notebook/setup-prompt.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/setup-venv.sh
  public_dropin_notebook_environments/python38_snowflake_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook/Dockerfile
  public_dropin_notebook_environments/python39_notebook/setup-prompt.sh
  public_dropin_notebook_environments/python39_notebook/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook/setup-venv.sh
  public_dropin_notebook_environments/python39_notebook/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu/setup-prompt.sh
  public_dropin_notebook_environments/python39_notebook_gpu/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu/setup-venv.sh
  public_dropin_notebook_environments/python39_notebook_gpu/start_server.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/Dockerfile
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/setup-prompt.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/setup-ssh.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/setup-venv.sh
  public_dropin_notebook_environments/python39_notebook_gpu_tf/start_server.sh
  public_dropin_notebook_environments/r_notebook/Dockerfile
  public_dropin_notebook_environments/r_notebook/setup-prompt.sh
  public_dropin_notebook_environments/r_notebook/setup-ssh.sh
  public_dropin_notebook_environments/r_notebook/setup-venv.sh
  public_dropin_notebook_environments/r_notebook/start_server.sh
Labels: 00 - Ready for Review, Close Jira on Merge

#908 [AGENT-5226] add new field to indicate if a runtime parameter is mandatory
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters_schema.py
  model_templates/python3_sklearn_runtime_params/model-metadata.yaml
  tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py
Labels: 00 - Ready for Review

#909 NB-4920: Increase env versions
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/r_notebook/env_info.json
Labels: 00 - Ready for Review, Auto Merge on Green

#905 [RAPTOR-10206] Add support for extra columns in Python predictor and extend response format
  DEFINE-INFERENCE-MODEL.md
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/julia_predictor/julia_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
  tests/unit/datarobot_drum/drum/test_data_marshalling.py
  tests/unit/datarobot_drum/resource/test_drum_server_utils.py
Labels: 00 - Ready for Review

#911 [RAPTOR-10233] check duplicate runtime parameters
  custom_model_runner/datarobot_drum/runtime_parameters/runtime_parameters.py
  tests/unit/datarobot_drum/runtime_parameters/test_runtime_parameters.py
Labels: 00 - Ready for Review

#912 [AGENT-5216] release DRUM v1.10.18
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#914 [RAPTOR-10266] fix dropin-env-base-jdk:ubi8.8 envs base image
  docker/dropin_env_base_jdk_ubi/Dockerfile
  docker/dropin_env_base_jdk_ubi/README.md
  docker/dropin_env_base_jdk_ubi/build_image.sh
  docker/dropin_env_base_jdk_ubi/requirements.txt
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/env_info.json
Labels: Ready for Review, Close Jira on Merge

#915 [MMM-16000] bump dmm library to 0.3.4
  public_dropin_notebook_environments/python311_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python38_snowflake_notebook/env_info.json
  public_dropin_notebook_environments/python38_snowflake_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook/env_info.json
  public_dropin_notebook_environments/python39_notebook/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/dr_requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#913 [RAPTOR-10263] Rename 'passthrough' to 'extra_model_output'
  DEFINE-INFERENCE-MODEL.md
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: 00 - Ready for Review

#916 [RAPTOR-10283] Fix invalid prediction's response format
  custom_model_runner/datarobot_drum/resource/predict_mixin.py
  tests/unit/datarobot_drum/resource/test_predict_mixin.py
Labels: 00 - Ready for Review

#920 [RAPTOR-10222] Add support for extra model output in R predictor
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/language_predictors/r_predictor/r_predictor.py
  custom_model_runner/datarobot_drum/drum/utils/dataframe.py
  tests/integration/datarobot_drum/drum/language_predictors/test_language_predictors.py
  tests/unit/datarobot_drum/drum/utils/test_dataframe.py
Labels: Ready for Review

#919 [RAPTOR-10296] bump pillow<=10.2.0, update envs, release v1.10.19
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/requirements.txt
  public_dropin_environments/java_codegen/dr_requirements.txt
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311_genai/dr_requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/python39_genai/env_info.json
  public_dropin_environments/python3_keras/dr_requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/dr_requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/dr_requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/dr_requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/dr_requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/dr_requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/dr_requirements.txt
  public_dropin_environments/r_lang/env_info.json
  task_templates/1_transforms/5_python3_image_transform/requirements.txt
  tests/fixtures/custom_task_interface_transform_image/requirements.txt
Labels: Ready for Review
