Repository datarobot/datarobot-user-models, pull requests merged in 2025-06, with the labels that each got.

#1493 [MMM-19604] Bump drum version in the environments.
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.txt
  public_dropin_nim_environments/nim_sidecar/env_info.json
  public_dropin_nim_environments/nim_sidecar/requirements.txt
Labels: Needs Review: Core Modeling, 00 - Ready for Review, Close Jira on Merge

#1494 [RAPTOR-12660] Pass model_dir to moderation library
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  tests/unit/datarobot_drum/drum/adapters/model_adapters/test_python_model_adapter.py
Labels: Ready for Review

#1495 [RAPTOR-12427] Less verbose 422 when reporting monitoring data from chat completions
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
Labels: Ready for Review, Auto Merge on Green, Close Jira on Merge

#1497 [RAPTOR-12695] Bump DRUM Version
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Ready for Review

#1491 [BUZZOK-26080] Bump run_agent and dockerfile for GenAI Agents
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/run_agent.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#1498 [MMM-19667] Fix fokring and instrument OpenAI
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/main.py
  tests/unit/datarobot_drum/drum/test_main.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1503 [MMM-19673] Bump version.
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1511 [RAPTOR-12742] move nim_llama_8b env to example
  example_dropin_environments/nim_llama_8b/.gitkeep
  example_dropin_environments/nim_llama_8b/Dockerfile
  example_dropin_environments/nim_llama_8b/README.md
  example_dropin_environments/nim_llama_8b/env_info.json
  example_dropin_environments/nim_llama_8b/requirements.in
  example_dropin_environments/nim_llama_8b/requirements.txt
  example_dropin_environments/nim_llama_8b/start_server.sh
  model_templates/gpu_nim_textgen/README.md
  public_dropin_nim_environments/README.md
Labels: Ready for Review, Close Jira on Merge, Auto Merge when Ready

#1502 [RAPTOR-12716] add contextUrl to env_info.json
  example_dropin_environments/triton_server/env_info.json
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_nim_environments/nim_sidecar/env_info.json
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
Labels: Ready for Review, Close Jira on Merge, Needs Review: CFX

#1526 Migrate opensource envs to chainguard
  .harness/test_functional_general.yaml
  harness_scripts/functional_general/general_tests_entrypoint.sh
  harness_scripts/functional_general/mlops_reporting_entrypoint.sh
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/Dockerfile
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
Labels: Ready for Review, Needs Review: GenAI Build (Buzok)

#1530 [RAPTOR-13924] Remove python311_genai environment
  .harness/python311_genai_default_pr_input.yaml
  .harness/python311_genai_image_build_default_pr_input.yaml
  .harness/python311_genai_local_default_pr_input.yaml
  .harness/python311_genai_local_image_build_default_pr_input.yaml
  .harness/python311_genai_local_on_pr.yaml
  .harness/python311_genai_local_on_push_master.yaml
  .harness/python311_genai_publish_to_docker_pr_input.yaml
  .harness/python311_genai_reconcile_dependencies_default_pr_input.yaml
  .harness/python311_genai_trivy_scan_pr_input.yaml
  .harness/python311_genai_update_env_version_pr_input.yaml
  DRCODEOWNERS
  jenkins/test_functional_per_framework.sh
  pipelineController.yaml
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/Dockerfile.local
  public_dropin_environments/python311_genai/README.md
  public_dropin_environments/python311_genai/__init__.py
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/fit.sh
  public_dropin_environments/python311_genai/requirements.in
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python311_genai/start_server.sh
  tests/conftest.py
  tests/constants.py
  tests/e2e/conftest.py
  tests/e2e/test_drop_in_environments.py
  tests/functional/test_per_framework.json
Labels: Ready for Review, Close Jira on Merge

#1537 [cherry-pick][RAPTOR-14024] set PYTHONUNBUFFERED=1 in vllm env
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
Labels: Ready for Review

#1534 [CFX-3059] Make tweaks to base image to be sure to use python 3.11 everywhere
  public_dropin_notebook_environments/py311_notebook_dropin.tar.gz
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
Labels: Ready for Review, Close Jira on Merge

#1538 [cherry-pick] Migrate opensource envs to chainguard (#1526)
  .harness/test_functional_general.yaml
  harness_scripts/functional_general/general_tests_entrypoint.sh
  harness_scripts/functional_general/mlops_reporting_entrypoint.sh
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/Dockerfile
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Core Modeling, Ready for Review, Needs Review: GenAI Build (Buzok)

#1542 [RAPTOR-14039] add httpx for testing
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  requirements_for_per_framework_tests.txt
  requirements_test.txt
  requirements_test_unit.txt
Labels: Ready for Review, Close Jira on Merge

#1541 [VUL-11510] Bulk resolved CVEs
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
Labels: 00 - Ready for Review

#1544 [cherry-pick][VUL-11510] Bulk resolved CVEs (#1541)
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
Labels: Ready for Review, Needs Review: GenAI Systems
