Repository datarobot/datarobot-user-models, pull requests merged in 2025-08, with the labels that each got.

#1606 [RAPTOR-14365] Automate env_info version bumps
  .harness/scripts/bump_env_info.sh
Labels: Ready for Review

#1610 [RAPTOR-14360] change tests to use env image published to datarobot dockerhub
  tests/e2e/conftest.py
Labels: Ready for Review, Close Jira on Merge

#1617 [BUZZOK-26495] Upgrade notebook-agent fastapi dependency to resolve starlette vulnernability
  public_dropin_environments/python311_genai_agents/agent/README.md
  public_dropin_environments/python311_genai_agents/agent/requirements-agent.txt
  public_dropin_environments/python311_genai_agents/env_info.json
Labels: 00 - Ready for Review

#1622 [-] (Auto) Bump env_info versions
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Core Modeling, Ready for Review

#1623 [RAPTOR-14453] Regen requirements.txt to fix CVE-2025-8747
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
Labels: Ready for Review

#1627 [BUZZOK-27241] [BUZZOK-27421] Bump requirements in GenAI Agents environment
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
Labels: 00 - Ready for Review, Priority: Blocker

#1631 [MMM-20322] Bump DRUM version.
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1634 [RAPTOR-14453] Regen requirements.txt to fix CVE-2025-8747
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
Labels: Ready for Review, Frozen Branch Merge Request

#1635 [RAPTOR-13851] Bump pytorch to rebuild
  public_dropin_environments/python3_pytorch/env_info.json
Labels: Ready for Review, Frozen Branch Merge Request

#1637 [RAPTOR-13851] pytorch: rebuild requirements to pull in updates
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
Labels: Ready for Review

#1640 [RAPTOR-14353] add client and NIM timeouts
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/root_predictors/prediction_server.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: Ready for Review
