Repository datarobot/datarobot-user-models, pull requests merged in 2025-04, with the labels that each got.

#1369 [CFX-1921] Update python 3.11 base template image's deps
  public_dropin_notebook_environments/py311_notebook_dropin.tar.gz
  public_dropin_notebook_environments/python311_notebook/requirements.txt
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#1372 [RAPTOR-12205] Fixed vllm environment
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/start_server.sh
Labels: Priority: Blocker, Frozen Branch Merge Request

#1378 [RAPTOR-12251] update list of allowed variables
  .harness/env_image_publish.yaml
  .harness/gpu_vllm_default_pr_input.yaml
  .harness/java_codegen_default_pr_input.yaml
  .harness/pythin3_sklearn_default_pr_input.yaml
  .harness/python311_default_pr_input.yaml
  .harness/python311_genai_default_pr_input.yaml
  .harness/python3_keras_default_pr_input.yaml
  .harness/python3_onnx_default_pr_input.yaml
  .harness/python3_pmml_dafault_pr_input.yaml
  .harness/python3_pytorch_default_pr_input.yaml
  .harness/python3_xgboost_default_pr_input.yaml
  .harness/r_lang_default_pr_input.yaml
Labels: Needs Review: Custom Models, 00 - Ready for Review, Close Jira on Merge

#1371 [RAPTOR-12205] Fixed vllm environment
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
Labels: Priority: Blocker

#1381 [CFX-1959] Update venv scripts to check python versions and recreate venv if needed
  public_dropin_notebook_environments/py311_notebook_dropin.tar.gz
  public_dropin_notebook_environments/python311_notebook/setup-venv.sh
  public_dropin_notebook_environments/python311_notebook_base/setup-venv.sh
Labels: Ready for Review, Close Jira on Merge

#1380 [RAPTOR-12253] bump vllm env v0.8.3
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
Labels: 00 - Ready for Review, Close Jira on Merge

#1385 [-] Update README and add example tarball
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/py311_notebook_dropin.tar.gz
Labels: Ready for Review

#1386 [CFX-471] Add the DR githelper binary to base python 3.11 image
  public_dropin_notebook_environments/py311_notebook_dropin.tar.gz
  public_dropin_notebook_environments/python311_notebook/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/start_server.sh
Labels: Ready for Review

#1390 [RAPTOR-12318] copy missing library into R env image
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Core Modeling, Needs Review: Custom Models, 00 - Ready for Review, Auto Merge when Ready

#1392 [MODEL-18996] update custom task select param to allow longer strings
  custom_model_runner/datarobot_drum/drum/model_metadata.py
  tests/unit/datarobot_drum/model_metadata/test_model_metadata_hyperparameters.py
Labels: 00 - Ready for Review

#1393 [AGENT-7138] Scott/agent 7138 models api in drum
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/datarobot_drum/drum/root_predictors/chat_helpers.py
  custom_model_runner/datarobot_drum/drum/root_predictors/predict_mixin.py
  custom_model_runner/datarobot_drum/drum/root_predictors/prediction_server.py
  model_templates/python3_dummy_chat/README.md
  model_templates/python3_dummy_chat/custom.py
  tests/unit/datarobot_drum/drum/conftest.py
  tests/unit/datarobot_drum/drum/helpers.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1395 [MODEL-18996] updated drum version
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review

#1397 [MODEL-18996] update envs
  .harness/python311_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
Labels: Ready for Review

#1405 [RAPTOR-12324] Using logging in DRUM server outputs
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/custom_task_interfaces/custom_task_interface.py
  custom_model_runner/datarobot_drum/drum/adapters/cli/shared/drum_class_label_adapter.py
  custom_model_runner/datarobot_drum/drum/adapters/cli/shared/drum_input_file_adapter.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/java_predictor/java_predictor.py
  custom_model_runner/datarobot_drum/drum/model_metadata.py
  custom_model_runner/datarobot_drum/drum/root_predictors/utils.py
  custom_model_runner/datarobot_drum/drum/runtime.py
  custom_model_runner/datarobot_drum/drum/typeschema_validation.py
  custom_model_runner/datarobot_drum/drum/utils/structured_input_read_utils.py
  public_dropin_environments/r_lang/env_info.json
  task_templates/2_estimators/13_python_credentials_and_internet_access/custom.py
Labels: Ready for Review, Auto Merge when Ready

#1403 [BUZZOK-25627][BUZZOK-25637] Add Python 3.11 Generative AI Agents drop in environment
  DRCODEOWNERS
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/README.md
  public_dropin_environments/python311_genai_agents/agent/README.md
  public_dropin_environments/python311_genai_agents/agent/agent.py
  public_dropin_environments/python311_genai_agents/agent/cgroup_watchers.py
  public_dropin_environments/python311_genai_agents/agent/requirements-agent.txt
  public_dropin_environments/python311_genai_agents/common-user-limits.sh
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/extensions/README.md
  public_dropin_environments/python311_genai_agents/extensions/dataframe_formatter.py
  public_dropin_environments/python311_genai_agents/ipython_config.py
  public_dropin_environments/python311_genai_agents/jupyter_kernel_gateway_config.py
  public_dropin_environments/python311_genai_agents/kernel.json
  public_dropin_environments/python311_genai_agents/requirements-genai.txt
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python311_genai_agents/run_agent.py
  public_dropin_environments/python311_genai_agents/setup-prompt.sh
  public_dropin_environments/python311_genai_agents/setup-ssh.sh
  public_dropin_environments/python311_genai_agents/setup-venv.sh
  public_dropin_environments/python311_genai_agents/sshd_config
  public_dropin_environments/python311_genai_agents/start_server.sh
  public_dropin_environments/python311_genai_agents/start_server_drum.sh
Labels: 00 - Ready for Review, Close Jira on Merge
