Repository datarobot/datarobot-user-models, pull requests merged in 2025-10, with the labels that each got.

#1682 [-] Autobump env_info version IDs
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Core Modeling, Ready for Review

#1683 [BUZZOK-27771] Update public execution env
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
Labels: 00 - Ready for Review

#1685 [RAPTOR-14745] fix command to be properly populated inside container
  tools/image-build-utils.sh
Labels: Ready for Review, Close Jira on Merge

#1692 [MMM-20737] Bump DRUM version for release.
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1693 [RAPTOR-14742] PDIE: All without pip
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/Dockerfile.local
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/Dockerfile
  public_dropin_environments/python311/Dockerfile.local
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/Dockerfile.local
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/Dockerfile.local
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/Dockerfile.local
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/Dockerfile.local
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/Dockerfile.local
  public_dropin_environments/python3_xgboost/env_info.json
Labels: Ready for Review

#1694 [RAPTOR-14666] Bump requirements to fix Keras CVE-2025-9905
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
Labels: Needs Review: Core Modeling, Ready for Review

#1688 [RAPTOR-14422] Drum fast fail when config file has issues
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/exceptions.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
  custom_model_runner/datarobot_drum/drum/main.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1695 [RAPTOR-14807] bump agents env version ID
  public_dropin_environments/python311_genai_agents/env_info.json
Labels: Ready for Review, Close Jira on Merge

#1696 [BUZZOK-27808] PDIE Genai agents: Use system pip
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
Labels: Ready for Review
