Repository datarobot/datarobot-user-models, pull requests merged in 2025-02, with the labels that each got.

#1242 [BUZZOK-24833] Fix issue with pydantic
  public_dropin_gpu_environments/python311_genai/requirements.txt
Labels: 00 - Ready for Review

#1246 [RAPTOR-11936] Add virtual environment to the FIPS-compliant scikit-learn environment
  custom_model_runner/datarobot_drum/drum/drum.py
  public_dropin_environments/python3_sklearn_fedramp_compliant.tar.gz
  public_fips_dropin_environments/__init__.py
  public_fips_dropin_environments/python3_sklearn/Dockerfile
  public_fips_dropin_environments/python3_sklearn/README.md
  public_fips_dropin_environments/python3_sklearn/__init__.py
  public_fips_dropin_environments/python3_sklearn/env_info.json
  public_fips_dropin_environments/python3_sklearn/fit.sh
  public_fips_dropin_environments/python3_sklearn/requirements.txt
  public_fips_dropin_environments/python3_sklearn/start_server.sh
  tests/conftest.py
  tests/constants.py
  tests/e2e/conftest.py
  tests/e2e/test_drop_in_environments.py
  tests/functional/test_mlops_monitoring.py
Labels: 00 - Ready for Review, Auto Merge on Green

#1250 [AGENT-6757] Add NIM EmbedQA
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
  jenkins/test_functional_per_framework.sh
  public_dropin_gpu_environments/nim_embedqa/.gitkeep
  public_dropin_gpu_environments/nim_embedqa/Dockerfile
  public_dropin_gpu_environments/nim_embedqa/env_info.json
  public_dropin_gpu_environments/nim_embedqa/requirements.in
  public_dropin_gpu_environments/nim_embedqa/requirements.txt
  public_dropin_gpu_environments/nim_embedqa/start_server.sh
  tests/conftest.py
  tests/constants.py
  tests/fixtures/nim_embedqa/custom.py
  tests/functional/test_inference_per_framework.py
Labels: Needs Review: Tracking-Agent, 00 - Ready for Review, Close Jira on Merge

#1247 [AGENT-6756 ] Adds Qwen 7b NIM
  public_dropin_gpu_environments/nim_qwen_7b/.gitkeep
  public_dropin_gpu_environments/nim_qwen_7b/Dockerfile
  public_dropin_gpu_environments/nim_qwen_7b/env_info.json
  public_dropin_gpu_environments/nim_qwen_7b/requirements.in
  public_dropin_gpu_environments/nim_qwen_7b/requirements.txt
  public_dropin_gpu_environments/nim_qwen_7b/start_server.sh
Labels: Needs Review: Custom Models, 00 - Ready for Review, Close Jira on Merge

#1255 [CFX-1527] Update base notebook image for FIPS compliance as well as others that are purely examples
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_tf/sshd_config
  public_dropin_notebook_environments/r_notebook/sshd_config
Labels: Ready for Review

#1256 Revert "[CFX-1527] Update base notebook image for FIPS compliance as well as others that are purely examples (#1255)"
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_tf/sshd_config
  public_dropin_notebook_environments/r_notebook/sshd_config
Labels: Ready for Review, Priority: Blocker

#1257 [RAPTOR-11951] Remove non-required tools from the FIPS-compliant sklearn environment
  public_fips_dropin_environments/python3_sklearn/Dockerfile
Labels: 00 - Ready for Review, Close Jira on Merge

#1258 [RAPTOR-11952] Remove a context file that was added by mistake
  public_dropin_environments/python3_sklearn_fedramp_compliant.tar.gz
Labels: 00 - Ready for Review, Close Jira on Merge

#1259 [RAPTOR-11954] Fix the default image tag in the environment build and publish Harness pipeline
  .harness/env_image_publish.yaml
Labels: 00 - Ready for Review, Close Jira on Merge

#1264 [CFX-1527] Update base notebook image for FIPS compliance as well as others that are purely examples
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/sshd_config
  public_dropin_notebook_environments/python39_notebook_gpu_tf/sshd_config
  public_dropin_notebook_environments/r_notebook/sshd_config
Labels: Ready for Review

#1248 AGENT-6712 extend NimPredictor to support multi-container deployments
  custom_model_runner/datarobot_drum/drum/args_parser.py
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
  custom_model_runner/datarobot_drum/drum/root_predictors/drum_server_utils.py
  custom_model_runner/datarobot_drum/drum/root_predictors/predict_mixin.py
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_pipeline.json.j2
  custom_model_runner/datarobot_drum/resource/pipelines/prediction_server_pipeline.json.j2
  jenkins/test_functional_per_framework.sh
  public_dropin_gpu_environments/nim_sidecar/Dockerfile
  public_dropin_gpu_environments/nim_sidecar/env_info.json
  public_dropin_gpu_environments/nim_sidecar/requirements.in
  public_dropin_gpu_environments/nim_sidecar/requirements.txt
  public_dropin_gpu_environments/nim_sidecar/start_server.sh
  tests/conftest.py
  tests/constants.py
  tests/functional/gpu_nim_sidecar/docker-compose.yaml
  tests/functional/test_inference_per_framework.py
  tests/unit/datarobot_drum/drum/test_drum.py
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1262 Add requirements.in for public dropin environments
  public_dropin_environments/python311_genai/requirements.in
  public_dropin_environments/python3_keras/requirements.in
  public_dropin_environments/python3_onnx/requirements.in
  public_dropin_environments/python3_pmml/requirements.in
  public_dropin_environments/python3_pytorch/requirements.in
  public_dropin_environments/python3_sklearn/requirements.in
  public_dropin_environments/python3_xgboost/requirements.in
  public_dropin_environments/r_lang/requirements.in
Labels: 00 - Ready for Review, Needs Review: GenAI Build (Buzok)

#1271 [AGENT-6717] extend DRUM API to proxy requests
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/root_predictors/prediction_server.py
  tests/functional/test_inference_per_framework.py
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1269 [RAPTOR-11970] Add FIPS-compliant pytroch drop-in environment
  .harness/fips_python3_pytorch_default_pr_input.yaml
  custom_model_runner/datarobot_drum/drum/artifact_predictors/torch_predictor.py
  model_templates/python3_pytorch/torch_reg.pth
  model_templates/python3_pytorch_multiclass/custom.py
  public_fips_dropin_environments/python3_pytorch/Dockerfile
  public_fips_dropin_environments/python3_pytorch/README.md
  public_fips_dropin_environments/python3_pytorch/__init__.py
  public_fips_dropin_environments/python3_pytorch/env_info.json
  public_fips_dropin_environments/python3_pytorch/fit.sh
  public_fips_dropin_environments/python3_pytorch/requirements.in
  public_fips_dropin_environments/python3_pytorch/requirements.txt
  public_fips_dropin_environments/python3_pytorch/start_server.sh
  task_templates/3_pipelines/13_python3_pytorch_multiclass/custom.py
  tests/fixtures/custom_task_interface_pytorch_binary/custom.py
  tests/fixtures/custom_task_interface_pytorch_multiclass/custom.py
  tests/fixtures/drop_in_model_artifacts/PyTorch.py
  tests/fixtures/drop_in_model_artifacts/torch_bin.pth
  tests/fixtures/drop_in_model_artifacts/torch_multi.pth
  tests/fixtures/drop_in_model_artifacts/torch_reg.pth
Labels: 00 - Ready for Review

#1278 [CFX-1596] Update Notebooks custom image templates README's for clarity/ease of copying command
  public_dropin_notebook_environments/README.md
  public_dropin_notebook_environments/python311_notebook/README.md
  public_dropin_notebook_environments/python311_notebook_base/README.md
  public_dropin_notebook_environments/python39_notebook_gpu/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/README.md
  public_dropin_notebook_environments/python39_notebook_gpu_tf/README.md
  public_dropin_notebook_environments/r_notebook/README.md
Labels: Ready for Review, Close Jira on Merge

#1265 [AGENT-6735] Update vLLM env
  public_dropin_gpu_environments/triton_server/.gitkeep
  public_dropin_gpu_environments/triton_server/Dockerfile
  public_dropin_gpu_environments/triton_server/env_info.json
  public_dropin_gpu_environments/triton_server/requirements.txt
  public_dropin_gpu_environments/vllm/.gitkeep
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.txt
  public_dropin_gpu_environments/vllm/start_server.sh
Labels: 00 - Ready for Review, Close Jira on Merge, Auto Merge when Ready

#1273 Cleanup vllm multi-gpu handling
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#1274 Move NIM to their own folder
  DRCODEOWNERS
  jenkins/test_functional_per_framework.sh
  model_templates/gpu_nim_textgen/README.md
  public_dropin_gpu_environments/README.md
  public_dropin_nim_environments/README.md
  public_dropin_nim_environments/nim_embedqa/.gitkeep
  public_dropin_nim_environments/nim_embedqa/Dockerfile
  public_dropin_nim_environments/nim_embedqa/env_info.json
  public_dropin_nim_environments/nim_embedqa/requirements.in
  public_dropin_nim_environments/nim_embedqa/requirements.txt
  public_dropin_nim_environments/nim_embedqa/start_server.sh
  public_dropin_nim_environments/nim_llama_70b/.gitkeep
  public_dropin_nim_environments/nim_llama_70b/Dockerfile
  public_dropin_nim_environments/nim_llama_70b/README.md
  public_dropin_nim_environments/nim_llama_70b/env_info.json
  public_dropin_nim_environments/nim_llama_70b/requirements.in
  public_dropin_nim_environments/nim_llama_70b/requirements.txt
  public_dropin_nim_environments/nim_llama_70b/start_server.sh
  public_dropin_nim_environments/nim_llama_8b/.gitkeep
  public_dropin_nim_environments/nim_llama_8b/Dockerfile
  public_dropin_nim_environments/nim_llama_8b/README.md
  public_dropin_nim_environments/nim_llama_8b/env_info.json
  public_dropin_nim_environments/nim_llama_8b/requirements.in
  public_dropin_nim_environments/nim_llama_8b/requirements.txt
  public_dropin_nim_environments/nim_llama_8b/start_server.sh
  public_dropin_nim_environments/nim_qwen_7b/.gitkeep
  public_dropin_nim_environments/nim_qwen_7b/Dockerfile
  public_dropin_nim_environments/nim_qwen_7b/env_info.json
  public_dropin_nim_environments/nim_qwen_7b/requirements.in
  public_dropin_nim_environments/nim_qwen_7b/requirements.txt
  public_dropin_nim_environments/nim_qwen_7b/start_server.sh
  public_dropin_nim_environments/nim_sidecar/Dockerfile
  public_dropin_nim_environments/nim_sidecar/env_info.json
  public_dropin_nim_environments/nim_sidecar/requirements.in
  public_dropin_nim_environments/nim_sidecar/requirements.txt
  public_dropin_nim_environments/nim_sidecar/start_server.sh
  tests/constants.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#1279 [AGENT-6734] Revert the check of training data available
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
Labels: Ready for Review

#1283 Setup reconcile dependencies pipeline for sandbox environment
  public_dropin_environments_sandbox/.harness/branch.yaml
  public_dropin_environments_sandbox/.harness/python3_keras.yaml
  public_dropin_environments_sandbox/.harness/reconcile_dependencies_template_0.0.0.yaml
  public_dropin_environments_sandbox/python3_keras/requirements.txt
  tools/reconcile_dependencies.sh
Labels: Ready for Review

#1284 [RAPTOR-11972] Add FIPS-compliant GenAI drop-in environment
  public_fips_dropin_environments/python311_genai/Dockerfile
  public_fips_dropin_environments/python311_genai/README.md
  public_fips_dropin_environments/python311_genai/__init__.py
  public_fips_dropin_environments/python311_genai/env_info.json
  public_fips_dropin_environments/python311_genai/fit.sh
  public_fips_dropin_environments/python311_genai/requirements.in
  public_fips_dropin_environments/python311_genai/requirements.txt
  public_fips_dropin_environments/python311_genai/start_server.sh
  tests/e2e/conftest.py
  tests/e2e/test_drop_in_environments.py
Labels: 00 - Ready for Review

#1287 [RAPTOR-11992] Fix Harness input sets for creating latest drop-in environments
  .harness/java_codegen_image_build_default_pr_input.yaml
  .harness/python311_genai_image_build_default_pr_input.yaml
  .harness/python3_keras_image_build_default_pr_input.yaml
  .harness/python3_onnx_image_build_default_pr_input.yaml
  .harness/python3_pmml_image_build_default_pr_input.yaml
  .harness/python3_pytorch_image_build_default_pr_input.yaml
  .harness/python3_sklearn_image_build_default_pr_input.yaml
  .harness/python3_xgboost_image_build_default_pr_input.yaml
  .harness/r_lang_image_build_default_pr_input.yaml
Labels: Ready for Review, Close Jira on Merge

#1286 [RAPTOR-11991] Add Harness resources for GenAI FIPS-compliant drop-in environment
  .harness/fips_python311_genai_default_pr_input.yaml
  .harness/fips_python311_genai_image_build_default_pr_input.yaml
Labels: Ready for Review, Close Jira on Merge

#1288 [RAPTOR-11993] Add missing Harness input-sets for creating latest FIPS-compliant drop-in environments
  .harness/fips_python311_image_build_default_pr_input.yaml
  .harness/fips_python3_keras_image_build_default_pr_input.yaml
  .harness/fips_python3_onnx_image_build_default_pr_input.yaml
  .harness/fips_python3_pytorch_image_build_default_pr_input.yaml
  .harness/fips_python3_sklearn_image_build_default_pr_input.yaml
  .harness/fips_python3_xgboost_image_build_default_pr_input.yaml
Labels: Needs Review: Custom Models, 00 - Ready for Review

#1285 [AGENT-6788] Prompt could be in the form of list
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
Labels: Ready for Review

#1291 [RAPTOR-12010] Fix the memory configuration in FIPS-compliant keras drop-in env functional test
  tests/e2e/test_drop_in_environments.py
Labels: 00 - Ready for Review, Auto Merge on Green, Priority: Blocker

#1290 [RAPTOR-12011] Rename experimental to DataRobot in the FIPS-compliant python311 name
  public_fips_dropin_environments/python311/env_info.json
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#1294 [AGENT-6541 AGENT-6865] Allow user to override parts of nim predictor logic
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/aws_helper.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/utils.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
  custom_model_runner/datarobot_drum/drum/root_predictors/prediction_server.py
  jenkins/test_functional_per_framework.sh
  public_dropin_nim_environments/nim_sidecar/requirements.txt
  tests/conftest.py
  tests/fixtures/nim_embedqa/.server_ready
  tests/fixtures/nim_jailbreak/custom.py
  tests/functional/gpu_nim_sidecar/docker-compose.yaml
  tests/functional/test_inference_per_framework.py
Labels: 00 - Ready for Review, Close Jira on Merge, Auto Merge when Ready

#1296 create publish to docker pipeline
  public_dropin_environments_sandbox/.harness/publish_to_docker.yaml
  public_dropin_environments_sandbox/.harness/publish_to_docker_python3_keras.yaml
Labels: 00 - Ready for Review

#1295 Create daily trivy security scan pipeline
  public_dropin_environments_sandbox/.harness/trivy_scan.yaml
  public_dropin_environments_sandbox/.harness/trivy_scan_python3_keras.yaml
Labels: 00 - Ready for Review

#1301 Bump nim_sidecar env version
  public_dropin_nim_environments/nim_sidecar/env_info.json
Labels: 00 - Ready for Review, Priority: Blocker, Auto Merge when Ready

#1302 [AGENT-6869 AGENT-6882] Major refactoring of GPU functional tests
  .gitignore
  DRCODEOWNERS
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  jenkins/test_functional_per_framework.sh
  public_dropin_nim_environments/README.md
  public_dropin_nim_environments/nim_embedqa/.gitkeep
  public_dropin_nim_environments/nim_embedqa/Dockerfile
  public_dropin_nim_environments/nim_embedqa/env_info.json
  public_dropin_nim_environments/nim_embedqa/requirements.in
  public_dropin_nim_environments/nim_embedqa/requirements.txt
  public_dropin_nim_environments/nim_embedqa/start_server.sh
  public_dropin_nim_environments/nim_llama_70b/.gitkeep
  public_dropin_nim_environments/nim_llama_70b/Dockerfile
  public_dropin_nim_environments/nim_llama_70b/README.md
  public_dropin_nim_environments/nim_llama_70b/env_info.json
  public_dropin_nim_environments/nim_llama_70b/requirements.in
  public_dropin_nim_environments/nim_llama_70b/requirements.txt
  public_dropin_nim_environments/nim_llama_70b/start_server.sh
  public_dropin_nim_environments/nim_qwen_7b/.gitkeep
  public_dropin_nim_environments/nim_qwen_7b/Dockerfile
  public_dropin_nim_environments/nim_qwen_7b/env_info.json
  public_dropin_nim_environments/nim_qwen_7b/requirements.in
  public_dropin_nim_environments/nim_qwen_7b/requirements.txt
  public_dropin_nim_environments/nim_qwen_7b/start_server.sh
  public_dropin_nim_environments/nim_sidecar/Dockerfile
  public_dropin_nim_environments/nim_sidecar/env_info.json
  public_dropin_nim_environments/nim_sidecar/requirements.txt
  tests/conftest.py
  tests/constants.py
  tests/fixtures/nim_embedqa/.server_ready
  tests/fixtures/nim_embedqa/custom.py
  tests/functional/run_integration_tests_in_framework_container.sh
  tests/functional/test_inference_gpu_predictors.py
  tests/functional/test_inference_per_framework.py
Labels: Needs Review: Core Modeling, Needs Review: Tracking-Agent, 00 - Ready for Review, Close Jira on Merge, Auto Merge when Ready
