Repository datarobot/datarobot-user-models, pull requests merged in 2025-07, with the labels that each got.

#1545 [BUZZOK-26626] [BUZZOK-26641] Update requirements and run_agent for GenAI Agents
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python311_genai_agents/run_agent.py
Labels: 00 - Ready for Review

#1547 [RAPTOR-14067] bump drum and mlops in all the envs (#1546)
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.txt
Labels: Ready for Review, Needs Review: GenAI Systems

#1554 [RAPTOR-14113] bump drum in VLLM env to 1.16.20
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.txt
Labels: Ready for Review, Auto Merge when Ready

#1555 [VUL-14360][VUL-9146][VUL-11518][VUL-11519] Fixing CVE-2025-48379, CVE-2024-47081, CVE-2025-50181 and CVE-2025-50182
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
Labels: 00 - Ready for Review

#1557 [CFX-3128] Notebooks base image - Bump to latest drgithelper binary
  public_dropin_notebook_environments/py311_notebook_dropin.tar.gz
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
Labels: Ready for Review

#1561 [RAPTOR-14144] Bump moderation lib version
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
Labels: Ready for Review, Priority: Blocker

#1564 [BUZZOK-26743] Update environment with latest CVE and critical bugfixes for tracing
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python311_genai_agents/run_agent.py
Labels: 00 - Ready for Review, Auto Merge on Green

#1566 [BUZZOK-26753] [BUZZOK-26713] Fix llama-index CVE in genai agents environment
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
Labels: 00 - Ready for Review, Needs Review: GenAI Build (Buzok)

#1567 [cherry-pick] [BUZZOK-26753] [BUZZOK-26713] Fix llama-index CVE in genai agents environment
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
Labels: 00 - Ready for Review, Frozen Branch Merge Request

#1571 [RAPTOR-14178] improve harness images build pipeline
  .harness/reusable_build_images.yaml
Labels: Ready for Review, Close Jira on Merge

#1576 [BUZZOK-26787] Force remove outdated asyncio package from container, it breaks codespaces
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/env_info.json
Labels: 00 - Ready for Review, Priority: Blocker

#1575 [cherry-pick] [BUZZOK-26787] Force remove outdated asyncio package from container, it breaks codespaces
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/env_info.json
Labels: 00 - Ready for Review, Priority: Blocker, Frozen Branch Merge Request

#1574 [RAPTOR-14205] update pipeline to a new reconcile template version to show status in PR
  .harness/test_functional_by_framework_multisteps.yaml
Labels: Ready for Review, Close Jira on Merge, Needs Review: GenAI Systems

#1581 [cherry-pick][RAPTOR-14205] update pipeline to a new reconcile template version to show status in PR
  .harness/test_functional_by_framework_multisteps.yaml
Labels: Ready for Review

#1583 [RAPTOR-14207] change pipeline identifier to prettify status message
  .harness/reusable_build_images.yaml
  .harness/test_functional_by_framework_multisteps.yaml
Labels: Ready for Review, Close Jira on Merge

#1580 [RAPTOR-14179] Bump env ver ids for CVE-2025-6069
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Frozen Branch Merge Request

#1586 [cherry-pick][RAPTOR-14202] Fix annoylib compilation
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/env_info.json
Labels: Ready for Review, Priority: Blocker, Frozen Branch Merge Request

#1585 [RAPTOR-14202] Fix annoylib compilation
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/env_info.json
Labels: Ready for Review, Priority: Blocker

#1594 [RAPTOR-14249] Remove python3 PMML dropin env
  .harness/dropin_env_base.yaml
  .harness/python3_pmml_dafault_pr_input.yaml
  .harness/python3_pmml_image_build_default_pr_input.yaml
  .harness/python3_pmml_local_default_pr_input.yaml
  .harness/python3_pmml_local_image_build_default_pr_input.yaml
  .harness/python3_pmml_local_on_pr.yaml
  .harness/python3_pmml_local_on_push_master.yaml
  .harness/python3_pmml_publish_to_docker_pr_input.yaml
  .harness/python3_pmml_reconcile_dependencies_default_pr_input.yaml
  .harness/python3_pmml_trivy_scan_pr_input.yaml
  .harness/python3_pmml_update_env_version_pr_input.yaml
  DEFINE-INFERENCE-MODEL.md
  DRCODEOWNERS
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/artifact_predictors/pmml_predictor.py
  custom_model_runner/datarobot_drum/drum/enum.py
  dependbot.yml
  jenkins/test_functional_per_framework.sh
  model_templates/README.md
  model_templates/python3_pmml/README.md
  model_templates/python3_pmml/custom.py
  model_templates/python3_pmml/iris_bin.pmml
  pipelineController.yaml
  public_dropin_environments/README.md
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/Dockerfile.local
  public_dropin_environments/python3_pmml/README.md
  public_dropin_environments/python3_pmml/__init__.py
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.in
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pmml/start_server.sh
  tests/conftest.py
  tests/constants.py
  tests/e2e/conftest.py
  tests/e2e/test_inference_model_templates.py
  tests/fixtures/artifacts.py
  tests/fixtures/drop_in_model_artifacts/iris_bin.pmml
  tests/fixtures/drop_in_model_artifacts/iris_multi.pmml
  tests/fixtures/drop_in_model_artifacts/iris_reg.pmml
  tests/functional/test_inference_per_framework.py
  tests/functional/test_per_framework.json
  tests/unit/datarobot_drum/drum/artifact_predictors/test_artifact_predictors.py
Labels: Ready for Review

#1595 [BUZZOK-26844] Remove drum server from everywhere in genai_agents image, replace with drum inline predictor
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python311_genai_agents/run_agent.py
Labels: 00 - Ready for Review

#1596 [APP-4435] Fix CVEs in Apps Dockefiles
  public_dropin_apps_environments/python312_apps/Dockerfile
  public_dropin_apps_environments/python312_apps/env_info.json
Labels: 00 - Ready for Review, Priority: Blocker, Frozen Branch Merge Request

#1604 [RAPTOR-14304] Bump python311_genai_agents to fix CVEs
  public_dropin_environments/python311_genai_agents/env_info.json
Labels: Ready for Review
