Repository datarobot/datarobot-user-models, pull requests merged in 2025-03, with the labels that each got.

#1304 [RAPTOR-12019] Add FIPS-compliant r_lang drop-in environment
  .harness/fips_r_lang_default_pr_input.yaml
  .harness/fips_r_lang_image_build_default_pr_input.yaml
  README.md
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  public_fips_dropin_environments/r_lang/Dockerfile
  public_fips_dropin_environments/r_lang/README.md
  public_fips_dropin_environments/r_lang/ensure_sh_shebang.py
  public_fips_dropin_environments/r_lang/env_info.json
  public_fips_dropin_environments/r_lang/fit.sh
  public_fips_dropin_environments/r_lang/requirements.in
  public_fips_dropin_environments/r_lang/requirements.txt
  public_fips_dropin_environments/r_lang/start_server.sh
  tests/e2e/conftest.py
  tests/e2e/test_drop_in_environments.py
  tests/functional/run_integration_tests_in_framework_container.sh
  tests/unit/datarobot_drum/model_metadata/test_model_metadata.py
Labels: Ready for Review

#1311 [RAPTOR-12052] Fix the memory in R drop-in env functional test
  tests/e2e/test_drop_in_environments.py
Labels: Needs Review: Custom Models, Ready for Review, Priority: Blocker, Close Jira on Merge

#1309 [RAPTOR-12050] Copy the FIPS-compliant python3_pmml to the public_dropin_environments folder
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.in
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pmml/start_server.sh
Labels: Ready for Review, Close Jira on Merge

#1314 [-] Move Applications environments to a separate directory
  public_dropin_apps_environments/python312_apps/Dockerfile
  public_dropin_apps_environments/python312_apps/README.md
  public_dropin_apps_environments/python312_apps/__init__.py
  public_dropin_apps_environments/python312_apps/env_info.json
  public_dropin_apps_environments/python39_streamlit/Dockerfile
  public_dropin_apps_environments/python39_streamlit/README.md
  public_dropin_apps_environments/python39_streamlit/env_info.json
  public_dropin_environments/python39_streamlit/packages/dr_components-0.1.4-py3-none-any.whl
Labels: Ready for Review

#1319 python3 keras reconcile dependencies
  .harness/python3_keras_reconcile_dependencies_default_pr_input.yaml
  .harness/reconcile_dependencies.yaml
  public_dropin_environments/python3_keras/requirements.txt
Labels: Needs Review: Custom Models, 00 - Ready for Review

#1324 python311 genai reconcile dependencies
  .harness/python311_genai_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/python311_genai/requirements.txt
Labels: 00 - Ready for Review, Needs Review: GenAI Build (Buzok)

#1317 java codegen publish_to_docker and trivy_scan
  .harness/java_codegen_publish_to_docker_pr_input.yaml
  .harness/java_codegen_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1325 python3_pmml input sets for publish_to_docker and trivy_scan
  .harness/python3_pmml_publish_to_docker_pr_input.yaml
  .harness/python3_pmml_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1327 python3_sklearn input sets for publish_to_docker and trivy_scan
  .harness/python3_sklearn_publish_to_docker_pr_input.yaml
  .harness/python3_sklearn_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1328 python3_xgboost input sets for publish_to_docker and trivy_scan
  .harness/python3_xgboost_publish_to_docker_pr_input.yaml
  .harness/python3_xgboost_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1326 python3_pytorch input sets for publish_to_docker and trivy_scan
  .harness/python3_pytorch_publish_to_docker_pr_input.yaml
  .harness/python3_pytorch_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1329 r_lang input sets for publish_to_docker and trivy_scan
  .harness/r_lang_publish_to_docker_pr_input.yaml
  .harness/r_lang_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1334 python3 xgboost reconcile dependencies
  .harness/python3_xgboost_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/python3_xgboost/requirements.txt
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1333 python3 sklearn reconcile dependencies
  .harness/python3_sklearn_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/python3_sklearn/requirements.txt
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1335 r lang reconcile dependencies
  .harness/r_lang_reconcile_dependencies_default_pr_input.yaml
  .harness/reconcile_dependencies.yaml
  public_dropin_environments/r_lang/requirements.txt
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1332 move publish_to_docker and trivy_scan to .harness
  .harness/publish_to_docker.yaml
  .harness/trivy_scan.yaml
Labels: 00 - Ready for Review

#1323 python311_genai input sets for publish_to_docker and trivy_scan
  .harness/python311_genai_publish_to_docker_pr_input.yaml
  .harness/python311_genai_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1322 python3 onnx input sets for publish_to_docker and trivy_scan
  .harness/python3_onnx_publish_to_docker_pr_input.yaml
  .harness/python3_onnx_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1318 python3 keras publish_to_docker and trivy_scan
  .harness/python3_keras_publish_to_docker_pr_input.yaml
  .harness/python3_keras_trivy_scan_pr_input.yaml
Labels: 00 - Ready for Review

#1330 python3 pmml reconcile dependencies
  .harness/python3_pmml_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/python3_pmml/requirements.txt
Labels: Needs Review: Core Modeling, 00 - Ready for Review

#1321 python3 onnx reconcile dependencies
  .harness/python3_onnx_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/python3_onnx/requirements.txt
Labels: 00 - Ready for Review

#1320 java codegen reconcile dependencies
  .harness/java_codegen_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/java_codegen/requirements.txt
Labels: 00 - Ready for Review

#1337 [RAPTOR-12061] Remove inline comments from the drop-in environment requirements files
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python3_pytorch/requirements.txt
Labels: Needs Review: Custom Models, 00 - Ready for Review, Auto Merge on Green

#1331 python3 pytorch reconcile dependencies
  .harness/python3_pytorch_reconcile_dependencies_default_pr_input.yaml
  public_dropin_environments/python3_pytorch/requirements.txt
Labels: 00 - Ready for Review

#1336 [RAPTOR-12038] Add support for building drop-in environment for local development
  public_dropin_environments/java_codegen/Dockerfile.local
  public_dropin_environments/python311/Dockerfile.local
  public_dropin_environments/python311_genai/Dockerfile.local
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/Dockerfile.local
  public_dropin_environments/python3_onnx/Dockerfile.local
  public_dropin_environments/python3_pmml/Dockerfile.local
  public_dropin_environments/python3_pytorch/Dockerfile.local
  public_dropin_environments/python3_sklearn/Dockerfile.local
  public_dropin_environments/python3_xgboost/Dockerfile.local
  public_dropin_environments/r_lang/Dockerfile.local
Labels: Ready for Review, Auto Merge on Green

#1338 update target_branch of publish_to_docker Input Sets
  .harness/java_codegen_publish_to_docker_pr_input.yaml
  .harness/python311_genai_publish_to_docker_pr_input.yaml
  .harness/python3_keras_publish_to_docker_pr_input.yaml
  .harness/python3_onnx_publish_to_docker_pr_input.yaml
  .harness/python3_pmml_publish_to_docker_pr_input.yaml
  .harness/python3_pytorch_publish_to_docker_pr_input.yaml
  .harness/python3_sklearn_publish_to_docker_pr_input.yaml
  .harness/python3_xgboost_publish_to_docker_pr_input.yaml
  .harness/r_lang_publish_to_docker_pr_input.yaml
Labels: 00 - Ready for Review

#1339 add environment argument to env_version_update.py script
  tools/env_version_update.py
Labels: 00 - Ready for Review

#1342 update environment version pipeline
  .harness/java_codegen_update_env_version_pr_input.yaml
  .harness/python311_genai_update_env_version_pr_input.yaml
  .harness/python3_keras_update_env_version_pr_input.yaml
  .harness/python3_onnx_update_env_version_pr_input.yaml
  .harness/python3_pmml_update_env_version_pr_input.yaml
  .harness/python3_pytorch_update_env_version_pr_input.yaml
  .harness/python3_sklearn_update_env_version_pr_input.yaml
  .harness/python3_xgboost_update_env_version_pr_input.yaml
  .harness/r_lang_update_env_version_pr_input.yaml
  .harness/update_env_version.yaml
Labels: 00 - Ready for Review

#1344 [RAPTOR-12072] Update environment versions to enable proper dependencies display in the description
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Needs Review: GenAI Build (Buzok)

#1316 AGENT-6925 Do not hardcode model name in DRUM
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  public_dropin_nim_environments/nim_sidecar/requirements.txt
  tests/functional/run_integration_tests_in_framework_container.sh
  tests/functional/test_inference_gpu_predictors.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#1347 [RAPTOR-12084] Use 'exec' in Dockerfile ENTRYPOINT for better signal handling and efficiency
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/Dockerfile.local
  public_dropin_environments/python311/Dockerfile
  public_dropin_environments/python311/Dockerfile.local
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/Dockerfile.local
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/Dockerfile.local
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/Dockerfile.local
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/Dockerfile.local
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/Dockerfile.local
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/Dockerfile.local
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/Dockerfile.local
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/Dockerfile.local
Labels: Ready for Review

#1350 [RAPTOR-12104] Solve scanning error of AsymmetricPrivateKey in _python_rsa.cpython-311.pyc
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/Dockerfile
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review

#1346 [AGENT-6917] return error if model has no chat support
  custom_model_runner/datarobot_drum/drum/root_predictors/predict_mixin.py
  custom_model_runner/datarobot_drum/drum/server.py
  tests/unit/datarobot_drum/drum/conftest.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: 00 - Ready for Review

#1353 [AGENT-6954] Ensure only TextGen models have chat capability
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  requirements_test_unit.txt
  tests/unit/datarobot_drum/drum/gpu_predictors/test_gpu_predictors.py
Labels: Ready for Review, Auto Merge on Green, Close Jira on Merge

#1356 AGENT-6954 Bump drum to 1.16.10
  custom_model_runner/CHANGELOG.md
  public_dropin_nim_environments/nim_sidecar/env_info.json
  public_dropin_nim_environments/nim_sidecar/requirements.txt
Labels: 00 - Ready for Review

#1358 AGENT-6954 Bump drum to 1.16.10
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Auto Merge on Green

#1360 [AGENT-7023] Default to 10 HTTP workers for nim sidecar container
  public_dropin_nim_environments/nim_sidecar/Dockerfile
  public_dropin_nim_environments/nim_sidecar/env_info.json
  tests/functional/test_inference_gpu_predictors.py
Labels: Ready for Review, Close Jira on Merge, Auto Merge when Ready

#1355 [AGENT-6982] More accurate NIM functional tests
  custom_model_runner/datarobot_drum/drum/root_predictors/drum_server_utils.py
  tests/functional/test_inference_gpu_predictors.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1363 [11.0] [AGENT-7023] Default to 10 HTTP workers for nim sidecar container
  public_dropin_nim_environments/nim_sidecar/Dockerfile
  public_dropin_nim_environments/nim_sidecar/env_info.json
  tests/functional/test_inference_gpu_predictors.py
Labels: Ready for Review, Frozen Branch Merge Request

#1352 [RAPTOR-12062] Add Harness pipeline support for testing local development drop-in environment Dockerfiles
  .harness/env_image_publish.yaml
  .harness/java_codegen_local_default_pr_input.yaml
  .harness/java_codegen_local_image_build_default_pr_input.yaml
  .harness/java_codegen_local_on_pr.yaml
  .harness/java_codegen_local_on_push_master.yaml
  .harness/python311_genai_local_default_pr_input.yaml
  .harness/python311_genai_local_image_build_default_pr_input.yaml
  .harness/python311_genai_local_on_pr.yaml
  .harness/python311_genai_local_on_push_master.yaml
  .harness/python311_local_default_pr_input.yaml
  .harness/python311_local_image_build_default_pr_input.yaml
  .harness/python311_local_on_pr.yaml
  .harness/python311_local_on_push_master.yaml
  .harness/python3_keras_local_default_pr_input.yaml
  .harness/python3_keras_local_image_build_default_pr_input.yaml
  .harness/python3_keras_local_on_pr.yaml
  .harness/python3_keras_local_on_push_master.yaml
  .harness/python3_onnx_local_default_pr_input.yaml
  .harness/python3_onnx_local_image_build_default_pr_input.yaml
  .harness/python3_onnx_local_on_pr.yaml
  .harness/python3_onnx_local_on_push_master.yaml
  .harness/python3_pmml_local_default_pr_input.yaml
  .harness/python3_pmml_local_image_build_default_pr_input.yaml
  .harness/python3_pmml_local_on_pr.yaml
  .harness/python3_pmml_local_on_push_master.yaml
  .harness/python3_pytorch_local_default_pr_input.yaml
  .harness/python3_pytorch_local_image_build_default_pr_input.yaml
  .harness/python3_pytorch_local_on_pr.yaml
  .harness/python3_pytorch_local_on_push_master.yaml
  .harness/python3_sklearn_local_default_pr_input.yaml
  .harness/python3_sklearn_local_image_build_default_pr_input.yaml
  .harness/python3_sklearn_local_on_pr.yaml
  .harness/python3_sklearn_local_on_push_master.yaml
  .harness/python3_xgboost_local_default_pr_input.yaml
  .harness/python3_xgboost_local_image_build_default_pr_input.yaml
  .harness/python3_xgboost_local_on_pr.yaml
  .harness/python3_xgboost_local_on_push_master.yaml
  .harness/r_lang_local_default_pr_input.yaml
  .harness/r_lang_local_image_build_default_pr_input.yaml
  .harness/r_lang_local_on_pr.yaml
  .harness/r_lang_local_on_push_master.yaml
  .harness/test_functional_by_framework.yaml
  harness_scripts/functional_by_framework/check_env_changed_check_diff.sh
Labels: 00 - Ready for Review

#1368 [AGENT-6674] Add support for extra_body argument in vLLM
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.txt
  tests/functional/test_inference_gpu_predictors.py
Labels: 00 - Ready for Review
