Repository datarobot/datarobot-user-models, pull requests merged in 2025-01, with the labels that each got.

#1206 [RAPTOR-11813] Refactor Harness pipelines: move inline Bash code to repository scripts
  .harness/base_checks.yaml
  .harness/test_functional_by_framework.yaml
  .harness/test_functional_general.yaml
  harness_scripts/base_check/integration_tests_entrypoint.sh
  harness_scripts/base_check/unit_tests_entrypoint.sh
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
  harness_scripts/functional_general/general_tests_entrypoint.sh
  harness_scripts/functional_general/mlops_reporting_entrypoint.sh
  public_dropin_environments/python3_sklearn/Dockerfile.bak
  public_dropin_environments/python3_sklearn/requirements.txt.bak
  requirements_test.txt
Labels: 00 - Ready for Review

#1200 [RAPTOR-11788] Remove mlpiper from the DRUM scoring mode execution path
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/exceptions.py
  custom_model_runner/datarobot_drum/drum/root_predictors/__init__.py
  custom_model_runner/datarobot_drum/drum/root_predictors/generic_predictor.py
  custom_model_runner/datarobot_drum/resource/components/Python/generic_predictor/component.json
  tests/unit/datarobot_drum/drum/test_drum.py
Labels: 00 - Ready for Review

#1204 [RAPTOR-11798] Set the 'flask' dependency without specifying version constraints
  custom_model_runner/requirements.txt
Labels: 00 - Ready for Review

#1207 [RAPTOR-11814] Improve Harness scripts for better robustness and independence
  harness_scripts/base_check/integration_tests_entrypoint.sh
  harness_scripts/base_check/unit_tests_entrypoint.sh
  harness_scripts/common/create_and_source_venv.sh
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
  harness_scripts/functional_general/general_tests_entrypoint.sh
  harness_scripts/functional_general/mlops_reporting_entrypoint.sh
Labels: Ready for Review

#1211 [RAPTOR-11818] Ensure DRUM package installation uses the Python interpreter from the virtual environment
  custom_model_runner/setup.py
Labels: Ready for Review

#1201 [CFX-590] Prepare Notebook base environment for release
  public_dropin_notebook_environments/python311_notebook/env_info.json
  public_dropin_notebook_environments/python311_notebook/requirements.txt
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: 00 - Ready for Review

#1205 [RAPTOR-11809] Avoid using the mlops tracking agent to report statistics to DataRobot
  .gitignore
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/drum.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  custom_model_runner/requirements.txt
  harness_scripts/base_check/integration_tests_entrypoint.sh
  harness_scripts/common/create_and_source_venv.sh
  harness_scripts/common/update_python_to_meet_requirements.sh
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
  harness_scripts/functional_general/general_tests_entrypoint.sh
  harness_scripts/functional_general/mlops_reporting_entrypoint.sh
  public_dropin_environments/python3_sklearn/requirements.txt.bak
  public_dropin_environments/r_lang/requirements.txt
  tests/fixtures/unstructured_custom_mlops.py
  tests/functional/test_mlops_monitoring.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
Labels: 00 - Ready for Review

#1212 [MODEL-14740]Fix how sparse matrix is handled for comparison.
  custom_model_runner/datarobot_drum/drum/perf_testing.py
  tests/unit/datarobot_drum/drum/test_perf_testing.py
Labels: Ready for Review, Auto Merge on Green, Close Jira on Merge

#1213 [RAPTOR-11810] Release v1.16.0
  custom_model_runner/CHANGELOG.md
Labels: Ready for Review

#1214 [RAPTOR-11828] update base R env image
  docker/dropin_env_base_r/Dockerfile
  docker/dropin_env_base_r/README.md
  docker/dropin_env_base_r/build_image.sh
  docker/dropin_env_base_r/requirements.txt
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/requirements.txt
  tests/e2e/test_drop_in_environments.py
Labels: Ready for Review, Priority: Blocker, Close Jira on Merge

#1215 [RAPTOR-11836] Remove support for Apache Arrow
  custom_model_runner/CHANGELOG.md
  custom_model_runner/README.md
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/enum.py
  custom_model_runner/datarobot_drum/drum/root_predictors/predict_mixin.py
  custom_model_runner/datarobot_drum/drum/root_predictors/transform_helpers.py
  custom_model_runner/datarobot_drum/drum/utils/structured_input_read_utils.py
  custom_model_runner/drum_server_api.yaml
  custom_model_runner/requirements.txt
  example_dropin_environments/julia_mlj/dr_requirements.txt
  example_dropin_environments/python39_genai/dr_requirements.txt
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_sklearn_ironbank.tar.gz
  public_dropin_environments/python3_sklearn_stig_venv.tar.gz
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/requirements.txt
  public_dropin_gpu_environments/nim_llm/requirements.txt
  public_dropin_gpu_environments/python311_genai/dr_requirements.txt
  public_dropin_gpu_environments/triton_server/requirements.txt
  public_dropin_gpu_environments/vllm/requirements.txt
  tests/functional/test_drum_server_failures.py
  tests/functional/test_inference_per_framework.py
  tests/unit/datarobot_drum/drum/root_predictors/test_predict_mixin.py
  tests/unit/datarobot_drum/drum/utils/test_structured_input_read_utils.py
Labels: 00 - Ready for Review

#1217 Mark NIM container as not downloadable
  public_dropin_gpu_environments/nim_llm/env_info.json
Labels: 00 - Ready for Review, Auto Merge when Ready

#1216 [DSX-3771] Move NBX to CFX
  DRCODEOWNERS
Labels: Ready for Review

#1220 [RAPTOR-11857] Fix docker tag name when running DRUM with the docker option
  custom_model_runner/datarobot_drum/drum/drum.py
  tests/unit/datarobot_drum/drum/test_drum.py
Labels: Ready for Review, Auto Merge on Green

#1221 [RAPTOR-11859] Implement a reliable way to inject lines into a Docker file during testing
  public_dropin_environments/python3_sklearn/Dockerfile
  tests/functional/test_mlops_monitoring.py
Labels: Ready for Review, Auto Merge on Green

#1222 [RAPTOR-11860] Improve Harness script to skip Docker login in local development
  harness_scripts/functional_general/general_tests_entrypoint.sh
Labels: Ready for Review

#1225 [RAPTOR-11864] Move harness common scripts to tools directory
  harness_scripts/base_check/integration_tests_entrypoint.sh
  harness_scripts/base_check/unit_tests_entrypoint.sh
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
  harness_scripts/functional_general/general_tests_entrypoint.sh
  harness_scripts/functional_general/mlops_reporting_entrypoint.sh
  tools/create-and-source-venv.sh
  tools/update-python-to-meet-requirements.sh
Labels: Ready for Review

#1228 [RAPTOR-11867] release DRUM 1.16.1
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Needs Review: Core Modeling, Ready for Review, Close Jira on Merge

#1227 [RAPTOR-11866] update environments to have DRUM 1.16.1
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
Labels: Needs Review: Core Modeling, Ready for Review, Needs Review: GenAI Build (Buzok)

#1224 [AGENT-6667] No monitoring if training data is not available
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/language_predictors/base_language_predictor.py
  custom_model_runner/datarobot_drum/drum/language_predictors/python_predictor/python_predictor.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
Labels: Ready for Review

#1230 [AGENT-6684] Update NIM predictor for newer start server script
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#1229 [RAPTOR-11834] DR base python image is derived from an official Python image
  docker/dropin_env_base/Dockerfile
  docker/dropin_env_base/README.md
  docker/dropin_env_base/build_image.sh
  docker/dropin_env_base/pom.xml
  docker/dropin_env_base/pull_artifacts.sh
  docker/dropin_env_base/requirements.txt
  harness_scripts/common/common.sh
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  harness_scripts/functional_general/custom_java_predictor_entrypoint.sh
  harness_scripts/functional_general/general_tests_entrypoint.sh
  harness_scripts/functional_general/mlops_reporting_entrypoint.sh
  public_dropin_environments/python3_sklearn/Dockerfile
  tools/common.sh
Labels: Ready for Review, Auto Merge on Green

#1232 [AGENT-6675] Add support for CUSTOM_MODEL_WORKERS param in GPU predictors
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/base.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/nim_predictor.py
  custom_model_runner/datarobot_drum/drum/gpu_predictors/vllm_predictor.py
  public_dropin_gpu_environments/nim_llama_70b/env_info.json
  public_dropin_gpu_environments/nim_llama_70b/requirements.txt
  public_dropin_gpu_environments/nim_llama_8b/env_info.json
  public_dropin_gpu_environments/nim_llama_8b/requirements.txt
  public_dropin_gpu_environments/vllm/Dockerfile
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.txt
  tests/functional/test_inference_per_framework.py
Labels: 00 - Ready for Review, Auto Merge when Ready

#1234 [BUZZOK-24833] Fix issue with openai
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_gpu_environments/python311_genai/env_info.json
  public_dropin_gpu_environments/python311_genai/requirements.txt
Labels: 00 - Ready for Review, Needs Review: GenAI Build (Buzok)

#1226 [RAPTOR-11863] Add a script to generate model artifacts and copy them to required destination
  tools/generate-model-artifacts.sh
Labels: 00 - Ready for Review

#1233 [RAPTOR-11887] Remove unused archives that were unintentionally added
  public_dropin_environments/python3_sklearn_ironbank.tar.gz
  public_dropin_environments/python3_sklearn_stig_venv.tar.gz
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#1235 [RAPTOR-11892] Fix base image tag generation in the base image builder script
  docker/dropin_env_base/build_image.sh
Labels: 00 - Ready for Review

#1236 [RAPTOR-11835] Build the Python based drop-in environments from DR base python image
  harness_scripts/functional_by_framework/check_by_framework_run1_step_entrypoint.sh
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_xgboost/Dockerfile
Labels: 00 - Ready for Review

#1238 [CFX-1429] Upgrading to latest DRUM package in DR Notebooks drop-in Envs
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
  public_dropin_notebook_environments/python311_notebook_base/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_rapids/requirements.txt
  public_dropin_notebook_environments/python39_notebook_gpu_tf/env_info.json
  public_dropin_notebook_environments/python39_notebook_gpu_tf/requirements.txt
Labels: Ready for Review, Auto Merge on Green

#1237 [RAPTOR-11901] Unlock Python 3.12 for DRUM
  .harness/base_checks.yaml
  custom_model_runner/setup.py
  tests/unit/datarobot_drum/drum/language_predictors/test_base_language_predictor.py
Labels: Needs Review: Core Modeling, Needs Review: Custom Models, 00 - Ready for Review

#1239 [RAPTOR-11901] Bump DRUM version
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review
