Repository datarobot/datarobot-user-models, pull requests merged in 2025-05, with the labels that each got.

#1413 [RAPTOR-12446] Fix invalid test -nz
  tools/image-build-utils.sh
Labels: Ready for Review

#1410 [RAPTOR-12432] update changelog for list models
  custom_model_runner/CHANGELOG.md
Labels: 00 - Ready for Review

#1415 [RAPTOR-12416] add new reconciliation pipeline
  .harness/reconcile_dependencies_for_all_envs_based_on_parent_folder.yaml
  tools/env_version_update.py
Labels: 00 - Ready for Review

#1412 [RAPTOR-12334] Tracking X-Request-id in API requests to DRUM server
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/server.py
  tests/unit/datarobot_drum/drum/test_logger.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: 00 - Ready for Review

#1411 [MMM-19334] Add support for OTEL.
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/datarobot_drum/drum/root_predictors/prediction_server.py
  custom_model_runner/requirements.txt
Labels: 00 - Ready for Review

#1418 [MMM-19225] Bump DRUM version
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review

#1420 [RAPTOR-12492] unbump DRUM version back to 1.16.13 as it has not been released yet
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Needs Review: Core Modeling, 00 - Ready for Review, Close Jira on Merge

#1419 [BUZZOK-25745] Add support for streaming drum server run outputs
  custom_model_runner/datarobot_drum/drum/root_predictors/drum_server_utils.py
  custom_model_runner/datarobot_drum/drum/root_predictors/utils.py
  tests/unit/datarobot_drum/drum/root_predictors/test_drum_server_utils.py
Labels: 00 - Ready for Review

#1424 [MMM-19375] Update DRUM version in drop in environments
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
  public_dropin_gpu_environments/vllm/env_info.json
  public_dropin_gpu_environments/vllm/requirements.txt
  public_dropin_nim_environments/nim_sidecar/env_info.json
  public_dropin_nim_environments/nim_sidecar/requirements.txt
Labels: Needs Review: Core Modeling, Needs Review: Scoring Code, Ready for Review, Needs Review: GenAI Build (Buzok)

#1436 Removes codegen from owners
  DRCODEOWNERS
Labels: 00 - Ready for Review

#1434 [BUZZOK-257330] Update GenAI Agents environment to latest
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/agent/agent.py
  public_dropin_environments/python311_genai_agents/agent/cgroup_watchers.py
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/extensions/dataframe_formatter.py
  public_dropin_environments/python311_genai_agents/ipython_config.py
  public_dropin_environments/python311_genai_agents/jupyter_kernel_gateway_config.py
  public_dropin_environments/python311_genai_agents/requirements-genai.txt
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python311_genai_agents/run_agent.py
  public_dropin_environments/python311_genai_agents/start_server.sh
Labels: 00 - Ready for Review

#1437 [CFX-2759] Bump to PYTHON_EXACT_VERSION=3.11.11
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
Labels: 00 - Ready for Review

#1440 [RAPTOR-12536] add more required tools into envs
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/Dockerfile
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
Labels: 00 - Ready for Review, Close Jira on Merge

#1441 [RAPTOR-12536] add more required tools into envs 2
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/env_info.json
Labels: Needs Review: Core Modeling, Ready for Review, Close Jira on Merge

#1442 [RAPTOR-12538] bump jinja2 flask in public envs
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/java_codegen/requirements.txt
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311/requirements.txt
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai/requirements.txt
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_keras/requirements.txt
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_onnx/requirements.txt
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pmml/requirements.txt
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_pytorch/requirements.txt
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_sklearn/requirements.txt
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/python3_xgboost/requirements.txt
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments/r_lang/requirements.txt
Labels: Needs Review: Core Modeling, Ready for Review, Close Jira on Merge

#1443 [RAPTOR-12536] Add busybox to the ChainGuard drop-in envs
  public_dropin_environments/java_codegen/Dockerfile
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/Dockerfile
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python311_genai/Dockerfile
  public_dropin_environments/python311_genai/env_info.json
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python3_keras/Dockerfile
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/Dockerfile
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pmml/Dockerfile
  public_dropin_environments/python3_pmml/env_info.json
  public_dropin_environments/python3_pytorch/Dockerfile
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/Dockerfile
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/Dockerfile
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/Dockerfile
  public_dropin_environments/r_lang/env_info.json
  public_dropin_environments_sandbox/fips_python3_keras/Dockerfile
  public_dropin_environments_sandbox/fips_python3_keras/env_info.json
  public_dropin_nim_environments/nim_sidecar/Dockerfile
  public_dropin_nim_environments/nim_sidecar/env_info.json
Labels: Needs Review: Core Modeling, Needs Review: Tracking-Agent, 00 - Ready for Review, Priority: Blocker, Auto Merge when Ready

#1439 [MMM-19441] Missing chat hook error message for agentic workflow
  custom_model_runner/datarobot_drum/drum/root_predictors/predict_mixin.py
  tests/unit/datarobot_drum/drum/test_prediction_server.py
Labels: 00 - Ready for Review

#1445 More robust tracer setup.
  custom_model_runner/datarobot_drum/drum/adapters/model_adapters/python_model_adapter.py
  custom_model_runner/datarobot_drum/drum/common.py
  custom_model_runner/datarobot_drum/drum/main.py
  custom_model_runner/requirements.txt
Labels: Ready for Review

#1438 [BUZZOK-25849] Bump requirements to add opentelemetry for LLMs
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python311_genai_agents/run_agent.py
Labels: 00 - Ready for Review, Close Jira on Merge

#1459 Rename custom models
  DRCODEOWNERS
  dependbot.yml
Labels: 00 - Ready for Review

#1460 Rename custom models
  DRCODEOWNERS
  dependbot.yml
  tools/create-and-source-venv.sh
  tools/update-python-to-meet-requirements.sh
Labels: 00 - Ready for Review

#1461 Rename custom models
  dependbot.yml
Labels: 00 - Ready for Review

#1465 Change agent ownership
  DRCODEOWNERS
Labels: 00 - Ready for Review

#1466 Change agent ownership
  DRCODEOWNERS
Labels: Ready for Review

#1467 [BUZZOK-25993] Sync run_agent.py with latest changes
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/ipython_config.py
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
  public_dropin_environments/python311_genai_agents/run_agent.py
Labels: 00 - Ready for Review, Auto Merge on Green, Close Jira on Merge

#1492 [MMM-19600] release DRUM v1.16.15
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: 00 - Ready for Review, Close Jira on Merge, Needs Review: GenAI Build (Buzok)
