Repository datarobot/datarobot-user-models, pull requests merged in 2025-09, with the labels that each got.

#1648 [RAPTOR-14353] Bump DRUM version
  custom_model_runner/CHANGELOG.md
  custom_model_runner/datarobot_drum/drum/description.py
Labels: Ready for Review

#1653 [RAPTOR-14592] Bump moderation library version
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
Labels: Ready for Review

#1660 [CFX-3593] Update drop-in notebook env to have latest drgithelper binary
  public_dropin_notebook_environments/py311_notebook_dropin.tar.gz
  public_dropin_notebook_environments/python311_notebook_base/Dockerfile
  public_dropin_notebook_environments/python311_notebook_base/env_info.json
Labels: Ready for Review

#1663 [RAPTOR-14653] bump env version IDs to reinstall
  public_dropin_environments/java_codegen/env_info.json
  public_dropin_environments/python311/env_info.json
  public_dropin_environments/python3_keras/env_info.json
  public_dropin_environments/python3_onnx/env_info.json
  public_dropin_environments/python3_pytorch/env_info.json
  public_dropin_environments/python3_sklearn/env_info.json
  public_dropin_environments/python3_xgboost/env_info.json
  public_dropin_environments/r_lang/env_info.json
Labels: Needs Review: Core Modeling, Ready for Review

#1676 [BUZZOK-27766] Update GenAI agents environment synchronize package and dockerfile changes
  public_dropin_environments/python311_genai_agents/Dockerfile
  public_dropin_environments/python311_genai_agents/Dockerfile.local
  public_dropin_environments/python311_genai_agents/agent/requirements-agent.txt
  public_dropin_environments/python311_genai_agents/env_info.json
  public_dropin_environments/python311_genai_agents/requirements.in
  public_dropin_environments/python311_genai_agents/requirements.txt
Labels: 00 - Ready for Review, Close Jira on Merge
